### ISSUE TITLE
IMPORT_FILE variable not set in Notebook

### ISSUE THREAD

**Issue by brianchunkang** [GoogleCloudPlatform/vertex-ai-samples#1122]
## Expected Behavior
IMPORT_FILE is set to a local file/GCS path

## Actual Behavior
Called in gsutil command but not set in notebook

## Steps to Reproduce the Problem

1. Go to the gsutil step that uses IMPORT_FILE in this notebook, and it will create blank files: https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/explainable_ai/sdk_custom_tabular_regression_batch_explain.ipynb

## Specifications

- Version:
- Platform:

**Comment by andrewferlitsch** [comment]
Fixed in PR 1173
