### ISSUE TITLE
aiplatform.featurestore.entity_type.read() not in SDK

### ISSUE THREAD

**Issue by jth1911** [GoogleCloudPlatform/vertex-ai-samples#1162]
## Expected Behavior
1. Feature values should be returned. 

## Actual Behavior

AttributeError: 'EntityType' object has no attribute 'read'

## Steps to Reproduce the Problem
1. Create a user entity_type and call the read method

## Specifications
- Version: Python 3.7
- Platform: Linux

**Comment by jth1911** [comment]
Please ignore as I overlooked the method.  It does exist.

**Comment by davidcavazos** [comment]
Thanks for the clarification, I'm closing this.
