### ISSUE TITLE
Matching Engine: Queries with filtering do not work as expected

### ISSUE THREAD

**Issue by fedprt** [GoogleCloudPlatform/vertex-ai-samples#1230]
I tried to run this notebook: https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/matching_engine/stream_update_for_matching_engine.ipynb
I got an issue with the filtering step:
Let's say glove100.json is:

```
{"id":"0","embedding":[-0.99544,-2.3651],"restricts":[{"namespace": "class", "allow_list": ["0"]}],"crowding_tag":"a"}
{"id":"1","embedding":[0.42052,-1.1817],"restricts":[{"namespace": "class", "allow_list": ["1"]}],"crowding_tag":"b"}
{"id":"2","embedding":[-0.10185,0.59817],"restricts":[{"namespace": "class", "allow_list": ["2"]}],"crowding_tag":"a"}
```

If I try to filter in this way:

```
for val in query:
    request.float_val.append(val)

restrict = match_service_pb2.Namespace()
restrict.name = "class"
restrict.allow_tokens.append("1")
request.restricts.append(restrict)
response = stub.Match(request)
response
```

I do not get any response (empty result). If from the above code I remove the "restrict block", it works (of course without filtering).

```
request = match_service_pb2.MatchRequest()
request.deployed_index_id = DEPLOYED_INDEX_ID
for val in query:
    request.float_val.append(val)
# restrict = match_service_pb2.Namespace()
# restrict.name = "class"
# restrict.allow_tokens.append("1")
# request.restricts.append(restrict)
response = stub.Match(request)
response
```
response:

```
neighbor {
  id: "0"
  distance: 17.592369079589844
}
neighbor {
  id: "1"
  distance: 17.592369079589844
}
...
```

But, if I add a new vector by Vertex SDK for Python ([link](https://github.com/googleapis/python-aiplatform.git@main)), in this way:

```
insert_datapoints_payload = aiplatform_v1.IndexDatapoint(
    datapoint_id="3",
    feature_vector=query,
    restricts=[{"namespace": "class", "allow_list": ["3"]}],
    # crowding_tag=aiplatform_v1.IndexDatapoint.CrowdingTag(crowding_attribute="b"), <-- this does not seem to change anything
)

upsert_request = aiplatform_v1.UpsertDatapointsRequest(
    index=INDEX_RESOURCE_NAME, datapoints=[insert_datapoints_payload]
)

index_client.upsert_datapoints(request=upsert_request)
```

and then I try to filter in the same way above with filter class == "3", I get the right response.

It seems like the allow_tokens are "seen" by vertex only when I insert a new vector by Vertex SDK and not when I specify them in the initial glove100.json.

Moreover, if I update a datapoint where the filter did not work, for example id=1:
```
update_datapoints_payload = aiplatform_v1.IndexDatapoint(
    datapoint_id="1",
    feature_vector=embedding,
    restricts=[{"namespace": "class", "allow_list": ["1"]}],
    # crowding_tag=aiplatform_v1.IndexDatapoint.CrowdingTag(crowding_attribute="b"),
)

upsert_request = aiplatform_v1.UpsertDatapointsRequest(
    index=INDEX_RESOURCE_NAME, datapoints=[update_datapoints_payload]
)

index_client.upsert_datapoints(request=upsert_request)

response = stub.Match(request)
response
```
The filter for class=1 starts to work.

Is there a way to know what is actually stored in the index? I mean a kind of "SELECT * FROM myindex" in order to check embeddings and tokens stored.

Any ideas on how to solve this issue?

Thanks in advance

## Steps to Reproduce the Problem

Follow:  https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/matching_engine/stream_update_for_matching_engine.ipynb
I tried from local and from workbench, the result is the same.

## Specifications

- Version: Python 3.7.9
- Platform: Matching Engine. zone: europe-west1

**Comment by ivanmkc** [comment]
Let me redirect this to the backend team.

**Comment by ivanmkc** [comment]
I feel like the sample has a bug. I would think that "a" and "b" should be in `allow_list` and not in the `crowding_tag` attribute.

**Comment by ivanmkc** [comment]
crowding_tag is explained here and doesn't seem relevant to filtering except as a limiter: https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform_v1.types.IndexDatapoint.CrowdingTag

**Comment by fedprt** [comment]
Hi @ivanmkc, Thank you for replying! :)
> I feel like the sample has a bug. I would think that "a" and "b" should be in `allow_list` and not in the `crowding_tag` attribute.

What do you mean by "sample has a bug"? 
1) My data are the glove100.json generated like [here](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/matching_engine/stream_update_for_matching_engine.ipynb) and I did not change anything, and if there is a bug I expect that also the query without filtering does not work. I attached the glove100.json [glove100.txt](https://github.com/GoogleCloudPlatform/vertex-ai-samples/files/10011859/glove100.txt). I uploaded to the bucket for index generation.  
2) The _allow_lists_ have numbers and I am filtering on numbers, not on "a" or "b". I reported the _crowding_tag_ for completeness (since I followed the notebook). Btw, just to be sure, I tried with and without the _crowding_tag_, the results do not change: the  "restrict" filtering works only on vectors added later and not with the vectors added at the beginning with glove100.json.

**Comment by peterping666** [comment]
Hi @fedprt,

For the filtering step, did you initialize the request by 
```
request = match_service_pb2.MatchRequest()
request.deployed_index_id = DEPLOYED_INDEX_ID
```
If not yet, maybe you can try to see if that can fix the issue. In your example, it could look like this:
```
request = match_service_pb2.MatchRequest()
request.deployed_index_id = DEPLOYED_INDEX_ID
for val in query:
    request.float_val.append(val)

restrict = match_service_pb2.Namespace()
restrict.name = "class"
restrict.allow_tokens.append("1")
request.restricts.append(restrict)
response = stub.Match(request)
response
```

**Comment by fedprt** [comment]
> Hi @fedprt,
> 
> For the filtering step, did you initialize the request by
> 
> ```
> request = match_service_pb2.MatchRequest()
> request.deployed_index_id = DEPLOYED_INDEX_ID
> ```
> 
> If not yet, maybe you can try to see if that can fix the issue. In your example, it could look like this:
> 
> ```
> request = match_service_pb2.MatchRequest()
> request.deployed_index_id = DEPLOYED_INDEX_ID
> for val in query:
>     request.float_val.append(val)
> 
> restrict = match_service_pb2.Namespace()
> restrict.name = "class"
> restrict.allow_tokens.append("1")
> request.restricts.append(restrict)
> response = stub.Match(request)
> response
> ```

Hi @peterping666 ,

I confirm I initialized the request as you said,  just I did not paste the 2 code rows.

**Comment by Q-SudhirDeshmukh** [comment]
Hi when I am trying following:
`
response = my_index_endpoint.match(
    deployed_index_id=DEPLOYED_INDEX_ID,
    queries=test[:1],
    num_neighbors=NUM_NEIGHBOURS,
    filter=[Namespace("class", ["even"])],
)`

This return empty list. But if I remove filter I get expected output

Can someone please direct, how to use filter in this case ?

**Comment by peterping666** [comment]
Hi @fedprt and @Q-SudhirDeshmukh, 

I checked with the team, the "allow_list" for creating index is not supported yet. It needs to be "allow". So when you write a glove100.json, change "allow_list" to "allow". Then use that file to create a new index.
It will look like this:
```
with open("glove100.json", "w") as f:
    for i in range(len(train)):
        f.write('{"id":"' + str(i) + '",')
        f.write('"embedding":[' + ",".join(str(x) for x in train[i]) + "],")
        f.write(
            '"restricts":[{"namespace": "class", "allow": ["' + str(i) + '"]}],'
        )
        f.write('"crowding_tag":' + ('"a"' if i % 2 == 0 else '"b"') + "}")
        f.write("\n")
        if i >= 100:
            break
```
This should make the filtering work. 
For StreamUpdate Upsert datapoints, you can still use "allow_list" because that's supported by StreamUpdate.

**Comment by peterping666** [comment]
I have updated "allow_list" to "allow" in main branch.

**Comment by peterping666** [comment]
@fedprt  If the issue has been fixed, maybe we can close this issue.

**Comment by fedprt** [comment]
hi @peterping666 ,
Thank you, I will try in the next few days if it works

**Comment by fedprt** [comment]
Hi @peterping666 ,
I confirm it works now.
Thank you very much!
