### ISSUE TITLE
Installation of scikit learn inside @component do not work and the deployment of the model as well

### ISSUE THREAD

**Issue by felattaoui** [GoogleCloudPlatform/vertex-ai-samples#1251]
## Expected Behavior
Deploying a sklearn pipeline

## Actual Behavior
The pipeline fails for at least 2 reasons I have identified : 
to install scikit-learn, you should write scikit learn in the package to install not sklearn (deprecated).
I think that we should add "db-dtypes" as well.
Last thing, I think that since some updates in scikit-learn and joblib the dump of the model do not work properly 

## Steps to Reproduce the Problem

1. Launch all the cells of the notebook until run1.submit() to reproduce the several bugs
1.
1.

## Specifications

- Version:
- Platform:

**Comment by andrewferlitsch** [comment]
@felattaoui which notebook are you referring to?

**Comment by andrewferlitsch** [comment]
fixed occurrence in two official notebooks
