### ISSUE TITLE
Using model.resource_name and endpoint.resource_name to instantiate the model and endpoint resources

### ISSUE THREAD

**Issue by candicehou07** [GoogleCloudPlatform/vertex-ai-samples#126]
## Expected Behavior
In the notebooks/community/managed_notebooks/fraud_detection/fraud-detection-model.ipynb
we need to Instantiate the resources using the resource names.

model = aiplatform.Model(model_name=model.resource_name) 
endpoint = aiplatform.Endpoint(endpoint_name=endpoint.resource_name)

## Actual Behavior

Failed to instantiate the resources using the displayed_names

## Steps to Reproduce the Problem

1. Create a Managed-notebook in Vertex AI Workbench
2. open the terminal and git clone the repo
3. go to notebooks/community/managed_notebooks/fraud_detection/fraud-detection-model.ipynb
4. run the cells until cell of "Deploy the model to the created Endpoint"
5. run the current cell

## Specifications
![Screen Shot 2021-11-03 at 5 40 37 PM](https://user-images.githubusercontent.com/89653023/140214226-0b9473dc-580e-45cd-ba04-bcd5973c2f02.png)

- Version:
- Platform:

**Comment by kweinmeister** [comment]
Hi, a few questions to troubleshoot  this:

* Can you confirm that you've successfully trained a model in the previous steps?
* Also you've updated the `DEPLOYED_MODEL_NAME` variable?
* Can you provide the details of the error message you're seeing?

**Comment by matthewayne** [comment]
@aarondietz234 Can you take a look at this?

**Comment by candicehou07** [comment]
Hi, to answer the questions:

- I have trained the model and uploaded the model to Vertex Models
(screenshot included)
![Screen Shot 2021-11-08 at 3 20 00 PM](https://user-images.githubusercontent.com/89653023/140819936-ac7b88c6-7968-4de2-a1cf-f193e549c6a1.png)

- I updated the DEPLOYED_MODEL_NAME as the deployed model name, "fraud-detection-model-v1"
  - variables used to retrieve the model and the endpoint: MODEL_DISPLAY_NAME: fraud-detection-model
ENDPOINT_DISPLAY_NAME: fraud-detection-model-ep1
![Screen Shot 2021-11-08 at 3 22 17 PM](https://user-images.githubusercontent.com/89653023/140820195-ec96a423-bbbd-4336-82fe-961959a9badf.png)

- Error Message:



---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/google/api_core/grpc_helpers.py in error_remapped_callable(*args, **kwargs)
     65         try:
---> 66             return callable_(*args, **kwargs)
     67         except grpc.RpcError as exc:

/opt/conda/lib/python3.7/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    945                                       wait_for_ready, compression)
--> 946         return _end_unary_response_blocking(state, call, False, None)
    947 

/opt/conda/lib/python3.7/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    848     else:
--> 849         raise _InactiveRpcError(state)
    850 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "List of found errors:	1.Field: name; Message: Invalid Model resource name.	"
	debug_error_string = "{"created":"@1636406161.921552593","description":"Error received from peer ipv4:142.250.128.95:443","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"List of found errors:\t1.Field: name; Message: Invalid Model resource name.\t","grpc_status":3}"
>

The above exception was the direct cause of the following exception:

InvalidArgument                           Traceback (most recent call last)
/tmp/ipykernel_1/2157564676.py in <module>
      1 # instantiate the model and endpoint resources
----> 2 model = aiplatform.Model(model_name=MODEL_DISPLAY_NAME)
      3 endpoint = aiplatform.Endpoint(endpoint_name=ENDPOINT_DISPLAY_NAME)
      4 
      5 # deploy the model to the endpoint

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/models.py in __init__(self, model_name, project, location, credentials)
   1394             resource_name=model_name,
   1395         )
-> 1396         self._gca_resource = self._get_gca_resource(resource_name=model_name)
   1397 
   1398     # TODO(b/170979552) Add support for predict schemata

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/base.py in _get_gca_resource(self, resource_name)
    531         )
    532 
--> 533         return getattr(self.api_client, self._getter_method)(name=resource_name)
    534 
    535     def _sync_gca_resource(self):

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform_v1/services/model_service/client.py in get_model(self, request, name, retry, timeout, metadata)
    589 
    590         # Send the request.
--> 591         response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
    592 
    593         # Done; return the response.

/opt/conda/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py in __call__(self, timeout, retry, *args, **kwargs)
    140             kwargs["metadata"] = metadata
    141 
--> 142         return wrapped_func(*args, **kwargs)
    143 
    144 

/opt/conda/lib/python3.7/site-packages/google/api_core/grpc_helpers.py in error_remapped_callable(*args, **kwargs)
     66             return callable_(*args, **kwargs)
     67         except grpc.RpcError as exc:
---> 68             raise exceptions.from_grpc_error(exc) from exc
     69 
     70     return error_remapped_callable

InvalidArgument: 400 List of found errors:	1.Field: name; Message: Invalid Model resource name.	

- I checked the [Apiplatform SDK](https://googleapis.dev/python/aiplatform/latest/aiplatform.html?highlight=aiplatform#module-google.cloud.aiplatform), both APIs need to use resource name or ID to retrieve model and endpoint. Here we're using the display names rather than the resource names.
![Screen Shot 2021-11-08 at 3 24 17 PM](https://user-images.githubusercontent.com/89653023/140820502-b086b49f-d4c1-4057-a818-0a78ac6f8c5d.png)
![Screen Shot 2021-11-08 at 3 24 28 PM](https://user-images.githubusercontent.com/89653023/140820506-0a9a5e5e-6133-4406-aadc-09700df15158.png)

I tried to run with resource_name and it worked. I hope this helps with troubleshooting!
