### ISSUE TITLE
Custom training that uses BigQuery Python library should use an explicit PROJECT_ID

### ISSUE THREAD

**Issue by ivanmkc** [GoogleCloudPlatform/vertex-ai-samples#1269]
## Expected Behavior
Some notebooks that demonstrate custom training use an inferred project:

```
from google.cloud import bigquery

client = bigquery.Client()
```

This will cause permission issues. See:

See https://cloud.google.com/vertex-ai/docs/workbench/managed/executor#explicit-project-selection.

## Solution
Use an explicit project id:

```
import os

from google.cloud import bigquery

project_number = os.environ["CLOUD_ML_PROJECT_ID"]

client = bigquery.Client(project=project_number)
```

**Comment by andrewferlitsch** [comment]
This seems obsolete. There are no notebooks referenced here.
