### ISSUE TITLE
outdated code, vertexAi doesn't have Model

### ISSUE THREAD

**Issue by AharonSterman** [GoogleCloudPlatform/vertex-ai-samples#1311]
## Expected Behavior
code should run

## Actual Behavior
Model not retrieved

<img width="889" alt="Screen Shot 2022-11-30 at 9 21 41" src="https://user-images.githubusercontent.com/109730859/204733081-9d90bca4-4fe3-4500-b915-169ba481b64a.png">

![Screen Shot 2022-11-30 at 9 23 25](https://user-images.githubusercontent.com/109730859/204733542-7fe2019e-945a-4eed-abec-1c583bb5510c.png)

## Steps to Reproduce the Problem
Running the tutorial in colab

## Specifications

- Version:

- Platform:

**Comment by andrewferlitsch** [comment]
There is no reference to a notebook. Weekly regression testing should pick this up if problem still in existing notebook
