### ISSUE TITLE
Problem in the preprocessing function while defining the serving_default signature for a model in a community notebook

### ISSUE THREAD

**Issue by ayushjn20** [GoogleCloudPlatform/vertex-ai-samples#133]
## Problem
In the section `Deployment` > `Upload the model for serving` > `Serving function for image data` of [this](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/ec3fd38b0bce06b29807adbf3710b05343bc07a3/notebooks/community/gapic/custom/showcase_custom_image_classification_online.ipynb) notebook, the preprocess function is defined as,

```python
def _preprocess(bytes_input):
    decoded = tf.io.decode_jpeg(bytes_input, channels=3)
    decoded = tf.image.convert_image_dtype(decoded, tf.float32)
    resized = tf.image.resize(decoded, size=(32, 32))
    rescale = tf.cast(resized / 255.0, tf.float32)
    return rescale
```

For this, the author has written, 

> resized / 255.0 - Rescales (normalization) the pixel data between 0 and 1.

But if we check the working of [tf.image.convert_image_dtype](https://www.tensorflow.org/api_docs/python/tf/image/convert_image_dtype) as per the current TensorFlow version `2.7.0`, we see that this function not only converts the `dtype`, but also normalizes/rescales the image according to the target `dtype`.

In the documentation, it is mentioned,

> Images that are represented using floating-point values are expected to have values in the range `[0,1)`. Image data stored in integer data types are expected to have values in the range `[0, MAX]`, where `MAX` is the largest positive representable number for the data type.

This means that while converting to `tf.float32` it also normalizes the `decoded` image in the range `[0,1]`. Therefore, the line `rescale = tf.cast(resized / 255.0, tf.float32)` must be omitted.

## Specifications

- Version: Tensorflow Version: 2.7.0

**Comment by andrewferlitsch** [comment]
From TF 2.5 on, the automatic scaling is correct (as noted by the issue poster). For TF 2.4 and earlier documentation, it is vague.
