### ISSUE TITLE
PyTorch intro notebook: remove non-Vertex training example

### ISSUE THREAD

**Issue by telpirion** [GoogleCloudPlatform/vertex-ai-samples#1403]
[This sample](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/community-content/pytorch_text_classification_using_vertex_sdk_and_gcloud/pytorch-text-classification-vertex-ai-train-tune-deploy.ipynb) didn't finish training for me the first time I ran it (PyTorch w/ HuggingFace model local training).

## Expected Behavior

All content in notebook runs without issue. Time intensive operations are clearly labeled as such in the explanatory text that precedes it.

## Actual Behavior

Local PyTorch training on Vertex WorkBench fails to complete after 24 hours. 

## Steps to Reproduce the Problem

1. Open the notebook in Vertex WorkBench.
1. Run the first set of cells to train a HuggingFace BERT model on PyTorch locally
1. Wait and wait and wait

## Observations

If we do keep this section, we should be sure to check for the availability of GPUs and CUDA.

```
if torch.cuda.is_available():
   torch.device('cuda')
```

**Comment by andrewferlitsch** [comment]
We don't support community-content (as-is)
