### ISSUE TITLE
import_file not consumed in hyperparam tuning notebook

### ISSUE THREAD

**Issue by hyuatpc** [GoogleCloudPlatform/vertex-ai-samples#1443]
## Expected Behavior
In the HPT notebook https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/cad623ef84882f410fcc0dc39527be25a5e5f584/notebooks/community/ml_ops/stage3/get_started_with_hpt_pipeline_components.ipynb,  `import_file` is suggested to be part of the `parameter_values`. Ideally it should demonstrate how to use this variable in the HPT pipeline.

## Actual Behavior
`import_file` is mentioned but not shown how to get passed to the HPT pipeline.

## Steps to Reproduce the Problem

1. Open https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/cad623ef84882f410fcc0dc39527be25a5e5f584/notebooks/community/ml_ops/stage3/get_started_with_hpt_pipeline_components.ipynb
1. Search for `import_file`

## Specifications

- Version:
- Platform:

**Comment by ivanmkc** [comment]
FYI @andrewferlitsch

**Comment by andrewferlitsch** [comment]
this was previously fixed
