### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools'

### ISSUE THREAD

**Issue by moussetmar** [GoogleCloudPlatform/vertex-ai-samples#1474]
## Expected Behavior
Launch of train pipeline by AI platform.

## Actual Behavior
When trying to execute setup.py of the form in attached files, I have the error 
`ModuleNotFoundError: No module named 'setuptools'`
Even if I try to reinstall setup tool in the launcher.sh before hand.

## Code

launcher.sh:
`
cd repertory

gcloud config set project data-test-255312

JOB_NAME="My-job-name"
JOB_DIR="path-to-gcs"

gcloud ai-platform jobs submit training $JOB_NAME \
  --config config.yaml \
  --package-path trainer/ \
  --module-name trainer.task \
  --region europe-west1 \
  --python-version 3.7 \
  --runtime-version 2.6 \
  --job-dir $JOB_DIR \
  -- \
  --site {site} \
  --metacamp {metacamp} \
  --date {date} \
  --hour {hour} \
  --worker_batches {worker_batches} \
  --tasks {tasks} \
  --model {model} \
  --epochs {epochs} \
  --batch_size {batch_size}
`
config.yaml

`
trainingInput:
    runtimeVersion: "2.6"
    pythonVersion: "3.7"
    scaleTier: CUSTOM
    masterType: n1-standard-16
    workerType: n1-standard-16
    parameterServerType: n1-standard-16
    useChiefInTfConfig: true
    workerCount: {{worker_batches}}
    workerConfig:
      acceleratorConfig:
        count: 1
        type: NVIDIA_TESLA_T4
    parameterServerCount: 1
    scheduling:
            maxWaitTime: 7200s
            maxRunningTime: 86400s
`

setup.py:
`
from setuptools import find_packages
from setuptools import setup

REQUIRED_PACKAGES = ['tensorflow==2.5.0','tensorflow-io==0.19.1','jinja2~=3.0.1','GPUtil']

setup(
    name='trainer',
    version='0.1',
    install_requires=REQUIRED_PACKAGES,
    packages=find_packages(),
    include_package_data=True,
    description='My training application package.'
)
`

- Version: python 3.7 runtime 2.6
- Platform: AI platform

**Comment by ivanmkc** [comment]
What sample are you referring to?

**Comment by moussetmar** [comment]
> What sample are you referring to?

If I understand your question correctly it's "When does it crashes?"

It seems to bug when importing setuptools in the setup.py:

```from setuptools import find_packages
from setuptools import setup

REQUIRED_PACKAGES = ['tensorflow==2.5.0','tensorflow-io==0.19.1','jinja2~=3.0.1','GPUtil']

setup(
name='trainer',
version='0.1',
install_requires=REQUIRED_PACKAGES,
packages=find_packages(),
include_package_data=True,
description='My training application package.'
)```

I also tried to print the list of pip modules and setuptools is in it.

**Comment by moussetmar** [comment]
Wrong place for the issue, I close it.
