### ISSUE TITLE
Cell notes say the predict job will use GCS, not BigQuery, but BigQuery is used.

### ISSUE THREAD

**Issue by stevewalker-de** [GoogleCloudPlatform/vertex-ai-samples#1482]
https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/automl/sdk_automl_tabular_forecasting_batch.ipynb

"batch_predict can export predictions either to BigQuery or GCS. The BigQuery options are commented out below and the predictions will be exported to the BUCKET_URI"

PREDICTION_DATASET_BQ_PATH = (
    "bq://bigquery-public-data:iowa_liquor_sales_forecasting.2021_sales_predict"
)

batch_prediction_job = model.batch_predict(
    job_display_name=f"iowa_liquor_sales_forecasting_predictions_{UUID}",
    bigquery_source=PREDICTION_DATASET_BQ_PATH,
    instances_format="bigquery",
    bigquery_destination_prefix=batch_predict_bq_output_uri_prefix,
    predictions_format="bigquery",
    generate_explanation=True,
    sync=False,
)

print(batch_prediction_job)

**Comment by ivanmkc** [comment]
Thanks, will fix.
