### ISSUE TITLE
[Notebook Request] Need a notebook in samples where we have made an end to end custom model deployment all using vertex ai pipelines

### ISSUE THREAD

**Issue by Rstar1998** [GoogleCloudPlatform/vertex-ai-samples#1521]
Need a notebook in samples where we have made an end to end custom model deployment all using vertex ai pipelines.
There lacks a notebook which explains about how incrementally upload model to model registry , create an endpoint and deploy model. There are many notebooks which explains uptil model training part , but things like recurrently uploading models to vertex ai model artifacts (versioning )  , creating vertex ai endpoint (skip if already created) and deploying model using endpoint can be implemented in vertex ai pipelines (using best practices) which can help the community

**Comment by andrewferlitsch** [comment]
there are several notebooks in official/pipelines that cover this. For example:
https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb
