### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by nxorable** [GoogleCloudPlatform/vertex-ai-samples#1522]
https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb

Has a broken link to:
https://google-cloud-pipeline-components.readthedocs.io/en/latest/google_cloud_pipeline_components.aiplatform.html#module-google_cloud_pipeline_components.aiplatform

**Comment by andrewferlitsch** [comment]
fix submitted
