### ISSUE TITLE
No module named 'google.cloud.aiplatform' in sdk_custom_image_classification_online_explain.ipynb

### ISSUE THREAD

**Issue by vipinn123** [GoogleCloudPlatform/vertex-ai-samples#153]
## Steps to Reproduce the Problem

1. Cloned this git repository into a Managed Notebooks Environment in Vertex AI 
2. Tried running the notebook sample sdk_custom_image_classification_online_explain.ipynb
3. the cell "import google.cloud.aiplatform as aip" errors out with ModuleNotFoundError: No module named 'google.cloud.aiplatform'
## Specifications

- Version:
- Platform:

**Comment by andrewferlitsch** [comment]
@vipinn123

I ran the notebook in a Managed Notebook Environment with defaul Python local kernel. The notebook successfully imported google.cloud.aiplatform:

Set up variables
Next, set up some variables used throughout the tutorial.

Import libraries and define constants
import google.cloud.aiplatform as aip
