### ISSUE TITLE
PyTorch intro notebook: Hyperparameter tuning needs to be sync

### ISSUE THREAD

**Issue by telpirion** [GoogleCloudPlatform/vertex-ai-samples#1572]
When running the hyperparameter tuning job in [this sample](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/community-content/pytorch_text_classification_using_vertex_sdk_and_gcloud/pytorch-text-classification-vertex-ai-train-tune-deploy.ipynb), the tuning job is set to `sync=False`. Unfortunately this means that the Vertex SDK will swallow any errors that arise before the job is started (e.g. a mismatch in bucket & API regions).

## Expected Behavior

The cell where `hp_job.run()` is called has `sync=True`. The method generates output as the job is being queued and run.

## Actual Behavior

The cell where `hp_job.run()` is called has `sync=False`. No output is generated, even in an error state.

## Steps to Reproduce the Problem

1. Create a bucket in one region (e.g. us-west1)
1. Initialize the Vertex SDK in another region (e.g. us-central1)
1. Run the Hyperparameter tuning cells

## Additional

[This issue has a corresponding issue on the Vertex SDK](https://github.com/googleapis/python-aiplatform/issues/2003).

**Comment by andrewferlitsch** [comment]
We don't support community-content (as-is)
