### ISSUE TITLE
Code for Normalization is wrong

### ISSUE THREAD

**Issue by jchavezar** [GoogleCloudPlatform/vertex-ai-samples#1599]
## Actual Behavior
Normalization happens over 13 rows not over columns (features)

  def scale(feature):
    max = np.max(feature)
    feature = (feature / max).astype(np.float)
    return feature, max
  params = []
  for _ in range(13):
    x_train[_], max = scale(x_train[_])
    x_test[_], _ = scale(x_test[_])
    params.append(max)

## Steps to Reproduce the Problem

1. Change line for this one: x_train[_:_+1:]
1.
1.

## Specifications

- Version:
- Platform:

**Comment by andrewferlitsch** [comment]
fixed
