### ISSUE TITLE
Error: Pipelines introduction for KFP

### ISSUE THREAD

**Issue by rafaelgildin** [GoogleCloudPlatform/vertex-ai-samples#1668]
## Expected Behavior
Successfully run in vertex pipelines, by showing green in all nodes, since I'm following a tutorial that should work: https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/Fixed-the-component-versions/notebooks/official/pipelines/pipelines_intro_kfp.ipynb

## Actual Behavior
Failing in the first node by the following error:
ERROR: No matching distribution found for kfp==1.8.19

## Steps to Reproduce the Problem

1.Run the notebook inside vertex ai workbench.

## Specifications

- Version: Python==3.7.12
- Platform: vertex ai workbench user-managed notebook.

**Comment by andrewferlitsch** [comment]
Verified install works on Workbench:

! pip3 install --upgrade google-cloud-aiplatform \
                        google-cloud-storage \
                        kfp \
                        google-cloud-pipeline-components
