### ISSUE TITLE
Default pipeline_root is not shown in the UI

### ISSUE THREAD

**Issue by AFTownsend** [GoogleCloudPlatform/vertex-ai-samples#1680]
## Expected Behavior
When you set the default pipeline root in the dsl decorator it shows in Vertai AI Pipeline UI
```
        @dsl.pipeline(
            name=name, description=description, pipeline_root=root
        )
```

## Actual Behavior
The pipeline root is either not set or set to the bucket from the last run even if that run was is in a different GCP project. 

## Steps to Reproduce the Problem

1. Deploy a pipeline template to GCP using the kubeflow cli with a pipeline root set
2. Run the pipeline the bucket will not be set if it is set it to a **different** bucket
3. Redeploy the pipeline
4. Run the pipeline and default bucket will the different bucket you set in step 2

## Specifications

- Version: kfp = "2.0.0b8"
- Platform: Vertex AI

**Comment by ChaseLyall** [comment]
@AFTownsend , can you please provide the minimal code to reproduce?

In all clients ([KFP](https://kubeflow-pipelines.readthedocs.io/en/master/source/client.html#kfp.client.Client.create_run_from_pipeline_package.pipeline_root), [Vertex Python SDK](https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform.PipelineJob#parameters), and Google Cloud Console GUI, the pipeline_root defined in the pipeline definition is overridable as part of the runtime config. Please make sure you are not overriding it. Also, if executing on Vertex AI Pipelines, I would recommend the Vertex AI aiplatform Python SDK.

**Comment by AFTownsend** [comment]
Hi Chase,

Thank you for getting back to me. The pipeline and deployment looks like the snippet below. The pipeline is that ran through the vertex ai ui 

```
@dsl.pipeline(
    name="my-pipeline", description="My pipeline", pipeline_root="gs://my-bucket"
)
def simple_pipeline(word: str, number: int) -> None:
        simple(
            word=word,
            number=number,
        )

template_path = f"my-folder/my-pipeline.yaml"
compiler.Compiler().compile(
    pipeline_func=simple_pipeline, package_path=template_path
)

client = RegistryClient(
    host=f"https://{config.REGION}-kfp.pkg.dev/{config.PROJECT}/{config.PIPELINE_REGISTRY}"
)

client.upload_pipeline(
    file_name=template_path,
    tags=["latest"],
    extra_headers={"description": "My Pipeline"},
)
```

**Comment by andrewferlitsch** [comment]
Not a notebook tutorial issue, reassigning.

**Comment by AFTownsend** [comment]
@andrewferlitsch, what happens with this ticket now? You said it's been reassigned but I'm not sure who or what to?

**Comment by andrewferlitsch** [comment]
@AFTownsend 
Sorry the conversation died here: https://b.corp.google.com/issues/276623466#comment6. Desmond says we would need access to their data. Can you please have them open a Support ticket? In general it seems like non-notebook issues should be redirected to Support?

**Comment by andrewferlitsch** [comment]
non-notebook issue
