### ISSUE TITLE
Have trouble to use bigquery

### ISSUE THREAD

**Issue by yunruili** [GoogleCloudPlatform/vertex-ai-samples#174]
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/bigquery/v2/projects/vf64cb108e9b1b4cfp-tp/jobs?prettyPrint=false: Access Denied: Project vf64cb108e9b1b4cfp-tp: User does not have bigquery.jobs.create permission in project vf64cb108e9b1b4cfp-tp.

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by kweinmeister** [comment]
Hello, can you please let us know if this issue relates to one of the notebooks in this sample code repository?

**Comment by kweinmeister** [comment]
Hi, since we haven't heard back, we'll go ahead and close this issue. Please feel free to reopen if you have more information.
