### ISSUE TITLE
Model Garden notebook bug: Can't deploy Dreambooth fine-tuned model (Stable Diffusion)

### ISSUE THREAD

**Issue by jasonbrancazio** [GoogleCloudPlatform/vertex-ai-samples#1796]
When I run https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb, and change the model_id to a GCS path, like f"gs://{GCS_BUCKET}/dreambooth/output", I expect to be able to deploy the fine-tuned Dreambooth model, but I receive this error at the aiplatform.Model.upload step:

400 Model directory gs://my-project/dreambooth/output is expected to contain exactly one of: [model.mar].  (note that I replaced my actual project id in the error message with "my-project").

This is the full traceback:

```
---------------------------------------------------------------------------
FailedPrecondition                        Traceback (most recent call last)
/var/tmp/ipykernel_19019/474774148.py in <module>
      1 # Set the model_id to a GCS path, like "gs://GCS_BUCKET/dreambooth/output", to load the dreambooth finetuned model above.
      2 model, endpoint = deploy_model(
----> 3     model_id=f"gs://{GCS_BUCKET}/dreambooth/output", task="text-to-image"
      4 )

/var/tmp/ipykernel_19019/3153156216.py in deploy_model(model_id, task)
     57         serving_container_health_route="/ping",
     58         serving_container_environment_variables=serving_env,
---> 59         artifact_uri=artifact_uri,
     60     )
     61     model.deploy(

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/base.py in wrapper(*args, **kwargs)
    808                 if self:
    809                     VertexAiResourceNounWithFutureManager.wait(self)
--> 810                 return method(*args, **kwargs)
    811 
    812             # callbacks to call within the Future (in same Thread)

/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/models.py in upload(cls, serving_container_image_uri, artifact_uri, model_id, parent_model, is_default_version, version_aliases, version_description, serving_container_predict_route, serving_container_health_route, description, serving_container_command, serving_container_args, serving_container_environment_variables, serving_container_ports, local_model, instance_schema_uri, parameters_schema_uri, prediction_schema_uri, explanation_metadata, explanation_parameters, display_name, project, location, credentials, labels, encryption_spec_key_name, staging_bucket, sync, upload_request_timeout)
   3134         _LOGGER.log_create_with_lro(cls, lro)
   3135 
-> 3136         model_upload_response = lro.result()
   3137 
   3138         this_model = cls(

/opt/conda/lib/python3.7/site-packages/google/api_core/future/polling.py in result(self, timeout, retry, polling)
    259             # pylint: disable=raising-bad-type
    260             # Pylint doesn't recognize that this is valid in this case.
--> 261             raise self._exception
    262 
    263         return self._result

FailedPrecondition: 400 Model directory gs://my-project/dreambooth/output is expected to contain exactly one of: [model.mar].
```

I suspect, but can't verify, that the notebook is missing a step, which is to use the torch model archiver to archive the Stable Diffusion Pipeline. The "model.mar" file would be uploaded to the artifact_uri path. (Is this even possible, considering that the pipeline is composed of several pytorch models?)

I say this because I can see from the Endpoint logs that Torchserve is used inside the serving container `us-docker.pkg.dev/vertex-ai-restricted/vertex-vision-model-garden-dockers/pytorch-diffusers-serve`, and torch model archive files are typically used with Torchserve.

aiplatform.Model.upload checks artifact uris against a `_SUPPORTED_MODEL_FILE_NAMES` variable, but I think the code actually gets past this check, and instead fails when the Google Cloud REST API fails to find `model.mar` in the output path on Google Cloud Storage, which instead contains all the subcomponents of a Stable Diffusion pipeline.

I'd love to dig in further, but I can't, because the serving container `us-docker.pkg.dev/vertex-ai-restricted/vertex-vision-model-garden-dockers/pytorch-diffusers-serve` is in a restricted project, so I can't pull it and inspect its contents.

**Comment by jasonbrancazio** [comment]
Also, when I inspect the logs of a deployed Endpoint that fails to launch the fine-tuned model, I see a Hugging Face error, indicating to me that the code is actually expecting a hugging face repo_id

```
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'gs://my-project/dreambooth/output'. Use `repo_type` argument if needed.
````

**Comment by xiangxu-google** [comment]
The issue has been fixed. Please run the latest notebook https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb from beginning.

NOTE: one extra step is added to the `Setup Google Cloud project` section:
[Create a service account](https://cloud.google.com/iam/docs/service-accounts-create#iam-service-accounts-create-console) with Vertex AI User and Storage Object Admin roles for deploying fine tuned model to Vertex AI endpoint.

**Comment by jasonbrancazio** [comment]
Fantastic! I will try, @xiangxu-google .

The open source models in the model garden rely on training & serving Docker containers hosted in an Artifact Registry in a vertex-ai-restricted project. 

Will Google Cloud eventually publish the source code for those Dockerfiles publicly, or at least make the images downloadable? 

I'd love to see all the parameters that I can add in instances sent to a deployed Stable Diffusion model, but I can't. 

The instances in this notebook only contain "prompt", but a StableDiffusionPipeline huggingface class accepts [other parameters](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L532) such as height, width, num_inference_steps, guidance_scale, etc.

**Comment by xiangxu-google** [comment]
Hi @jasonbrancazio , thanks for your questions!
Currently we have no plan to open source the code of Dockerfiles yet. But it may change in the future.
We have plan to make the prediction configurable, so that users will be able to send StableDiffusionPipeline params in the endpoint request.

**Comment by jasonbrancazio** [comment]
Thanks for clarifying @xiangxu-google ! 

By the time you get to public preview, you might only need to document all the parameters instances can take for each model in the garden. Then users won't be confused about what they can and can't do with the deployed models. But seeing the Dockerfile & image source code would be a real plus, in the same way that we can see the source code of the Vertex AI SDK at https://github.com/googleapis/python-aiplatform

**Comment by andrewferlitsch** [comment]
closing per discussion with xiangxu
