### ISSUE TITLE
how can we do early stopping for sample notebook I provided in the below

### ISSUE THREAD

**Issue by yunruili** [GoogleCloudPlatform/vertex-ai-samples#180]
I saw there're argument called disable_early_stopping in autoML. Can we do the same thing in the below notebook?
https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/36455b8125802459f3a40752fbda0e4c9407c854/notebooks/official/migration/UJ11%20Vertex%20SDK%20Hyperparameter%20Tuning.ipynb

**Comment by andrewferlitsch** [comment]
disable_early_stopping is for AutoML only. The referenced notebook is HPT for a custom job. One can DIY implement early stop for training. Likewise when doing HPT you set max_trials. If HPT does not think it making progress, it will stop early.
