### ISSUE TITLE
ERROR:google.cloud.aiplatform.prediction.local_endpoint:Exception during starting serving: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory')).

### ISSUE THREAD

**Issue by tankbattle** [GoogleCloudPlatform/vertex-ai-samples#1870]
Was trying colab https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/vertex_endpoints/find_ideal_machine_type/find_ideal_machine_type.ipynb 

## Expected Behavior
The colab should run through well.

## Actual Behavior
 Came across error complaining 
"ERROR:google.cloud.aiplatform.prediction.local_endpoint:Exception during starting serving: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))."
when executing https://colab.research.google.com/github/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/vertex_endpoints/find_ideal_machine_type/find_ideal_machine_type.ipynb#scrollTo=c4f664318f9a&line=7&uniqifier=1

## Steps to Reproduce the Problem

1. Start the colab and execute all.
1. After "aiplatform" package is installed, restart the kernel, as suggested.
1. Remove "sudo" in https://colab.research.google.com/github/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/vertex_endpoints/find_ideal_machine_type/find_ideal_machine_type.ipynb#scrollTo=392ae29f9285&line=1&uniqifier=1, or it would complain "gsutil not found".
1. Continue execution, and the error shows up.

## Specifications

- Version: google_cloud_aiplatform-1.25.0-py2.py3-none-any
- Platform:

**Comment by gericdong** [comment]
Hello @tankbattle, do you need any help with this issue?

**Comment by andrewferlitsch** [comment]
aged out
