### ISSUE TITLE
Distributed Training - Checkpoint Files Not Created.  

### ISSUE THREAD

**Issue by jth1911** [GoogleCloudPlatform/vertex-ai-samples#1897]
## Expected Behavior
- Checkpoint files should be created: model/variables/variables_temp/part-00000-of-00001.data-00000-of-00001
- After merge, these should be deleted.

## Actual Behavior
- Checkpoint files are not created therefore deletion process fails.  

## Steps to Reproduce the Problem
 ```
MODEL_DIR = BUCKET_URI

CMDARGS = ["--epochs=5", "--batch_size=16", "--distribute=multiworker"]

try:
    model = job.run(
        model_display_name="jharding_boston_" + UUID,
        args=CMDARGS,
        replica_count=4,
        machine_type=TRAIN_COMPUTE,
        accelerator_type=TRAIN_GPU.name,
        accelerator_count=TRAIN_NGPU,
        base_output_dir=MODEL_DIR,
        sync=True,
    )
except Exception as e:
    # may fail duing model.save() -- seems to be some issue when merging checkpoints from the workers
    print(e)
```

1. Set distribute=multiworker
1. 

## Specifications
- Notebook: notebooks/official/training/distributed_hyperparameter_tuning.ipynb 
- Version: 'tensorflow==2.5.0', 'tensorflow_datasets==1.3.0
- Platform: VertexAI

## Error Message

Training failed with:
code: 3
message: "The replica workerpool1-0 exited with a non-zero status of 1. Termination reason: Error. \nTraceback (most recent call last):\n  [...]\n  File \"/opt/conda/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py\", line 1219, in save\n    file_prefix_tensor, object_graph_tensor, options)\n  File \"/opt/conda/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py\", line 1164, in _save_cached_when_graph_building\n    save_op = saver.save(file_prefix, options=options)\n  File \"/opt/conda/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py\", line 300, in save\n    return save_fn()\n  File \"/opt/conda/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py\", line 287, in save_fn\n    sharded_prefixes, file_prefix, delete_old_dirs=True)\n  File \"/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py\", line 504, in merge_v2_checkpoints\n    delete_old_dirs=delete_old_dirs, name=name, ctx=_ctx)\n  File \"/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py\", line 528, in merge_v2_checkpoints_eager_fallback\n    attrs=_attrs, ctx=ctx, name=name)\n  File \"/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/execute.py\", line 60, in quick_execute\n    inputs, attrs, num_outputs)\ntensorflow.python.framework.errors_impl.NotFoundError: Error executing an HTTP request: HTTP response code 404 with body \'{\n  \"error\": {\n    \"code\": 404,\n    \"message\": \"No such object: jharding-distributed/model/variables/variables_temp/part-00000-of-00001.data-00000-of-00001\",\n    \"errors\": [\n      {\n        \"message\": \"No such object: jharding-distributed/model/variables/variables_temp/part-00000-of-00001.data-00000-of-00001\",\n        \"domain\": \"global\",\n        \"reason\": \"notFound\"\n      }\n    ]\n  }\n}\n\'\n\t when deleting gs://jharding-distributed/model/variables/variables_temp/part-00000-of-00001.data-00000-of-00001 [Op:MergeV2Checkpoints]

**Comment by andrewferlitsch** [comment]
notebook passes CI/CD test
