### ISSUE TITLE
Distributed Training Failure

### ISSUE THREAD

**Issue by jth1911** [GoogleCloudPlatform/vertex-ai-samples#1898]
## Expected Behavior
- Container creation

## Actual Behavior
- failed to create containerd task

## Steps to Reproduce the Problem
 ```
PRIMARY_COMPUTE = "n2-highcpu-64"

MODEL_DIR = BUCKET_URI

CMDARGS = [
    "--model-dir=" + MODEL_DIR,
    "--epochs=5",
    "--batch_size=16",
    "--distribute=multiworker",
]

CONTAINER_SPEC = {"image_uri": TRAIN_IMAGE, "command": "trainer.task", "args": CMDARGS}

PRIMARY_WORKER_POOL = {
    "replica_count": 1,
    "machine_spec": {"machine_type": PRIMARY_COMPUTE, "accelerator_count": 0},
    "container_spec": CONTAINER_SPEC,
}

WORKER_POOL_SPECS = [PRIMARY_WORKER_POOL]

TRAIN_WORKER_POOL = {
    "replica_count": 4,
    "machine_spec": {
        "machine_type": TRAIN_COMPUTE,
        "accelerator_count": TRAIN_NGPU,
        "accelerator_type": TRAIN_GPU,
    },
    "container_spec": CONTAINER_SPEC,
}

WORKER_POOL_SPECS.append(TRAIN_WORKER_POOL)



```

1. Set distribute=multiworker
1. 

## Specifications
- Notebook: notebooks/official/training/distributed_hyperparameter_tuning.ipynb 
- Version: 'tensorflow==2.5.0', 'tensorflow_datasets==1.3.0
- Platform: VertexAI

## Error Message

Job failed with:
code: 3
message: "The replica workerpool0-0 exited with a non-zero status of 128. Termination reason: StartError. \n Termination log message: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \"t\": executable file not found in $PATH: unknown

**Comment by andrewferlitsch** [comment]
fixed
