### ISSUE TITLE
documentation: at least introduce what a  KFP is before using it in a sentence Create a KFP pipeline:

### ISSUE THREAD

**Issue by pleabargain** [GoogleCloudPlatform/vertex-ai-samples#1904]
By using jargon straight out of the box you alienate those who don't speak your version of geek

At least introduce what a  KFP is before using it in a sentence Create a KFP pipeline. You are talking about
Kubeflow Pipelines
Right?

**Comment by andrewferlitsch** [comment]
Is there a specific notebook you are referring to?

**Comment by pleabargain** [comment]
notebooks/official/pipelines/control_flow_kfp.ipynb
and there are other notebooks that make a similar statement

lost and found:https://t.me/dennisdaniels
