### ISSUE TITLE
custom_model_training_and_batch_prediction: Failed at tensorflow import

### ISSUE THREAD

**Issue by ivanmkc** [GoogleCloudPlatform/vertex-ai-samples#203]
# Command
`import tensorflow as tf`

# Error
---------------------------------------------------------------------------
ContextualVersionConflict                 Traceback (most recent call last)
/tmp/ipykernel_20/3384745563.py in <module>
----> 1 import tensorflow as tf
      2 from google_cloud_pipeline_components import aiplatform as gcc_aip
      3 from google_cloud_pipeline_components.experimental.custom_job import utils
      4 from kfp.v2 import compiler, dsl
      5 from kfp.v2.dsl import component

~/.local/lib/python3.9/site-packages/tensorflow/__init__.py in <module>
     39 import sys as _sys
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43 

~/.local/lib/python3.9/site-packages/tensorflow/python/__init__.py in <module>
     46 from tensorflow.python import data
     47 from tensorflow.python import distribute
---> 48 from tensorflow.python import keras
     49 from tensorflow.python.feature_column import feature_column_lib as feature_column
     50 from tensorflow.python.layers import layers

~/.local/lib/python3.9/site-packages/tensorflow/python/keras/__init__.py in <module>
     23 
     24 # See b/110718070#comment18 for more details about this import.
---> 25 from tensorflow.python.keras import models
     26 
     27 from tensorflow.python.keras.engine.input_layer import Input

~/.local/lib/python3.9/site-packages/tensorflow/python/keras/models.py in <module>
     18 from tensorflow.python.framework import ops
     19 from tensorflow.python.keras import backend
---> 20 from tensorflow.python.keras import metrics as metrics_module
     21 from tensorflow.python.keras import optimizer_v1
     22 from tensorflow.python.keras.engine import functional

~/.local/lib/python3.9/site-packages/tensorflow/python/keras/metrics.py in <module>
     35 from tensorflow.python.framework import tensor_shape
     36 from tensorflow.python.framework import tensor_spec
---> 37 from tensorflow.python.keras import activations
     38 from tensorflow.python.keras import backend
     39 from tensorflow.python.keras.engine import base_layer

~/.local/lib/python3.9/site-packages/tensorflow/python/keras/activations.py in <module>
     16 
     17 from tensorflow.python.keras import backend
---> 18 from tensorflow.python.keras.layers import advanced_activations
     19 from tensorflow.python.keras.utils.generic_utils import deserialize_keras_object
     20 from tensorflow.python.keras.utils.generic_utils import serialize_keras_object

~/.local/lib/python3.9/site-packages/tensorflow/python/keras/layers/__init__.py in <module>
     20 # pylint: disable=g-bad-import-order
     21 # pylint: disable=g-import-not-at-top
---> 22 from tensorflow.python.keras.engine.input_layer import Input
     23 from tensorflow.python.keras.engine.input_layer import InputLayer
     24 from tensorflow.python.keras.engine.input_spec import InputSpec

~/.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/input_layer.py in <module>
     22 from tensorflow.python.keras import backend
     23 from tensorflow.python.keras.distribute import distributed_training_utils
---> 24 from tensorflow.python.keras.engine import base_layer
     25 from tensorflow.python.keras.engine import keras_tensor
     26 from tensorflow.python.keras.engine import node as node_module

~/.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py in <module>
     47 from tensorflow.python.keras import initializers
     48 from tensorflow.python.keras import regularizers
---> 49 from tensorflow.python.keras.engine import base_layer_utils
     50 from tensorflow.python.keras.engine import input_spec
     51 from tensorflow.python.keras.engine import keras_tensor

~/.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_utils.py in <module>
     29 from tensorflow.python.keras.utils import control_flow_util
     30 from tensorflow.python.keras.utils import tf_inspect
---> 31 from tensorflow.python.keras.utils import tf_utils
     32 from tensorflow.python.ops import array_ops
     33 from tensorflow.python.ops import variables as tf_variables

~/.local/lib/python3.9/site-packages/tensorflow/python/keras/utils/tf_utils.py in <module>
     20 
     21 from tensorflow.python.data.experimental.ops import cardinality
---> 22 from tensorflow.python.distribute.coordinator import cluster_coordinator as coordinator_lib
     23 from tensorflow.python.eager import context
     24 from tensorflow.python.framework import composite_tensor

~/.local/lib/python3.9/site-packages/tensorflow/python/distribute/coordinator/cluster_coordinator.py in <module>
     34 
     35 from tensorflow.python.distribute import input_lib
---> 36 from tensorflow.python.distribute import parameter_server_strategy_v2
     37 from tensorflow.python.distribute.coordinator import metric_utils
     38 from tensorflow.python.eager import cancellation

~/.local/lib/python3.9/site-packages/tensorflow/python/distribute/parameter_server_strategy_v2.py in <module>
     31 from tensorflow.python.distribute import mirrored_run
     32 from tensorflow.python.distribute import multi_worker_util
---> 33 from tensorflow.python.distribute import parameter_server_strategy
     34 from tensorflow.python.distribute import sharded_variable
     35 from tensorflow.python.distribute import values

~/.local/lib/python3.9/site-packages/tensorflow/python/distribute/parameter_server_strategy.py in <module>
     32 from tensorflow.python.distribute import ps_values
     33 from tensorflow.python.distribute import values
---> 34 from tensorflow.python.distribute.cluster_resolver import SimpleClusterResolver
     35 from tensorflow.python.distribute.cluster_resolver import TFConfigClusterResolver
     36 from tensorflow.python.eager import context

~/.local/lib/python3.9/site-packages/tensorflow/python/distribute/cluster_resolver/__init__.py in <module>
     29 from tensorflow.python.distribute.cluster_resolver.cluster_resolver import SimpleClusterResolver
     30 from tensorflow.python.distribute.cluster_resolver.cluster_resolver import UnionClusterResolver
---> 31 from tensorflow.python.distribute.cluster_resolver.gce_cluster_resolver import GCEClusterResolver
     32 from tensorflow.python.distribute.cluster_resolver.kubernetes_cluster_resolver import KubernetesClusterResolver
     33 from tensorflow.python.distribute.cluster_resolver.slurm_cluster_resolver import SlurmClusterResolver

~/.local/lib/python3.9/site-packages/tensorflow/python/distribute/cluster_resolver/gce_cluster_resolver.py in <module>
     26 _GOOGLE_API_CLIENT_INSTALLED = True
     27 try:
---> 28   from googleapiclient import discovery  # pylint: disable=g-import-not-at-top
     29   from oauth2client.client import GoogleCredentials  # pylint: disable=g-import-not-at-top
     30 except ImportError:

~/.local/lib/python3.9/site-packages/googleapiclient/discovery.py in <module>
     66 from googleapiclient.errors import UnknownApiNameOrVersion
     67 from googleapiclient.errors import UnknownFileType
---> 68 from googleapiclient.http import build_http
     69 from googleapiclient.http import BatchHttpRequest
     70 from googleapiclient.http import HttpMock

~/.local/lib/python3.9/site-packages/googleapiclient/http.py in <module>
     65 from googleapiclient.errors import UnexpectedBodyError
     66 from googleapiclient.errors import UnexpectedMethodError
---> 67 from googleapiclient.model import JsonModel
     68 
     69 

~/.local/lib/python3.9/site-packages/googleapiclient/model.py in <module>
     34 from googleapiclient.errors import HttpError
     35 
---> 36 _LIBRARY_VERSION = pkg_resources.get_distribution("google-api-python-client").version
     37 _PY_VERSION = platform.python_version()
     38 

/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py in get_distribution(dist)
    464         dist = Requirement.parse(dist)
    465     if isinstance(dist, Requirement):
--> 466         dist = get_provider(dist)
    467     if not isinstance(dist, Distribution):
    468         raise TypeError("Expected string, Requirement, or Distribution", dist)

/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py in get_provider(moduleOrReq)
    340     """Return an IResourceProvider for the named module or requirement"""
    341     if isinstance(moduleOrReq, Requirement):
--> 342         return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
    343     try:
    344         module = sys.modules[moduleOrReq]

/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py in require(self, *requirements)
    884         included, even if they were already activated in this working set.
    885         """
--> 886         needed = self.resolve(parse_requirements(requirements))
    887 
    888         for dist in needed:

/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
    775                 # Oops, the "best" so far conflicts with a dependency
    776                 dependent_req = required_by[req]
--> 777                 raise VersionConflict(dist, req).with_context(dependent_req)
    778 
    779             # push the new requirements onto the stack

ContextualVersionConflict: (google-api-core 2.3.2 (/builder/home/.local/lib/python3.9/site-packages), Requirement.parse('google-api-core<2dev,>=1.21.0'), {'google-api-python-client'})

**Comment by ivanmkc** [comment]
[custom_model_training_and_batch_prediction.ipynb.zip](https://github.com/GoogleCloudPlatform/vertex-ai-samples/files/7831287/custom_model_training_and_batch_prediction.ipynb.zip)

**Comment by ivanmkc** [comment]
Has this been fixed?

**Comment by ivanmkc** [comment]
@andrewferlitsch

**Comment by andrewferlitsch** [comment]
fixed
