### ISSUE TITLE
can't access AIP_TENSORBOARD_LOG_DIR and AIP_MODEL_DIR

### ISSUE THREAD

**Issue by haiderasad** [GoogleCloudPlatform/vertex-ai-samples#2069]
While running custom training pipeline both AIP_TENSORBOARD_LOG_DIR and AIP_MODEL_DIR shows paths as  
![image](https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/55244143/e1413b65-54b7-429b-a11c-5b0da3b1919e)

gs://yolov7-artifacts/aiplatform-custom-training-2023-07-05-14:35:00.308/logs/
gs://yolov7-artifacts/aiplatform-custom-training-2023-07-05-14:35:00.308/model/
but when reading above AIP_TENSORBOARD_LOG_DIR it gives the error 
![image](https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/55244143/b2c8d443-88cf-4ec9-bb02-01ed290aa919)

`ValueError: No recognized filesystem for prefix gs`

seems it can read or write to the path when the path has "gs://"

it read/writes OK when specifying the path as "/gcs/<bucket_name>/filename"

For the AIP_MODEL_DIR it gives no error but  the trained model is not stored to the AIP_MODEL_DIR, but when giving a "/gcs/<bucket_name>/filename" path it stores the model ok 

Are your specified environment variables stored correctly?if so how can i access them to store the tensorboard logs and the trained model

**Comment by andrewferlitsch** [comment]
@haiderasad Hi, is there a specific notebook that is failing?

**Comment by andrewferlitsch** [comment]
aged out
