### ISSUE TITLE
google_cloud_pipeline_components Compiling Error in metadata Parameter in ModelDeployOp()

### ISSUE THREAD

**Issue by pactera-song** [GoogleCloudPlatform/vertex-ai-samples#208]
I try to write something to metadata of vertext ai model.
and my code is like this:

    import google.cloud.aiplatform as aip 
    from google_cloud_pipeline_components import aiplatform as gcc_aip

    @dsl.pipeline(
        name="test-vertext-ai-02",
        pipeline_root=PIPELINE_ROOT,
    )
    def pipeline():
        ds_op = gcc_aip.TextDatasetCreateOp(
            project=PROJECT_ID,
            display_name=dataset_display_name,
            gcs_source=gcs_source,
            import_schema_uri=aip.schema.dataset.ioformat.text.extraction,
        )
    
    training_job_run_op = gcc_aip.CustomContainerTrainingJobRunOp(
        project=PROJECT_ID,
        display_name='pipeline_test_0112_1030',
        dataset=ds_op.outputs["dataset"],
        annotation_schema_uri=aip.schema.dataset.annotation.text.extraction,
        model_display_name=model_display_name,
        base_output_dir=base_output_dir,
        container_uri='us-central1-docker.pkg.dev/fr-dev-piiworker/ml-training/test_01_image:latest',
        staging_bucket='gs://vertex_ai_test_dev',
        model_serving_container_image_uri=model_serving_container_image_uri,
    )
    
    gcc_aip.ModelDeployOp(
        model=training_job_run_op.outputs["model"],
        metadata=None
    )

then i compile this code:

    from kfp.v2 import compiler

    compiler.Compiler().compile(
        pipeline_func=pipeline, package_path="intro_pipeline.json".replace(" ", "_")
    )

but i get ths error message:

---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    /tmp/ipykernel_280/3730446987.py in <module>
      2 
      3 compiler.Compiler().compile(
    ----> 4     pipeline_func=pipeline, package_path="intro_pipeline.json".replace(" ", "_")
      5 )

    /opt/conda/lib/python3.7/site-packages/kfp/v2/compiler/compiler.py in compile(self, pipeline_func, package_path, 
    pipeline_name, pipeline_parameters, type_check)
       1275                 pipeline_func=pipeline_func,
       1276                 pipeline_name=pipeline_name,
    -> 1277                 pipeline_parameters_override=pipeline_parameters)
       1278             self._write_pipeline(pipeline_job, package_path)
       1279         finally:

    /opt/conda/lib/python3.7/site-packages/kfp/v2/compiler/compiler.py in _create_pipeline_v2(self, pipeline_func, 
    pipeline_name, pipeline_parameters_override)
       1194 
       1195         with dsl.Pipeline(pipeline_name) as dsl_pipeline:
    -> 1196             pipeline_func(*args_list)
       1197 
       1198         if not dsl_pipeline.ops:

    /tmp/ipykernel_280/786563907.py in pipeline()
     25     gcc_aip.ModelDeployOp(
     26         model=training_job_run_op.outputs["model"],
    ---> 27         metadata=None
     28     )

    TypeError: model_deploy() got an unexpected keyword argument 'metadata'

so how to fix this error?
Thanks!

**Comment by pactera-song** [comment]
and when i check this doc i find there is a parameter named 'metadata' in method 'ModelDeployOp':

https://google-cloud-pipeline-components.readthedocs.io/en/google-cloud-pipeline-components-0.1.4/google_cloud_pipeline_components.aiplatform.html

**Comment by kweinmeister** [comment]
Hi, is this code from one of the notebooks in this repo?

**Comment by andrewferlitsch** [comment]
You can add user-defined metadata to a Vertex Model using the parameter labels, which is in a dictionary format.

**Comment by andrewferlitsch** [comment]
answered user's usability question.
