### ISSUE TITLE
Issue with community/vertex_endpoints/torchserve/dreambooth_stablediffusion.ipynb

### ISSUE THREAD

**Issue by zetyquickly** [GoogleCloudPlatform/vertex-ai-samples#2082]
Hello,

This notebook is a tutorial how to deploy a custom stable diffusion network stored here (gs://cloud-samples-data/vertex-ai/model-deployment/models/stable-diffusion/model_artifacts.zip). But at the end of the day it creates the `handler.py` which uses `model_id = 'runwayml/stable-diffusion-v1-5'`.

How can one adjust the code of this notebook to actually deploy a customly trained dreambooth from gbucket?

**Comment by zetyquickly** [comment]
https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/vertex_endpoints/torchserve/dreambooth_stablediffusion.ipynb

**Comment by gericdong** [comment]
@zetyquickly : can you please check this notebook [pytorch_image_classification_with_prebuilt_serving_containers.ipynb](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/prediction/pytorch_image_classification_with_prebuilt_serving_containers.ipynb) and see if it'd help? 
Although this notebook is not stable diffusion specific, it demonstrates how to upload and deploy a PyTorch image model using a prebuilt serving container.

**Comment by andrewferlitsch** [comment]
closing issue as notebook is no longer supported.
