### ISSUE TITLE
SAM Model Deployment Timeout model_garden_pytorch_sam.ipynb

### ISSUE THREAD

**Issue by sleazebaggano** [GoogleCloudPlatform/vertex-ai-samples#2103]
## Expected Behavior
Deploy command should deploy the SAM model to the endpoint created.

## Actual Behavior
Model is uploaded to the registry, endpoint is created then model deployment times out even after setting the timeout to 10000.

## Steps to Reproduce the Problem
Follow the steps of the model_garden_pytorch_sam.ipynb file in the examples and wait for it to timeout.

## Specifications
I used both colab and jupytper vertex ai workbench notebook and it times out on both.

DeadlineExceeded                          Traceback (most recent call last)
<ipython-input-7-3129f44de0b4> in <cell line: 1>()
----> 1 endpoint, model = deploy_model(
      2     task="mask-generation", model_id="facebook/sam-vit-large"
      3 )

5 frames
/usr/local/lib/python3.10/dist-packages/google/api_core/future/polling.py in result(self, timeout, retry, polling)
    259             # pylint: disable=raising-bad-type
    260             # Pylint doesn't recognize that this is valid in this case.
--> 261             raise self._exception
    262 
    263         return self._result

DeadlineExceeded: 504 Timeout. Model server logs can be found at -- give the link to logging but there are no logs.

**Comment by andrewferlitsch** [comment]
Manually tried the notebook and got the same timeout
DeadlineExceeded: 504 Timeout. Model server logs can be found at https://console.cloud.google.com/logs/viewer?project=759209241365&resource=aiplatform.googleapis.com%252FEndpoint&advancedFilter=resource.type%3D%22aiplatform.googleapis.com%2FEndpoint%22%0Aresource.labels.endpoint_id%3D%228224131471485435904%22%0Aresource.labels.location%3D%22us-central1%22. If this error persists, contact ai-platform-unified-feedback@google.com 4: Timeout. Model server logs can be found at https://console.cloud.google.com/logs/viewer?project=759209241365&resource=aiplatform.googleapis.com%252FEndpoint&advancedFilter=resource.type%3D%22aiplatform.googleapis.com%2FEndpoint%22%0Aresource.labels.endpoint_id%3D%228224131471485435904%22%0Aresource.labels.location%3D%22us-central1%22. If this error persists, contact ai-platform-unified-feedback@google.com

**Comment by n-clinton** [comment]
Confirmed.  Doesn't deploy.  No logs.

**Comment by ivanmkc** [comment]
@sleazebaggano Community notebooks are provided for reference but are community-contributed and not maintained by Google.

I would advise to contact the author [huguensjean](https://github.com/huguensjean) or contact [ai-platform-unified-feedback@google.com](mailto:ai-platform-unified-feedback@google.com) like the error message suggests.
