### ISSUE TITLE
error: subprocess-exited-with-error | Deploying Iris-detection model using FastAPI and Vertex AI custom container serving

### ISSUE THREAD

**Issue by demichael4520** [GoogleCloudPlatform/vertex-ai-samples#2108]
## Expected Behavior

No errors when installing packages from the requirements file from the notebook https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/custom/SDK_Custom_Container_Prediction.ipynb

## Actual Behavior

 error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [794 lines of output]
      <string>:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Partial import of sklearn during the build process.
      <string>:116: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html

## Steps to Reproduce the Problem

1. Used the Vertex sample, https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/custom/SDK_Custom_Container_Prediction.ipynb
2. Create the  Requirements file:

%%writefile requirements.txt
joblib~=1.0
numpy~=1.20
scikit-learn~=0.24
google-cloud-storage>=1.26.0,<2.0.0dev

2. Run the install:

# Required in Docker serving container
! pip3 install -U  -r requirements.txt -q

# For local FastAPI development and running
! pip3 install -U  "uvicorn[standard]>=0.12.0,<0.14.0" fastapi~=0.63 -q

# Vertex SDK for Python
! pip3 install -U  google-cloud-aiplatform -q

3. Observe the error:

error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [794 lines of output]
      <string>:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Partial import of sklearn during the build process.
      <string>:116: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html

<SNIP>

  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

## Specifications

- Version: N/A
- Platform: N/A

**Comment by ivanmkc** [comment]
@andrewferlitsch can you triage to the owner?

**Comment by andrewferlitsch** [comment]
attempting fix:
https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/2124

**Comment by ivanmkc** [comment]
Looks like Vinny was the original author: https://github.com/GoogleCloudPlatform/ai-platform-samples/pull/300

**Comment by ivanmkc** [comment]
@demichael4520 see the attached notebook which ran successfully on our CI.

**Comment by ivanmkc** [comment]
[SDK_Custom_Container_Prediction.ipynb.zip](https://github.com/GoogleCloudPlatform/vertex-ai-samples/files/12176880/SDK_Custom_Container_Prediction.ipynb.zip)

This might help you debug.

**Comment by andrewferlitsch** [comment]
@demichael4520 The notebook has been updated since the issue was posted and passes CI/CD test.
