### ISSUE TITLE
Two-Tower Container not exporting model files to Cloud Bucket

### ISSUE THREAD

**Issue by M1keZulu** [GoogleCloudPlatform/vertex-ai-samples#2118]
## Expected Behavior
notebooks/community/ml_ops/stage6/get_started_with_matching_engine_twotowers.ipynb
The container should produce two TFModels and export to cloud bucket.

## Actual Behavior
The model is running successfully but exporting no model files to output directory.

## Steps to Reproduce the Problem

1. I am currently following the exact same steps with the same arguments as mentioned in this notebook using Kubeflow and Vertex AI pipelines, have tried several approaches and tried to do some debugging as well. Log files show that the model is training OK, Epochs are logged and the Custom Job successfully runs but there is nothing in the Output-Dir

![image](https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/68997634/0ad8e695-199b-4847-a13b-4ba806c2ffaf)
![image](https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/68997634/dedc7a1d-6252-4ddd-86e3-8785575f8029)
![image](https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/68997634/aade2bf8-c352-48b3-830f-d255ef4e251e)
![image](https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/68997634/4e3fa067-d955-4c32-92b4-99862957ce65)

**Comment by andrewferlitsch** [comment]
@M1keZulu Thanks for letting us know. Vertex AI Two-Towers is a deprecated product. I will remove the notebook from the repo.
