### ISSUE TITLE
Wrong GitHub logo at `notebooks/official/datasets/get_started_bq_datasets.ipynb`

### ISSUE THREAD

**Issue by oogl** [GoogleCloudPlatform/vertex-ai-samples#2121]
## Expected Behavior

![image](https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/36997715/11049ed5-5702-4604-81a8-1f5c883bcf35)

https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/c2ca773c27380c25ae15e6aedb7e1b639535301e/notebooks/notebook_template.ipynb#L31-L55

## Actual Behavior

![image](https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/36997715/20878686-c8c5-4950-be5b-41cd8bf72276)

https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/c2ca773c27380c25ae15e6aedb7e1b639535301e/notebooks/official/datasets/get_started_bq_datasets.ipynb#L31-L52

## Steps to Reproduce the Problem

1. Go to the latest version of the [tutorial on GitHub](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/datasets/get_started_bq_datasets.ipynb) (or open in Vertex AI)

## Specifications

- Version: any
- Platform: any

**Comment by andrewferlitsch** [comment]
https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/2145

**Comment by andrewferlitsch** [comment]
verified
