### ISSUE TITLE
No module named 'google_cloud_pipeline_components.experimental'

### ISSUE THREAD

**Issue by Jen-Cook** [GoogleCloudPlatform/vertex-ai-samples#2125]
I am running the tabnet_on_vertex_pipelines.ipynb on GCP Vertex. In this workbook, under Import libraries and define constants-block 14, I am attempting to import the libraries. When running line 9, 
from google_cloud_pipeline_components.experimental.automl.tabular import \
     utils as automl_tabular_utils

I receive the following error:
ModuleNotFoundError: No module named 'google_cloud_pipeline_components.experimental'

I did have success when using the following command:
from google_cloud_pipeline_components. import \
     utils as automl_tabular_utils
However, this caused issues later in the workbook under Customize TabNet HyperparameterTuningJob configuration and create pipeline, block 13. The error is below. 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[13], line 26
     19 study_spec_metric_goal = "MINIMIZE"
     21 # max_steps and/or max_train_secs must be set. If both are
     22 # specified, training stop after either condition is met.
     23 # By default, max_train_secs is set to -1 and max_steps is set to
     24 # an appropriate range given dataset_size and training budget.
     25 study_spec_parameters_override = (
---> 26     automl_tabular_utils.get_tabnet_study_spec_parameters_override(
     27         dataset_size_bucket="small",
     28         prediction_type=prediction_type,
     29         training_budget_bucket="small",
     30     )
     31 )
     33 # If your system does not use Python, you can save the JSON file (`template_path`),
     34 # and use another programming language to submit the pipeline.
     35 (
     36     template_path,
     37     parameter_values,
   (...)
     62     run_evaluation=True,
     63 )

AttributeError: module 'google_cloud_pipeline_components.utils' has no attribute 'get_tabnet_study_spec_parameters_override'

- Platform: GCP Vertex, TensorFlow2.1

**Comment by andrewferlitsch** [comment]
Fixed in https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/2144

**Comment by andrewferlitsch** [comment]
@Jen-Cook If you are using GCPC >=2.0, the namespace has changed from experimental to preview.

**Comment by Jen-Cook** [comment]
Thank you, I appreciate it!
