### ISSUE TITLE
Unable to run custom job in sdk-custom-image-classification-batch.ipynb

### ISSUE THREAD

**Issue by ravishmal** [GoogleCloudPlatform/vertex-ai-samples#213]
In `vertex-ai-samples/notebooks/official/custom/sdk-custom-image-classification-batch.ipynb`, when I run the following cell on a Vertex AI workbench notebook

```
job = aiplatform.CustomTrainingJob(
    display_name=JOB_NAME,
    script_path="task.py",
    container_uri=TRAIN_IMAGE,
    requirements=["tensorflow_datasets==1.3.0"],
    model_serving_container_image_uri=DEPLOY_IMAGE,
)

MODEL_DISPLAY_NAME = "cifar10-" + TIMESTAMP

if TRAIN_GPU:
    model = job.run(
        model_display_name=MODEL_DISPLAY_NAME,
        args=CMDARGS,
        replica_count=1,
        machine_type=TRAIN_COMPUTE,
        accelerator_type=TRAIN_GPU.name,
        accelerator_count=TRAIN_NGPU,
    )
else:
    model = job.run(
        model_display_name=MODEL_DISPLAY_NAME,
        args=CMDARGS,
        replica_count=1,
        machine_type=TRAIN_COMPUTE,
        accelerator_count=0,
    )
```
it gives error 
```InvalidArgument: 400 Accelerator "NVIDIA_TESLA_K80" is not supported for machine type "n1-standard-4"```. 

My understanding is Tesla K80 is compatible with 4vcpu, as listed here. https://cloud.google.com/ai-platform/training/docs/using-gpus

**Comment by andrewferlitsch** [comment]
I ran this notebook to completion w/o errors. Perhaps yours was somehow transitory. Could you try again?

Here's my output from job.run():

INFO:google.cloud.aiplatform.utils.source_utils:Training script copied to:
gs://andy-1234-221921aip-20220118164055/aiplatform-2022-01-18-16:42:18.067-aiplatform_custom_trainer_script-0.1.tar.gz.
INFO:google.cloud.aiplatform.training_jobs:Training Output directory:
gs://andy-1234-221921aip-20220118164055/aiplatform-custom-training-2022-01-18-16:42:18.250 
INFO:google.cloud.aiplatform.training_jobs:View Training:
https://console.cloud.google.com/ai/platform/locations/us-central1/training/814620468437843968?project=759209241365
INFO:google.cloud.aiplatform.training_jobs:View backing custom job:
https://console.cloud.google.com/ai/platform/locations/us-central1/training/498893505498710016?project=759209241365
INFO:google.cloud.aiplatform.training_jobs:CustomTrainingJob projects/759209241365/locations/us-central1/trainingPipelines/814620468437843968 current state:
PipelineState.PIPELINE_STATE_RUNNING
INFO:google.cloud.aiplatform.training_jobs:CustomTrainingJob projects/759209241365/locations/us-central1/trainingPipelines/814620468437843968 current state:
PipelineState.PIPELINE_STATE_RUNNING
INFO:google.cloud.aiplatform.training_jobs:CustomTrainingJob projects/759209241365/locations/us-central1/trainingPipelines/814620468437843968 current state:
PipelineState.PIPELINE_STATE_RUNNING
INFO:google.cloud.aiplatform.training_jobs:CustomTrainingJob projects/759209241365/locations/us-central1/trainingPipelines/814620468437843968 current state:
PipelineState.PIPELINE_STATE_RUNNING
INFO:google.cloud.aiplatform.training_jobs:CustomTrainingJob projects/759209241365/locations/us-central1/trainingPipelines/814620468437843968 current state:
PipelineState.PIPELINE_STATE_RUNNING
INFO:google.cloud.aiplatform.training_jobs:CustomTrainingJob projects/759209241365/locations/us-central1/trainingPipelines/814620468437843968 current state:
PipelineState.PIPELINE_STATE_RUNNING
INFO:google.cloud.aiplatform.training_jobs:CustomTrainingJob projects/759209241365/locations/us-central1/trainingPipelines/814620468437843968 current state:
PipelineState.PIPELINE_STATE_RUNNING
INFO:google.cloud.aiplatform.training_jobs:CustomTrainingJob run completed. Resource name: projects/759209241365/locations/us-central1/trainingPipelines/814620468437843968
INFO:google.cloud.aiplatform.training_jobs:Model available at projects/759209241365/locations/us-central1/models/4979613395406815232

**Comment by ivanmkc** [comment]
Feel free to close if stale.

**Comment by ravishmal** [comment]
Yes, this works now. Thanks!
