### ISSUE TITLE
I pip installed vertexai via https://pypi.org/project/vertexai/ - is this for real, or is it malicious?

### ISSUE THREAD

**Issue by brokejoker** [GoogleCloudPlatform/vertex-ai-samples#2185]
## Expected Behavior
pip install vertexai --> real one is pip install google-cloud-aiplatform

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by andrewferlitsch** [comment]
vertexai is just a placeholder and is not the release. When you go to the project page, you will see:

vertexai
To use the Vertex AI SDK, please install the google-cloud-aiplatform PyPi package by running pip install google-cloud-aiplatform.
