### ISSUE TITLE
Tutorial links to Pantheon Internal Google Links

### ISSUE THREAD

**Issue by sommes54** [GoogleCloudPlatform/vertex-ai-samples#2228]
## Expected Behavior
Public Google Storage Bucket

## Actual Behavior
Link to Pantheon - Internal Google Cloud Storage Bucket

## Steps to Reproduce the Problem

1. Click to download the sample dataset in the tutorial here - https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/gen_ai/rlhf_tune_llm.ipynb
2. You are redirected to an internal Google Cloud Bucket (Pantheon)

![pantheon](https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/48247569/f596e8cb-ccea-4863-a37f-9a636c90aa93)

## Specifications

- Version: [ee651d1](https://github.com/GoogleCloudPlatform/vertex-ai-samples/commit/ee651d1f226e4807fa3a1018dc5c5c18c6464e53)
- Platform: Colab

**Comment by andrewferlitsch** [comment]
all internal links are replaced
