### ISSUE TITLE
intro-swivel downloads external code

### ISSUE THREAD

**Issue by ivanmkc** [GoogleCloudPlatform/vertex-ai-samples#225]
It looks like the https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/matching_engine/intro-swivel.ipynb notebook downloads code from a Cloud Bucket

gsutil cp gs://cloud-samples-data/vertex-ai/matching-engine/swivel/pipeline/* .`

It isn't really standard practice to download external code to run. This means that code might not be tested/reviewed and could change at any time.
Notebooks in this repo must be self-contained notebooks, with all code inside the notebook..

Preferred solution: Rewrite the .sh files as code inside the notebook.
Alternative solution: Move your notebook to "community-content"

**Comment by andrewferlitsch** [comment]
notebook no longer exists
