### ISSUE TITLE
rlhf_tune_llm.ipynb - Example dataset isn't public

### ISSUE THREAD

**Issue by fgonzalezprada-replytech-ai** [GoogleCloudPlatform/vertex-ai-samples#2360]
Hi, 
We are trying to access the example dataset in the following notebook:

https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/e4275197acc33f4ea0e19686bb60416431dab9ed/notebooks/official/generative_ai/rlhf_tune_llm.ipynb

It seems that it isn't, public. It prompts for a Google employee login:

![image](https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/135854887/79d6b672-4591-4096-a9bd-3c980b5b2c18)

This is the link:

https://pantheon.corp.google.com/storage/browser/vertex-ai/generative-ai/rlhf/text_small/summarize_from_feedback_tfds/comparisons/train?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&e=13802955&jsmode=O&mods=-ai_platform_fake_service&project=vertex-ai&prefix=&forceOnObjectsSortingFiltering=false

Regards,
Fernando Gonzalez Prada

**Comment by andrewferlitsch** [comment]
already fixed
