### ISSUE TITLE
Question on Google Cloud Next Demo "What's new with Palm 2" : filtered_context method

### ISSUE THREAD

**Issue by quentin-lior** [GoogleCloudPlatform/vertex-ai-samples#2373]
Does anyone know which library (and product/service) the 'filtered_context' function comes from, as seen in the latest Google Next event at https://youtu.be/WF4xjKgU8r0?feature=shared&t=1241?
I am really interested in implementing it for an enterprise usage.
Thanks !

**Comment by andrewferlitsch** [comment]
@quentin-lior These issues are for the official Vertex AI notebooks. You seem to have a more general question. I would suggest posting your question on the community forum:

https://cloud.google.com/communities
