### ISSUE TITLE
rlhf_tune_llm.ipynb - There is no linked url for "Bulk Inference" tutorial 

### ISSUE THREAD

**Issue by lucidhwee** [GoogleCloudPlatform/vertex-ai-samples#2380]
## Expected Behavior
On the notebook of [rlhf_tune_llm.ipynb](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/generative_ai/rlhf_tune_llm.ipynb), Click "**Bulk Inference**" and it will redirect to the related tutorial.

## Actual Behavior
There is no linked url for "**Bulk Inference**" tutorial

## Steps to Reproduce the Problem

1. Read "Bulk Inference" part on the notebook of [rlhf_tune_llm.ipynb](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/generative_ai/rlhf_tune_llm.ipynb)

2. There is no lined url for "**Bulk Inference**" tutorial

## Specifications
- Screenshot
![issue - rlhf_tune_llm sample notebook](https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/29086352/f3a95351-1461-4fa5-905d-d2763790757c)

**Comment by andrewferlitsch** [comment]
fix in progress

**Comment by andrewferlitsch** [comment]
already fixed
