### ISSUE TITLE
rlhf_tune_llm.ipynb - Detailed guidance for testers who need online prediction with RLHF tuned T5 models.

### ISSUE THREAD

**Issue by lucidhwee** [GoogleCloudPlatform/vertex-ai-samples#2381]
## Expected Behavior
On the [rlhf_tune_llm.ipynb](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/generative_ai/rlhf_tune_llm.ipynb), testers using RLHF tuned T5 models can get a detailed guidance or references for online prediction with the models. (eg. Detailed guidance to download the tuned model from GCS and deploy it into Vertex Endpoint manually)

## Actual Behavior
Testers only can see the guidance for online prediction with `text-bison@001` and cannot find a solution for online prediction with RLHF tuned T5 models.

## Steps to Reproduce the Problem
1. Read "**Online Prediction (only applicable if you are tuning `text-bison@001`)**" part on the notebook of [rlhf_tune_llm.ipynb](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/generative_ai/rlhf_tune_llm.ipynb)

2. There is no detailed explanation or reference how to serve online prediction with RLHF tuned T5 models.

**Comment by andrewferlitsch** [comment]
asked PM to triage

**Comment by andrewferlitsch** [comment]
gentle ping PM a reminder

**Comment by andrewferlitsch** [comment]
closing issue as request is not supported
