### ISSUE TITLE
How to set max_out_tokens for the Llama2 model in the Model Garden

### ISSUE THREAD

**Issue by kylehh** [GoogleCloudPlatform/vertex-ai-samples#2427]
## Expected Behavior
Testing out Llama2-7b-chat from the model garden. 
following the [notebooks](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb)
The way it sets max_tokens is not working while I query directly using CURL
Not sure how to set the proper max output tokens

In the notebook, it shows follow instruct, but  doesn't work when I directly use CURL
instances = [
    {"prompt": "Write a poem about Valencia.", "max_length": 200, "top_k": 10},
]
I tried following 

body = {
  "instances": [
    { "prompt": "can you tell me a joke",
      "max_tokens": 1000,
      "top_k":10   
    }
  ],
  "parameters":{
      "temperature":0,
      "max_length":1000,
      "maxOutputTokens": 1000,
  }
}

But still, the Llama2 model output seems cut short
```
print(resp.json()['predictions'][0])
Prompt:
can you tell me a joke
Output:
?

i will give you one in return
```

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by batrasrishti** [comment]
Same issue

**Comment by andrewferlitsch** [comment]
reached out to a SWE to triage the issue

**Comment by xiangxu-google** [comment]
![image](https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/117880274/e7924abc-8c7d-4b2a-ba5b-c2e3b7ac3854)
Try to increase the --max_num_batched_tokens of vLLM engine and redeploy it, it's the upper bound of number of tokens can be processed in an iteration.

**Comment by andrewferlitsch** [comment]
fixed by PR 2536
