### ISSUE TITLE
bugfix in notebook used to delete outdated TensorBoard experiments

### ISSUE THREAD

**Issue by jasonbrancazio** [GoogleCloudPlatform/vertex-ai-samples#2463]
The `detailed_log` variable in the three helper functions in this notebook needs to be changed to uppercase in order to read its value from the global variable set earlier in the notebook.

https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/tensorboard/tensorboard_custom_training_with_custom_container.ipynb

**Comment by lakeyk** [comment]
This issue has been fixed. Thank you @jasonbrancazio for raising it.

**Comment by lakeyk** [comment]
Relevant pull request: https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/2469

**Comment by jasonbrancazio** [comment]
Cool! I see I included the wrong link in the issue I raised. It should have been [this one](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/experiments/delete_outdated_tensorboard_experiments.ipynb). Glad you found the right one!

**Comment by andrewferlitsch** [comment]
appears issue is fixed, closing the issue.
