### ISSUE TITLE
Unable to stream output of the LLM deployed on GCP

### ISSUE THREAD

**Issue by GargPriyanshu1112** [GoogleCloudPlatform/vertex-ai-samples#2491]
For streaming, I modified the code given in the following [file](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb). 

Here is the modified code:

```
    def get_streaming_response(self): 
        # Instance
        instance = {
            "prompt": llm_input,
            "max_length": 1028,
            "temperature": 0.6,
            "top_p": 1.0,
            "top_k": 10,
            "stream": True
        }
        
        # Endpoint
        endpoint = self.client.endpoint_path(
            project=PROJECT, location=LOCATION, endpoint=ENDPOINT_ID
        )
        endpoint = aiplatform.Endpoint(endpoint)
        
        #import datetime
        #print(datetime.datetime.now())
        for chunk in endpoint.raw_predict(
            body=json.dumps({"instances": [instance]}),
            headers={"Content-Type": "application/json"}
        ).iter_lines(
            chunk_size=100, # buffer size used to read the stream
            decode_unicode=False,
            delimiter=b"\0"
        ):
            if chunk:
                #print(datetime.datetime.now())
                data = json.loads(chunk.decode("utf-8"))
                output = data["predictions"][0]
                yield output


def get_llm_output(self, llm_input):
        print("Streaming:")
        text_len = 0
        for output in self.get_streaming_response():
            print(f"chunk: {output}")
```

What I found was that the code wasn't streaming. It first gets the entire output and then prints it.  The issue I think is with the following part of the code.

```
response = endpoint_with_peft.raw_predict(
    body=json.dumps({"instances": [instance]}),
    headers={"Content-Type": "application/json"},
)
```

**Comment by andrewferlitsch** [comment]
reached out to notebook author to take a look at the issue.

**Comment by MustafaAlahmid** [comment]
I am getting a similar issue 

> GoogleError: ServerStreamingPredict is not supported for deployed model: 


how can i enable the streaming ? im following  [model_garden_pytorch_llama2_peft](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb) vllm deployment

**Comment by MustafaAlahmid** [comment]
> @MustafaAlahmid
> 
> Did you check your model's predictions after vllm deployment? Was the quality the same? In my case, it decreased. Moreover, the model started giving short responses, hence a little bit of a decrease in response time (as there were fewer output tokens to process).

yes it looks like the quality is poor with vllm

**Comment by andrewferlitsch** [comment]
gentle ping of author for status

**Comment by Andy616** [comment]
when will the streaming be fixed, any updates?

**Comment by gr4y41** [comment]
Has there been any updates on this?
