### ISSUE TITLE
Not able to find logs related to Matching Engine

### ISSUE THREAD

**Issue by naveen675** [GoogleCloudPlatform/vertex-ai-samples#2523]
Problem. 

Hi We are not able to fetch any logs related to matching engine (vector search) in logging or any monitoring console in gcp. 
could anyone help me on this. We are facing issues in debugging the operations(Create, delete id in index, updating index) on the Matching engine . 

## Specifications

- Version: 1.31.0
- Platform: google-cloud-aiplatform

**Comment by andrewferlitsch** [comment]
reached out to PM to have someone debug

**Comment by naveen675** [comment]
@andrewferlitsch  May I know the issue that you have faced with matching engine 
and how many days it took for you to resolve.

**Comment by gericdong** [comment]
@naveen675 I am following to see if this is still an issue. Thanks.
