### ISSUE TITLE
Explainable AI notebooks failing after SDK 1.36.2 release

### ISSUE THREAD

**Issue by andrewferlitsch** [GoogleCloudPlatform/vertex-ai-samples#2528]
## Expected Behavior
XAI official notebooks were passing CI/CD tests.
sdk_custom_image_classification_batch_explain.ipynb
sdk_custom_tabular_regression_online_explain.ipynb
xai_image_classification_feature_attributions.ipynb 
sdk_custom_image_classification_online_explain.ipynb

## Actual Behavior
After release of Vertex AI SDK 1.36.2, the aforementioned notebooks are failing.
We pinned the SDK all the way to 1.33, to no avail. This maybe an issue with the backend service

## Steps to Reproduce the Problem

[1.](https://console.cloud.google.com/cloud-build/builds;region=us-central1/8df30974-00af-4168-9503-1a5bb1147c6a?project=1012616486416)
1.
1.

## Specifications

- Version:
- Platform:

**Comment by katiemn** [comment]
Tested the mentioned notebooks, but was not able to reproduce any failures at this time

**Comment by katiemn** [comment]
Tested the mentioned notebooks, but was not able to reproduce any failures at this time
