### ISSUE TITLE
Update a vector search index does not work

### ISSUE THREAD

**Issue by BastinFlorian** [GoogleCloudPlatform/vertex-ai-samples#2538]
## Expected Behavior
I want to update the vector search when files are deleted in my documentation

## Actual Behavior
The vector search is not updated by as written in the documentation: 
- I check the 'id' of the chunks
- I add them in the `delete_file.txt` in the `delete/` directory:
delete_file.txt : 
`
id1 \n id2 \n id3
`

## Steps to Reproduce the Problem

1. Create a vertex index and deploy it 
2. Add a id to the delete_file.txt
3. Update the index
Check if the number of vectors have check in the Google Vector Search interface

## Specifications

- Version: Last
- Platform: M1

**Comment by andrewferlitsch** [comment]
@BastinFlorian Is this an issue with an official notebook or the online documentation?

**Comment by BastinFlorian** [comment]
It is an issue on the official documentation, I close the issue. Thank you
