### ISSUE TITLE
Thousands of lines of code - But nothing works

### ISSUE THREAD

**Issue by sidoncloud** [GoogleCloudPlatform/vertex-ai-samples#2540]
Do you guys even test your code before committing? Or is it some guy running a jupyter nbk in his local system that randomly does code commits? This notebook is completely useless...theres a lot of fixes needed ...i tried fixing it but realized its a waste of time..!!

**Comment by andrewferlitsch** [comment]
@sidoncloud Is there a specific notebook you are referring to?

**Comment by kezirim** [comment]
Like this [one](https://colab.research.google.com/github/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/pipelines/pipelines_intro_kfp.ipynb?authuser=1#scrollTo=sjxaBix_2Ou7) does not work.

**Comment by gericdong** [comment]
Not enough information to proceed. Closed.
