### ISSUE TITLE
sdk-feature-store INTERNAL error

### ISSUE THREAD

**Issue by andrewferlitsch** [GoogleCloudPlatform/vertex-ai-samples#2547]
## Expected Behavior
This notebook has been passing CI/CD for a long time.

## Actual Behavior
Failing with internal error
https://console.cloud.google.com/cloud-build/builds;region=us-central1/cccd2ae6-ab12-4db1-af57-a6c1384456f2?project=1012616486416

Has failed on 11/19 and 11/20 runs

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by gericdong** [comment]
Random issue. Closed for now.
