### ISSUE TITLE
vertex search for RAG with custom documents

### ISSUE THREAD

**Issue by mhyeonsoo** [GoogleCloudPlatform/vertex-ai-samples#2548]
I would like to setup a pipeline with GCP modules to make RAG with vertex search for custom documents in formats of xlsx, pdf, xlsx, etc.
I saw there are some notebooks related to BigQuery + vertex search, but could not find one for document retrieval.
Is there any reference that I can see for this?

Thanks,

**Comment by mamdouhweb** [comment]
See following samples:
https://github.com/guruvittal/codesamples/blob/main/Retrieval_Augmented_Generation_Using_Vertex_Matching_Engine_-_Contract_Analyst.ipynb

https://github.com/guruvittal/generative-ai/blob/main/language/orchestration/langchain/intro_langchain_palm_api.ipynb
