### ISSUE TITLE
Enhance PyTorch Peft Container Image: Include Additional Parameters for Text Generation

### ISSUE THREAD

**Issue by shikanime** [GoogleCloudPlatform/vertex-ai-samples#2573]
### Expected Behavior

The expected behavior is that the Vertex AI PyTorch Peft container image (as referenced [here](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/2568e012f923b956d5a5c1d52934dd4f7c9f5aad/community-content/vertex_vision_model_garden/model_oss/peft/handler.py#L191)) should support additional parameters for text generation beyond the current `top_k` and `max_length`. Specifically, the following parameters should be functional:

- **`top_p`:** Allow setting the nucleus sampling probability for text generation.
- **`temperature`:** Enable adjusting the temperature for controlling the randomness of generated text.
- **`max_new_tokens`:** Allow users to set the maximum number of tokens generated, independent of the prompt length.

### Actual Behavior

The current limitation, where these parameters cannot be set, is problematic for certain use cases. The primary issue is that the `max_length` parameter, which considers the prompt length (as explained [here](https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationConfig.max_length)) additionally to the output tokens, restricts the flexibility of text generation.

For a more versatile and user-friendly experience, it is expected that the Vertex AI PyTorch Peft container image should support and appropriately handle these essential text generation parameters.

More detailed information about GenerationConfig and these parameters can be found in the [Hugging Face Transformers documentation](https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationConfig).

### Steps to Reproduce the Problem

1. Navigate to the [**Deploy LLaM2**](https://console.cloud.google.com/vertex-ai/publishers/google/model-garden/139?project=oranollm) page on the Google Cloud Console to initiate the import of the model into the registry.
2. Proceed to deploy the imported model onto an endpoint within your designated environment.
3. Execute queries on the deployed model using the specified parameters to observe and reproduce the encountered issue.
4. Specifically, monitor for truncation problems when using the max_length parameter with large prompt context, resulting in low generated diversity entropy.

I am willing to incorporate these functionalities if possible, and I'm open to any information or considerations I should be aware of.

**Comment by gericdong** [comment]
@shikanime: thanks for sharing this with us. We will take a look.
