### ISSUE TITLE
Error when invoking the model deployment for  `mistralai/Mistral-7B-Instruct-v0.1` on Vertex AI online prediction.

### ISSUE THREAD

**Issue by dxaen** [GoogleCloudPlatform/vertex-ai-samples#2575]
## Expected Behavior
The mistral LLM's vertex AI endpoint as described [here](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb), should support the chat model `mistralai/Mistral-7B-Instruct-v0.1`.

## Actual Behavior
The deployed model only takes `prompt` as input which corresponds to the `mistralai/Mistral-7B-v0.1`. As seen[ here](Mistral-7B-v0.1), the 
`mistralai/Mistral-7B-Instruct-v0.1` expects `messages` as an input param in the request. However, on inspecting the code inside the docker, the file: `/workspace/vllm/vllm/entrypoints/api_server.py` line 42, explicitly only processes `prompt`.
## Steps to Reproduce the Problem

1. Deploy the model as described [here](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb)
2. Change `mistralai/Mistral-7b-v0.1` to `mistralai/Mistral-7B-Instruct-v0.1` everywhere.
> Side note: Inside the vllm_args, add argument `--max-model-len=4096` to match `--max-num-batched-tokens`.
3. Create a request, where the prompt looks like:
```
messages = [
{"role": "user", "content": "What is the bash command to list all files in a folder and sort them by last modification?"}
]
```
4. Send the request over -- results in an error.

## Specifications

- Version: default as specified in docker
- Platform: Vertex AI Online prediction.

**Comment by dxaen** [comment]
[Update] It looks like the container runs this file:
https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/api_server.py
However, this can only be used for text generation and not for chat.

The container should run this script for chat with a provided [chat template](https://github.com/vllm-project/vllm/blob/main/examples/template_chatml.jinja).
https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/openai/api_server.py

**Comment by NielsRogge** [comment]
@dxaen it looks like you can change this by changing the `serving_container_command` in [this notebook](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_openllama_peft.ipynb).

In the notebook, they specify ["python", "-m", "vllm.entrypoints.api_server"] but you can change this to ["python", "-m", "vllm.entrypoints.openai.api_server"].

```diff
model = aiplatform.Model.upload(
        display_name=model_name,
        serving_container_image_uri=vllm_docker_uri,
-      serving_container_command=["python", "-m", "vllm.entrypoints.api_server"],
+      serving_container_command=["python", "-m", "vllm.entrypoints.openai.api_server"],
        serving_container_args=vllm_args,
        serving_container_ports=[7080],
        serving_container_predict_route="/generate",
        serving_container_health_route="/ping",
    )
```

**Comment by dxaen** [comment]
HI @NielsRogge 
Thanks for your reply. I did try this at the time, however, after making this and building the container. The model deployment fails, the logs seems to suggest that the service is unable to ping the health route of the container.

**Comment by dxaen** [comment]
Hi @kathyyu-google. Thanks a lot for fixing this issue.
