### ISSUE TITLE
"Hyperparameter Tuning" should be lowercase "hyperparameter tuning"

### ISSUE THREAD

**Issue by aarondietz234** [GoogleCloudPlatform/vertex-ai-samples#2585]
In the following notebook:

https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/pipelines/get_started_with_hpt_pipeline_components.ipynb

Within text cells, change instances of: Hyperparameter Tuning

...to lowercase: hyperparameter tuning.

**Comment by katiemn** [comment]
Changed "Hyperparameter Tuning" to lowercase "hyperparameter tuning" within notebook text cells
