### ISSUE TITLE
Lowercase "maintenance" in workbook title

### ISSUE THREAD

**Issue by aarondietz234** [GoogleCloudPlatform/vertex-ai-samples#2586]
In the following notebook:

https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/workbench/predictive_maintainance/predictive_maintenance_usecase.ipynb

In the notebook title, lowercase "maintenance" so that it's:

Predictive maintenance using Vertex AI

**Comment by katiemn** [comment]
Made "Maintenance" lowercase in notebook title
