### ISSUE TITLE
Make "custom training" lowercase in workbook title

### ISSUE THREAD

**Issue by aarondietz234** [GoogleCloudPlatform/vertex-ai-samples#2587]
In the following notebook:

https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/tensorboard/tensorboard_custom_training_with_custom_container.ipynb

In the notebook title, lowercase "custom training" so that it's:

Vertex AI TensorBoard custom training with custom container

**Comment by katiemn** [comment]
Made "Custom Training" lowercase in the notebook title
