### ISSUE TITLE
Make "hyperparameter tuning" lowercase in workbook title

### ISSUE THREAD

**Issue by aarondietz234** [GoogleCloudPlatform/vertex-ai-samples#2588]
In the following notebook:

https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/tensorboard/tensorboard_hyperparameter_tuning_with_hparams.ipynb

In the notebook title, lowercase "hyperparameter tuning" so that it's:

Vertex AI TensorBoard hyperparameter tuning with the HParams Dashboard

**Comment by katiemn** [comment]
Made "Hyperparameter Tuning" lowercase in the notebook title
