### ISSUE TITLE
"Distributed Training" should be lowercase "distributed training"

### ISSUE THREAD

**Issue by aarondietz234** [GoogleCloudPlatform/vertex-ai-samples#2589]
In the following notebook:

https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/training/get_started_with_vertex_distributed_training.ipynb

Within text cells, change instances of: Distributed Training

...to lowercase: distributed training.

**Comment by katiemn** [comment]
Made "Distributed Training" lowercase within the notebook text cells
