### ISSUE TITLE
"Batch Prediction" should be lowercase "batch prediction"

### ISSUE THREAD

**Issue by aarondietz234** [GoogleCloudPlatform/vertex-ai-samples#2590]
In the following notebook:

https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/migration/sdk-automl-image-classification-batch-online.ipynb

Within text cells, change instances of: Batch Prediction

...to lowercase: batch prediction

**Comment by katiemn** [comment]
Made "Batch Prediction" lowercase within notebook text cells
