### ISSUE TITLE
Update to reflect accurate name of Cloud Profiler

### ISSUE THREAD

**Issue by aarondietz234** [GoogleCloudPlatform/vertex-ai-samples#2591]
In the following notebook:

https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/custom/custom_training_tensorboard_profiler.ipynb

Within text cells, change instances of the following: 

* Profiler
* Vertex AI TensorBoard Profiler
* TensorBoard Profiler

...to:

Cloud Profiler

**Comment by katiemn** [comment]
Updated notebook to reflect correct naming of Cloud Profiler
