### ISSUE TITLE
Detectron2 support for keypoints rcnn support

### ISSUE THREAD

**Issue by RiccardoMaistri** [GoogleCloudPlatform/vertex-ai-samples#2607]
Will you add support for keypoints rccn using detectron2?

**Comment by gericdong** [comment]
@minwoo33park: would you please assist this question? Thanks.

**Comment by minwoo33park** [comment]
Hi! We don't have a plan to support keypoints rcnn, but you are welcome to modify the [detectron2 training dockerfile](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/community-content/vertex_model_garden/model_oss/detectron2/dockerfile/train.Dockerfile) to build your own docker image.
