### ISSUE TITLE
Error NETWORK_NOT_PEERED

### ISSUE THREAD

**Issue by alirezaomneky** [GoogleCloudPlatform/vertex-ai-samples#2611]
Hi all,

When creating a MatchingEngineIndexEndpoint using the code below:

`my_index_endpoint = aiplatform.MatchingEngineIndexEndpoint.create(
    display_name=DISPLAY_NAME,
    description=DISPLAY_NAME,
    public_endpoint_enabled=False,
    network=VPC_NETWORK_FULL,
)`

I keep getting this error: 

`Error NETWORK_NOT_PEERED`

How can I properly set up network peering to fix this issue?

Thank you

**Comment by alirezaomneky** [comment]
Is anyone else facing this issue?
I understand that this is more of a Google Cloud issue (rather than a code issue), but I am wondering if anyone else faced a similar problem and how they resolved it.

**Comment by gericdong** [comment]
@alirezaomneky please see if this doc helps: https://cloud.google.com/vertex-ai/docs/general/vpc-peering.
