### ISSUE TITLE
Issue when running the Mistral vLLM notebook

### ISSUE THREAD

**Issue by NielsRogge** [GoogleCloudPlatform/vertex-ai-samples#2620]
## Issue

When running the [sample notebook](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb) to deploy "mistralai/Mistral-7B-v0.1" with vLLM on Vertex AI without any code changes, the deployment fails:

<img width="710" alt="Screenshot 2024-01-10 at 10 32 54" src="https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/48327001/a9296856-04da-4795-85ea-e6164e5a44e9">

The logs show:

```
ERROR 2024-01-10T09:30:29.874350070Z ValueError: max_num_batched_tokens (4096) is smaller than max_model_len (32768). This effectively limits the maximum sequence length to max_num_batched_tokens and makes vLLM reject longer sequences. Please increase max_num_batched_tokens or decrease max_model_len.
  {
    "insertId": "mhj2jzf4ev0il",
    "jsonPayload": {
      "message": "ValueError: max_num_batched_tokens (4096) is smaller than max_model_len (32768). This effectively limits the maximum sequence length to max_num_batched_tokens and makes vLLM reject longer sequences. Please increase max_num_batched_tokens or decrease max_model_len."
    },
    "resource": {
      "type": "aiplatform.googleapis.com/Endpoint",
      "labels": {
        "endpoint_id": "9088607095661527040",
        "resource_container": "projects/1086157250679",
        "location": "europe-west1"
      }
    },
    "timestamp": "2024-01-10T09:30:29.874350070Z",
    "severity": "ERROR",
    "labels": {
      "deployed_model_id": "16963265393328128",
      "replica_id": "predictor-9088607095661527040-16963265393328128-7ff4794485lvzkc"
    },
    "logName": "projects/fednot-akten-ml/logs/aiplatform.googleapis.com%2Fprediction_container",
    "receiveTimestamp": "2024-01-10T09:30:30.155951824Z"
  }

```
It can be fixed by removing the "--max-num-batched-tokens=4096" argument.

## Expected behaviour

Notebook should run out-of-the-box.

Also, is there any plan to support the OpenAI-compatible vLLM server? Cause when replacing `serving_container_command=["python", "-m", "vllm.entrypoints.api_server"],` by `serving_container_command=["python", "-m", "vllm.entrypoints.openai.api_server"],` in the notebook, one gets an error that Accelerate is not installed (which is an additional dependency for the OpenAI endpoint as seen [here](https://github.com/vllm-project/vllm/blob/79d64c495463665cf80937a05226806785cfa583/Dockerfile#L76-L78). Related to https://github.com/GoogleCloudPlatform/vertex-ai-samples/issues/2575#issuecomment-1877094834

cc @kathyyu-google

**Comment by kathyyu-google** [comment]
Hi @NielsRogge, thank you for providing this feedback. We are working towards addressing the two issues you raised.

**Comment by NielsRogge** [comment]
Thanks! Also, Vertex AI endpoints doesn't support streaming tokens right?

**Comment by kathyyu-google** [comment]
> Thanks! Also, Vertex AI endpoints doesn't support streaming tokens right?

That's right

**Comment by kathyyu-google** [comment]
Hi @NielsRogge, we have updated the [Mistral/Mixtral notebook](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb) to fix the bug above. You may set `--max-model-len` and/or`--max-num-batched-tokens` for the deployment.

We have also added code examples for using the OpenAI-style vLLM server in the notebook.

Marking this issue as closed. Please feel free to reopen if there are further comments. Thank you!
