### ISSUE TITLE
Mixtral-8x7B-Instruct-v0.1 deployment fails with  ImportError: /root/.triton/cache/704764ad6ae9c3a5bc327b7bfe283d87/_padded_copy.so: undefined symbol: cuLaunchKernel

### ISSUE THREAD

**Issue by jvovk** [GoogleCloudPlatform/vertex-ai-samples#2622]
Trying to deploy Mixtral-8x7B-Instruct-v0.1 using notebook https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb.

Model deployment fails with:

ERROR 2024-01-10T20:35:28.471508502Z num_blocks = self._run_workers(
ERROR 2024-01-10T20:35:28.471519708Z File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 750, in _run_workers
ERROR 2024-01-10T20:35:28.471760988Z self._run_workers_in_batch(workers, method, *args, **kwargs))
ERROR 2024-01-10T20:35:28.471772193Z File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 727, in _run_workers_in_batch
ERROR 2024-01-10T20:35:28.471962690Z all_outputs = ray.get(all_outputs)
ERROR 2024-01-10T20:35:28.471971750Z File "/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
ERROR 2024-01-10T20:35:28.472045421Z return fn(*args, **kwargs)
ERROR 2024-01-10T20:35:28.472060680Z File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
ERROR 2024-01-10T20:35:28.472093343Z return func(*args, **kwargs)
ERROR 2024-01-10T20:35:28.472111225Z File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 2563, in get
ERROR 2024-01-10T20:35:28.472616910Z raise value.as_instanceof_cause()
ERROR 2024-01-10T20:35:28.472640514Z ray.exceptions.RayTaskError(ImportError): [36mray::RayWorkerVllm.execute_method()[39m (pid=3625, ip=10.0.3.197, actor_id=895cad5de83d8cc9a979687801000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x789b6e33ba30>)
ERROR 2024-01-10T20:35:28.472648859Z File "/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py", line 32, in execute_method
ERROR 2024-01-10T20:35:28.472666978Z return executor(*args, **kwargs)
ERROR 2024-01-10T20:35:28.472671270Z File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
ERROR 2024-01-10T20:35:28.472675800Z return func(*args, **kwargs)
ERROR 2024-01-10T20:35:28.472680330Z File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 86, in profile_num_available_blocks
ERROR 2024-01-10T20:35:28.472684383Z self.model_runner.profile_run()
ERROR 2024-01-10T20:35:28.472688436Z File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
ERROR 2024-01-10T20:35:28.472692489Z return func(*args, **kwargs)
ERROR 2024-01-10T20:35:28.472696781Z File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 321, in profile_run
ERROR 2024-01-10T20:35:28.472700595Z self.execute_model(seqs, kv_caches)
ERROR 2024-01-10T20:35:28.472705125Z File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
ERROR 2024-01-10T20:35:28.472709417Z return func(*args, **kwargs)
ERROR 2024-01-10T20:35:28.472723960Z File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 279, in execute_model
ERROR 2024-01-10T20:35:28.472731351Z hidden_states = self.model(
ERROR 2024-01-10T20:35:28.472738265Z File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
ERROR 2024-01-10T20:35:28.472745656Z return self._call_impl(*args, **kwargs)
ERROR 2024-01-10T20:35:28.472752332Z File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
ERROR 2024-01-10T20:35:28.472758293Z return forward_call(*args, **kwargs)
ERROR 2024-01-10T20:35:28.472764253Z File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/mixtral.py", line 483, in forward
ERROR 2024-01-10T20:35:28.472770214Z hidden_states = layer(
ERROR 2024-01-10T20:35:28.472776412Z File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
ERROR 2024-01-10T20:35:28.472782373Z return self._call_impl(*args, **kwargs)
ERROR 2024-01-10T20:35:28.472787857Z File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
ERROR 2024-01-10T20:35:28.472793579Z return forward_call(*args, **kwargs)
ERROR 2024-01-10T20:35:28.472799062Z File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/mixtral.py", line 438, in forward
ERROR 2024-01-10T20:35:28.472805261Z r = self.block_sparse_moe(self.ffn_norm(h))
ERROR 2024-01-10T20:35:28.472811937Z File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
ERROR 2024-01-10T20:35:28.472818136Z return self._call_impl(*args, **kwargs)
ERROR 2024-01-10T20:35:28.472823858Z File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
ERROR 2024-01-10T20:35:28.472829580Z return forward_call(*args, **kwargs)
ERROR 2024-01-10T20:35:28.472835540Z File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
ERROR 2024-01-10T20:35:28.472841262Z return func(*args, **kwargs)
ERROR 2024-01-10T20:35:28.472848653Z File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/mixtral.py", line 382, in forward
ERROR 2024-01-10T20:35:28.472854375Z x = ops.padded_scatter(
ERROR 2024-01-10T20:35:28.472859621Z File "/usr/local/lib/python3.10/dist-packages/megablocks/ops/padded_scatter.py", line 78, in padded_scatter
ERROR 2024-01-10T20:35:28.472864627Z return PaddedScatterOp.apply(x, indices, bin_ids, weights, bins,
ERROR 2024-01-10T20:35:28.472869157Z File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 539, in apply
ERROR 2024-01-10T20:35:28.472880840Z return super().apply(*args, **kwargs) # type: ignore[misc]
ERROR 2024-01-10T20:35:28.472884893Z File "/usr/local/lib/python3.10/dist-packages/stk/backend/autocast.py", line 28, in decorate_fwd
ERROR 2024-01-10T20:35:28.472888708Z return fwd(*args, **kwargs)
ERROR 2024-01-10T20:35:28.472892761Z File "/usr/local/lib/python3.10/dist-packages/megablocks/ops/padded_scatter.py", line 28, in forward
ERROR 2024-01-10T20:35:28.472896814Z return kernels.padded_scatter(
ERROR 2024-01-10T20:35:28.472900629Z File "/usr/local/lib/python3.10/dist-packages/megablocks/backend/kernels.py", line 190, in padded_scatter
ERROR 2024-01-10T20:35:28.472904920Z _padded_copy[(indices.shape[0],)](
ERROR 2024-01-10T20:35:28.472908973Z File "/usr/local/lib/python3.10/dist-packages/triton/runtime/autotuner.py", line 114, in run
ERROR 2024-01-10T20:35:28.472913742Z ret = self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **kwargs, **config.kwargs)
ERROR 2024-01-10T20:35:28.472917318Z File "<string>", line 63, in _padded_copy
ERROR 2024-01-10T20:35:28.472921133Z File "/usr/local/lib/python3.10/dist-packages/triton/compiler/compiler.py", line 515, in compile
ERROR 2024-01-10T20:35:28.472924947Z return CompiledKernel(fn, so_path, metadata, asm)
ERROR 2024-01-10T20:35:28.472929Z File "/usr/local/lib/python3.10/dist-packages/triton/compiler/compiler.py", line 528, in __init__
ERROR 2024-01-10T20:35:28.472933053Z mod = importlib.util.module_from_spec(spec)
ERROR 2024-01-10T20:35:28.472936868Z File "<frozen importlib._bootstrap>", line 571, in module_from_spec
ERROR 2024-01-10T20:35:28.472958087Z File "<frozen importlib._bootstrap_external>", line 1176, in create_module
ERROR 2024-01-10T20:35:28.472962617Z File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
**ERROR 2024-01-10T20:35:28.472966670Z ImportError: /root/.triton/cache/704764ad6ae9c3a5bc327b7bfe283d87/_padded_copy.so: undefined symbol: cuLaunchKernel**

**Comment by gericdong** [comment]
@kathyyu-google : could you please check if you can assist this issue? Thanks.

**Comment by kathyyu-google** [comment]
Hi @jvovk, we have updated the container used for deploying Mixtral-8x7B-Instruct-v0.1 and the [model notebook](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb). Please try it to see if the deployment works for you.

Marking this issue as closed. Please feel free to reopen if any error occurs, thank you!
