### ISSUE TITLE
google_cloud_pipeline_components_automl_images.ipynb fails due to AutoMLImageClassificationDeployedModelNodes quota exceeded

### ISSUE THREAD

**Issue by ivanmkc** [GoogleCloudPlatform/vertex-ai-samples#264]
Logs: https://pantheon.corp.google.com/vertex-ai/locations/us-central1/pipelines/runs/automl-image-training-v2-20220202211108?project=python-docs-samples-tests

```
RuntimeError: Failed to create the resource. Error: {'code': 8, 'message': 'The following quotas are exceeded: AutoMLImageClassificationDeployedModelNodes'}
```

# Solutions
- [ ] See why cleanup script doesn't solve this.
- [ ] Increase quota.

**Comment by kweinmeister** [comment]
I put in a request to double this quota, and it was approved.
