### ISSUE TITLE
Update 3 "Open in..." links in notebook

### ISSUE THREAD

**Issue by aarondietz234** [GoogleCloudPlatform/vertex-ai-samples#2643]
In the following notebook:

https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/prediction/get_started_with_nvidia_triton_serving.ipynb

Update the three "Open in..." links (Colab, GitHub, Vertex AI Workbench) to point to the official notebook (currently it still points to the community version).

**Comment by katiemn** [comment]
Updated the links to point to the official notebook.
