### ISSUE TITLE
Unable to connect to a repository

### ISSUE THREAD

**Issue by moro-no-kimi** [GoogleCloudPlatform/vertex-ai-samples#2668]
## Expected Behavior

On notebooks/community/model_garden/model_garden_jax_dito.ipynb
```
! svn export -r 606813 https://github.com/google-research/google-research/trunk/fvlm
```
executes without error

## Actual Behavior

raises error:
```
svn: E170013: Unable to connect to a repository at URL 'https://github.com/google-research/google-research/trunk/fvlm'
svn: E160013: '/google-research/google-research/trunk/fvlm' path not found
```

When navigating to https://github.com/google-research/google-research/trunk/fvlm in the browser, site return 404

## Steps to Reproduce the Problem

1. Open notebook in Vertex AI on Colab Enterprise
2. Connect to default instance type (e2-standard-4)
3. Run the "Installation" cell of the notebook

## Specifications

- Version: main branch
- Platform: Vertex AI workbench

**Comment by moro-no-kimi** [comment]
work around solution:

```
! mkdir google-research 

%cd google-research
! git init
! git remote add -f origin https://github.com/google-research/google-research
! git config core.sparsecheckout true
! echo "fvlm/" >> .git/info/sparse-checkout
! git pull origin master

%cd ..
! mv ./google-research/fvlm /root
! rm -rf google-research
```

**Comment by gericdong** [comment]
@huguensjean can you please take a look at this? Thanks.

**Comment by huguensjean** [comment]
Please give me a bit more time to investigate. I haven't seen the error before.

**Comment by huguensjean** [comment]
Thanks @minwoo33park.

**Comment by minwoo33park** [comment]
notebooks/community/model_garden/model_garden_jax_dito.ipynb is updated with sparse checkout, and finetuning support as well.
