### ISSUE TITLE
As always , code doesn't work

### ISSUE THREAD

**Issue by sidoncloud** [GoogleCloudPlatform/vertex-ai-samples#2678]
## **Expected Behavior**
Noone knows since your code never ran successfully.

**Ipynbk in question:** https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/generative_ai/rlhf_tune_llm.ipynb

## **Actual Behavior**
ValueError: eval_dataset not supported for text-bison@001. Please set this value to None when tuning this model. This model can be evaluated after tuning using Batch or Online Prediction.

## **Steps to Reproduce the Problem**
1. Just run each code block like a normal human would

<img width="1408" alt="Screen Shot 2024-02-06 at 11 22 19 PM" src="https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/133084113/e14e80b1-b4b0-4b46-b197-c8becb31be06">

**Comment by latture** [comment]
@sidoncloud Thanks for letting us know! We're reworking the RLHF pipeline a bit and temporarily disabled the `eval_dataset` for first-part models. I just opened #2700, so we don't get validation errors in the meantime.

**Comment by katiemn** [comment]
Merged #2700 to mitigate validation errors
