### ISSUE TITLE
Notebook https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/explainable_ai/sdk_custom_tabular_regression_online_explain_get_metadata.ipynb and others fail with internal 500 error when doing model.explain

### ISSUE THREAD

**Issue by jmbrinkman** [GoogleCloudPlatform/vertex-ai-samples#2736]
## Expected Behavior

Notebook purpose is to show how to train and deploy a model with explainable AI. 

## Actual Behavior

Explain functionality fails with internal 500 error. Uploading the model with explanation metadata etc all works like a charm, but when and explanation is requested with test data in the notebook the request fails. Predictions for that same test data work fine.

## Steps to Reproduce the Problem

Follow the notebook cells. I followed all the defaults ( and tried with different TF versions for instance).

**Comment by gericdong** [comment]
Closed. Please reopen if it's still relevant.
