### ISSUE TITLE
model_garden_pytorch_stable_diffusion_xl_1_0.ipynb notebook not working with SDXL-REFINER option.

### ISSUE THREAD

**Issue by hiber-stefan** [GoogleCloudPlatform/vertex-ai-samples#2773]
## Expected Behavior

When running the notebook with SDXL-REFINER, the resulting endpoint should be queryable.

## Actual Behavior

When submitting predictions, either with notebook or directly via model registry, returns
"Model server is not available. Please retry."

## Steps to Reproduce the Problem

- set up notebook model_garden_pytorch_stable_diffusion_xl_1_0.ipynb, with DEPLOY_MODE = "SDXL-REFINER"
- run through deployment steps 
- wait for 5-10 minutes to ensure the predictor has installed
- run cabybara prediction step

## Specifications
- Version: pytorch-diffusers-serve-opt 20240223_1230_RC00 and 20240313_0836_RC00
- Platform: Default settings

**Comment by gericdong** [comment]
@weigary: could you please assist? Thanks.

**Comment by hiber-stefan** [comment]
Ok, so fixing that obvious omission of refiner_model_id did set the ENV variable, but since I don't have the source code for the docker, I can't evaluate if the REFINER_MODEL_ID is well formed or not.

**Comment by weigary** [comment]
Thanks I can reproduce the error on my end. Will send out a fix soon.

**Comment by weigary** [comment]
Sent out https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/2774

**Comment by weigary** [comment]
Should be fixed now.

**Comment by hiber-stefan** [comment]
@weigary thank you for looking into this. Upon redeploying with your fix, I now get

ServiceUnavailable: 503 {
  "code": 503,
  "type": "InternalServerException",
  "message": "Prediction failed"
}

please advise on how I can provide more info to get this resolved?

**Comment by weigary** [comment]
Hi Stefan,

It is a separate issue which I will send out an official tomorrow. However there is a workaround for it, by adding an empty "negative_prompt" field to the instances object. For example:

instances = [
    {
        "prompt": prompt,
        "negative_prompt": "",
        "height": height,
        "width": width,
        "num_inference_steps": num_inference_steps,
        "guidance_scale": guidance_scale,
    },
]

**Comment by hiber-stefan** [comment]
@weigary I can verify that adding an empty negative prompt using 20240314_0836_RC00 works. Again, thank you for the help!
