### ISSUE TITLE
Gemma in Model Garden Deployment - confusing section on Chat Applications

### ISSUE THREAD

**Issue by afirstenberg** [GoogleCloudPlatform/vertex-ai-samples#2800]
Environment
* Deployed a gemma-7b-it model on Vertex AI Model Garden using the "Deploy" button from the Gemma card. No additional tuning was done.
* I have an instance running on a g2-standard-12 machine with I4 GPU. It is visible in the Online Prediction section of my Cloud Console. 
* I am able to reach the endpoint without any issues.

Unable to find any good documentation on what needs to be sent to the model and what to get back, I used the "Model Garden Gemma Deployment on Vertex" notebook to try and get an idea. (See #2799 for a related issue.)

Description:
* The instructions in the section "Build chat applications with Gemma" indicate that there are templates that define the structure of a conversation.
* The code shows how to use the template to create a prompt.
* However, the prompt that is created isn't sent to the model. Instead, the text from a previous example is.
* Furthermore, even if I do send the text to the model, it doesn't seem to respond any differently.
* As with #2799, the response format that is to be expected isn't documented.

See starting 
https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/b37ed6e53c9d4e63b5e663b3a3d3d08bb7f73ac2/notebooks/community/model_garden/model_garden_gemma_deployment_on_vertex.ipynb#L667

**Comment by gericdong** [comment]
@kathyyu-google: could you please assist with this? Thanks.

**Comment by kathyyu-google** [comment]
Thank you @afirstenberg for this feedback. We will work on clarifying the chat application usage in this notebook.

**Comment by kathyyu-google** [comment]
We have updated the notebook to adopt the OpenAI chat completions API for chat application usage: https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/3088fc896da5b73b390293e916aaab4cd06e09e8/notebooks/community/model_garden/model_garden_gemma_deployment_on_vertex.ipynb. Additional documentation for the API is available here: https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/call-vertex-using-openai-library#supported_parameters.

Marking this issue as closed. Please reopen if there are any further questions, thank you!
