### ISSUE TITLE
Dataset creation

### ISSUE THREAD

**Issue by 75andybermond** [GoogleCloudPlatform/vertex-ai-samples#2809]
## Expected Behavior
Create a dataset from IMPORT_FILE csv not complete.

## Actual Behavior
In _vertex_samples/official/model_monitoring_ most of the netobooks requires to import :
_"gs://cloud-samples-data/vision/automl_classification/flowers/all_data_v2.csv"_ in order to create dataset. Unfortunatly I've tried many times and after waiting long period, I get message error that mention some of the images wihtin the csv files are not present/available.

## Steps to Reproduce the Problem

1. Run notebook _get_started_with_model_monitoring_automl_image_online.ipynb_ or _get_started_with_model_monitoring_automl.ipynb_ .
2.A the cell to create the dataset it will take time until error message comes
3. Leave it run for a while.

**Comment by gericdong** [comment]
This issue has been addressed.
