### ISSUE TITLE
vertex ai pipeline key error root

### ISSUE THREAD

**Issue by raihan1khan** [GoogleCloudPlatform/vertex-ai-samples#2822]
## Expected Behavior
tryin to use this example to run the pipeline but running into key root errors
https://github.com/GoogleCloudPlatform/fraudfinder/blob/main/vertex_ai/06_formalization.ipynb

## Actual Behavior
running into key errors
   (...)

     80   A PipelineRuntimeConfigBuilder object.

     81 """

     82 runtime_config_spec = job_spec["runtimeConfig"]

     83 parameter_input_definitions = (

---> 84     job_spec["pipelineSpec"]["root"]

     85     .get("inputDefinitions", {})

     86     .get("parameters", {})

     87 )

     88 schema_version = job_spec["pipelineSpec"]["schemaVersion"]

     90 # 'type' is deprecated in IR and change to 'parameterType'.

KeyError: 'root'
## Steps to Reproduce the Problem

1. compile and run the pipeline to generate components configuration
1. when i run pipeline_job code, it will through key root errors
1.

## Specifications

- Version:
- Platform:

**Comment by gericdong** [comment]
@raihan1khan: please open the issue in repo: https://github.com/GoogleCloudPlatform/fraudfinder/issues? Thanks.
