### ISSUE TITLE
issue(): automl_forecasting workshop

### ISSUE THREAD

**Issue by MichaelWalker-git** [GoogleCloudPlatform/vertex-ai-samples#2896]
https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/automl/automl_forecasting_on_vertex_pipelines.ipynb

## Expected Behavior

<img width="665" alt="Screenshot 2024-04-24 at 11 51 03 AM" src="https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/11032490/ce95917e-364a-4320-adf4-a066894d0e2d">

The directions state that we need to update this IAM role, however, this "gcp-sa...." role might be google specific

## Actual Behavior

I am unsure.

## Steps to Reproduce the Problem

1. See here: https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/automl/automl_forecasting_on_vertex_pipelines.ipynb?short_path=b788c6d#L238

## Specifications

- Version: Current Github Notebook for Workshop
- Platform: Vertex AI

**Comment by gericdong** [comment]
@MichaelWalker-git  This referred service accounts were created automatically in the system. You also can create you own service account.
