### ISSUE TITLE
Mistral finetuning notebook not working

### ISSUE THREAD

**Issue by bl4val** [GoogleCloudPlatform/vertex-ai-samples#2907]
Hello.
I've been following the [model_garden_pytorch_mistral_peft_tuning](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_pytorch_mistral_peft_tuning.ipynb) notebook training in `europe-west2` on `NVIDIA_L4`. The rest of the parameters are the default ones. It's also the default training dataset.

With the current `TRAIN_DOCKER_URI`  one gets the following logs
```
CUDA extension not installed.

Downloading builder script:   0%|          | 0.00/5.67k [00:00<?, ?B/s]
Downloading builder script: 100%|██████████| 5.67k/5.67k [00:00<00:00, 21.3MB/s]"

2024-04-30:08:49:57,398 WARNING  [__init__.py:145] /lm-evaluation-harness/lm_eval/tasks/benchmarks/t0_eval.yaml: No module named 'promptsource'. Config will not be added to registry.
```
And then nothing happens, CPU and GPU utilization stays at zero for at least 2 hours.

Choosing the latest training image `pytorch-peft-train:20240429_0936_RC00`
The Cuda error disappears at, one gets:
```
Downloading builder script:   0%|          | 0.00/5.67k [00:00<?, ?B/s]
Downloading builder script: 100%|██████████| 5.67k/5.67k [00:00<00:00, 21.3MB/s]"

2024-04-30:08:49:57,398 WARNING  [__init__.py:145] /lm-evaluation-harness/lm_eval/tasks/benchmarks/t0_eval.yaml: No module named 'promptsource'. Config will not be added to registry.

I0430 12:55:55.168113 136656347698368 modeling.py:987] We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
```
And then nothing happens, CPU and GPU utilization stays at zero for at least 2 hours.

Trying to run the latest training image locally shows that bitsandbytes was compiled without GPU
```
/opt/conda/lib/python3.11/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/opt/conda/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
```

I want to be able to train the `Mistral-7B-v0.1` model on vertex ai.

**Comment by chrisn-apokto-io** [comment]
@bl4val I see you market this as completed. I'm having the exact same problem with the latest `pytorch-peft-train:20240509_0936_RC00`. How did you fix it?

**Comment by felipeliliti** [comment]
Liberado

**Comment by bl4val** [comment]
@chrisn-apokto-io  It's the download, it takes around 13 hours. So you just have to wait. I changed to colab enterprise and download from huggingface instead. It takes around 1 min instead.

**Comment by chrisn-apokto-io** [comment]
> @chrisn-apokto-io  It's the download, it takes around 13 hours. So you just have to wait. I changed to colab enterprise and download from huggingface instead. It takes around 1 min.

To be clear, you're talking about the model download and doing it via Huggingface, correct?

**Comment by bl4val** [comment]
Yes, and also from a notebook in Colab Enterprise. Not sure sure which of the two solved the download issue.
