### ISSUE TITLE
Creation of Feature View from BigQuery failed with AttributeError

### ISSUE THREAD

**Issue by jieshi1010** [GoogleCloudPlatform/vertex-ai-samples#2924]
## Expected Behavior
Feature View is created. 

## Actual Behavior
Got below error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-25-a136afc10ebe>](https://localhost:8080/#) in <cell line: 14>()
     12 
     13 print(f"index_config: {index_config}")
---> 14 my_fv = my_fos.create_feature_view_from_big_query(
     15     FEATURE_VIEW_ID,
     16     big_query_source=big_query_source,

AttributeError: 'FeatureOnlineStore' object has no attribute 'create_feature_view_from_big_query'

## Steps to Reproduce the Problem

1. Run the notebook: https://github.com/jieshi1010/vertex-ai-samples/blob/main/notebooks/official/feature_store/online_feature_serving_and_vector_retrieval_bigquery_data_with_feature_store.ipynb
2. When creating a feature view from BigQuery, it throws an error saying that AttributeError: 'FeatureOnlineStore' object has no attribute 'create_feature_view_from_big_query'

## Specifications

- Version:
- Platform:

**Comment by gericdong** [comment]
@jieshi1010 :  It's possible that you were using an older version of the package. can you please update the google-cloud-aiplatform package and try again? Thanks.
