### ISSUE TITLE
Ray on Vertex Notebook Failure

### ISSUE THREAD

**Issue by happy-qiao** [GoogleCloudPlatform/vertex-ai-samples#3078]
## Expected Behavior
https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/ray_on_vertex_ai/get_started_with_pytorch_rov.ipynb run successfully

## Actual Behavior
https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/ray_on_vertex_ai/get_started_with_pytorch_rov.ipynb failed at this cell
```
client = JobSubmissionClient(
    address="vertex_ray://{}".format(ray_cluster.dashboard_address)
)
```
with error message
<img width="875" alt="Screenshot 2024-06-10 at 13 55 03" src="https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/159568575/e6b09584-ecb1-475f-9cac-f80ec6e28543">

## Steps to Reproduce the Problem

1.Run this script in workbench: [Open in Vertex AI Workbench](https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/ray_on_vertex_ai/get_started_with_pytorch_rov.ipynb)
1.Remove `! gcloud config set project {PROJECT_ID}` because workbench already has project_id set.
1.Fill necessary params and execute All cells

## Specifications

- Version:
- Platform:

**Comment by gericdong** [comment]
@inardini can you please help take a look? Thanks

**Comment by inardini** [comment]
This is going to be address here #3131 . Thanks
