### ISSUE TITLE
default_compression error when running a sample

### ISSUE THREAD

**Issue by natea11** [GoogleCloudPlatform/vertex-ai-samples#3084]
## Expected Behavior
The sample should work

## Actual Behavior
I get a default_compression error.

## Steps to Reproduce the Problem

1. I try to run the file get_started_automl_training.ipynb.
2. When I run the step: 
    dataset = aiplatform.ImageDataset.create(
    display_name="flowers",
    gcs_source=[IMPORT_FILE],
    import_schema_uri=aiplatform.schema.dataset.ioformat.image.single_label_classification,
    )

    print(dataset.resource_name)

I get the error:
  TypeError                                 Traceback (most recent call last)
  Cell In[14], line 1
  ----> 1 dataset = aiplatform.ImageDataset.create(
        2     display_name="flowers",
        3     gcs_source=[IMPORT_FILE],
        4     import_schema_uri=aiplatform.schema.dataset.ioformat.image.single_label_classification,
        5 )
        7 print(dataset.resource_name)
  
  File /opt/conda/lib/python3.10/site-packages/google/cloud/aiplatform/datasets/image_dataset.py:180, in ImageDataset.create(cls, display_name, gcs_source, import_schema_uri, data_item_labels, project, location, credentials, request_metadata, labels, encryption_spec_key_name, sync, create_request_timeout)
      171 metadata_schema_uri = schema.dataset.metadata.image
      173 datasource = _datasources.create_datasource(
      174     metadata_schema_uri=metadata_schema_uri,
      175     import_schema_uri=import_schema_uri,
      176     gcs_source=gcs_source,
      177     data_item_labels=data_item_labels,
      178 )
  --> 180 return cls._create_and_import(
      181     api_client=api_client,
      182     parent=initializer.global_config.common_location_path(
      183         project=project, location=location
      184     ),
      185     display_name=display_name,
      186     metadata_schema_uri=metadata_schema_uri,
      187     datasource=datasource,
      188     project=project or initializer.global_config.project,
      189     location=location or initializer.global_config.location,
      190     credentials=credentials or initializer.global_config.credentials,
      191     request_metadata=request_metadata,
      192     labels=labels,
      193     encryption_spec=initializer.global_config.get_encryption_spec(
      194         encryption_spec_key_name=encryption_spec_key_name
      195     ),
      196     sync=sync,
      197     create_request_timeout=create_request_timeout,
      198 )
  
  File /opt/conda/lib/python3.10/site-packages/google/cloud/aiplatform/base.py:863, in optional_sync.<locals>.optional_run_in_thread.<locals>.wrapper(*args, **kwargs)
      861     if self:
      862         VertexAiResourceNounWithFutureManager.wait(self)
  --> 863     return method(*args, **kwargs)
      865 # callbacks to call within the Future (in same Thread)
      866 internal_callbacks = []
  
  File /opt/conda/lib/python3.10/site-packages/google/cloud/aiplatform/datasets/dataset.py:342, in _Dataset._create_and_import(cls, api_client, parent, display_name, metadata_schema_uri, datasource, project, location, credentials, request_metadata, labels, encryption_spec, sync, create_request_timeout, import_request_timeout)
      259 @classmethod
      260 @base.optional_sync()
      261 def _create_and_import(
     (...)
      276     import_request_timeout: Optional[float] = None,
      277 ) -> "_Dataset":
      278     """Creates a new dataset and optionally imports data into dataset when
      279     source and import_schema_uri are passed.
      280 
     (...)
      339             Instantiated representation of the managed dataset resource.
      340     """
  --> 342     create_dataset_lro = cls._create(
      343         api_client=api_client,
      344         parent=parent,
      345         display_name=display_name,
      346         metadata_schema_uri=metadata_schema_uri,
      347         datasource=datasource,
      348         request_metadata=request_metadata,
      349         labels=labels,
      350         encryption_spec=encryption_spec,
      351         create_request_timeout=create_request_timeout,
      352     )
      354     _LOGGER.log_create_with_lro(cls, create_dataset_lro)
      356     created_dataset = create_dataset_lro.result(timeout=None)
  
  File /opt/conda/lib/python3.10/site-packages/google/cloud/aiplatform/datasets/dataset.py:467, in _Dataset._create(cls, api_client, parent, display_name, metadata_schema_uri, datasource, request_metadata, labels, encryption_spec, create_request_timeout)
      411 """Creates a new managed dataset by directly calling API client.
      412 
      413 Args:
     (...)
      456         An object representing a long-running operation.
      457 """
      459 gapic_dataset = gca_dataset.Dataset(
      460     display_name=display_name,
      461     metadata_schema_uri=metadata_schema_uri,
     (...)
      464     encryption_spec=encryption_spec,
      465 )
  --> 467 return api_client.create_dataset(
      468     parent=parent,
      469     dataset=gapic_dataset,
      470     metadata=request_metadata,
      471     timeout=create_request_timeout,
      472 )
  
  File /opt/conda/lib/python3.10/site-packages/google/cloud/aiplatform_v1/services/dataset_service/client.py:951, in DatasetServiceClient.create_dataset(self, request, parent, dataset, retry, timeout, metadata)
      941 response = rpc(
      942     request,
      943     retry=retry,
      944     timeout=timeout,
      945     metadata=metadata,
      946 )
      948 # Wrap the response in an operation future.
      949 response = gac_operation.from_gapic(
      950     response,
  --> 951     self._transport.operations_client,
      952     gca_dataset.Dataset,
      953     metadata_type=dataset_service.CreateDatasetOperationMetadata,
      954 )
      956 # Done; return the response.
      957 return response
  
  File /opt/conda/lib/python3.10/site-packages/google/cloud/aiplatform_v1/services/dataset_service/transports/grpc.py:258, in DatasetServiceGrpcTransport.operations_client(self)
      256 # Quick check: Only create a new client if we do not already have one.
      257 if self._operations_client is None:
  --> 258     self._operations_client = operations_v1.OperationsClient(self.grpc_channel)
      260 # Return the client from cache.
      261 return self._operations_client
  
  File /opt/conda/lib/python3.10/site-packages/google/api_core/operations_v1/operations_client.py:78, in OperationsClient.__init__(self, channel, client_config)
       74 default_timeout = timeouts.TimeToDeadlineTimeout(timeout=600.0)
       76 default_compression = Compression.NoCompression
  ---> 78 self._get_operation = gapic_v1.method.wrap_method(
       79     self.operations_stub.GetOperation,
       80     default_retry=default_retry,
       81     default_timeout=default_timeout,
       82     default_compression=default_compression,
       83 )
       85 self._list_operations = gapic_v1.method.wrap_method(
       86     self.operations_stub.ListOperations,
       87     default_retry=default_retry,
       88     default_timeout=default_timeout,
       89     default_compression=default_compression,
       90 )
       92 self._cancel_operation = gapic_v1.method.wrap_method(
       93     self.operations_stub.CancelOperation,
       94     default_retry=default_retry,
       95     default_timeout=default_timeout,
       96     default_compression=default_compression,
       97 )
  
  TypeError: wrap_method() got an unexpected keyword argument 'default_compression'

## Specifications

- Version:  Python 3 (ipykernel)
- Platform:  Vertex AI workbench instance

Thank you for the help.

**Comment by gericdong** [comment]
Thanks for reporting this issue. It's possible that it's a project quota issue. Can you please contact support thru https://cloud.google.com/support/docs/issue-trackers? Thanks.

**Comment by rafman-rev** [comment]
Hi @gericdong I have the same issue, what is the current working solution?
