### ISSUE TITLE
Maybe a font format problem in a sample

### ISSUE THREAD

**Issue by natea11** [GoogleCloudPlatform/vertex-ai-samples#3113]
## Expected Behavior
The code should show correctly.   The code is under the Batch prediction job in the automl-text-classification.ipynb file.

## Actual Behavior
The font is enlarged and the code won't run.  (See attached image.)

## Steps to Reproduce the Problem

1.  I just opened the file on github.com

## Specifications
N/A
![Screenshot (19)](https://github.com/GoogleCloudPlatform/vertex-ai-samples/assets/6468274/cd6ba7d4-fabb-42a4-9f17-7fe9adc6c47d)

**Comment by gericdong** [comment]
@natea11: thank you for reporting this issue. This appears to be an issue with the Github notebook viewer. The notebook itself is fine. Thank you for letting us know.
