### ISSUE TITLE
AnthropicVertex stream chat generation is taking too much time

### ISSUE THREAD

**Issue by DhruvThu** [GoogleCloudPlatform/vertex-ai-samples#3166]
Recently, i have started using AnthropicVertex instead of direct anthropic. When I try to generate some data through AnthropicVertex client, it is taking around 2s to start streaming. However, in case of direct anthropic, it is not taking this much time. Also 2s duration is random, sometime it takes quite large amount of time and goes upto 6-10s. In worse case, it goes upto 20s. So, is there any que kind of stuff? I am using same code given in vertex ai anthropic notebook to generate responses. Is there any workaround which i need to complete to get response as fast as direct anthropic? If someone could guide me on this, it would be really helpful.

Thanks !!

**Comment by gericdong** [comment]
Thanks for reaching out here. For this possible latency issue, I'd suggest to contact support or open support ticket here: https://cloud.google.com/support/docs/issue-trackers
