### ISSUE TITLE
Deployed custom container to vertex but container is unable to access gpu

### ISSUE THREAD

**Issue by pulkitmehtaworkmetacube** [GoogleCloudPlatform/vertex-ai-samples#3250]
## Expected Behavior
Container should be able to acces GPU device . 

## Actual Behavior
Container is not able to access GPU device.

## Steps to Reproduce the Problem

We deployed a custom container to vertex ai , it has prebuilt torch GPU container us-docker.pkg.dev/vertex-ai/training/pytorch-gpu.1-13.py310:latest as base image but when we deploy it to vertex using n1-highmem-8 machine and tesla t4 gpu , container is not able to access GPU , device is still CPU . Please guide . 

## Specifications
n1-highmem-8
tesla-t4 gpu
- Version:
- Platform:

**Comment by gericdong** [comment]
Thanks for reporting the issue. For general assistance, please contact support or use https://cloud.google.com/support/docs/issue-trackers.
