### ISSUE TITLE
Stable Diffusion Subject Fidelity(DINO) and Prompt Fidelity(COCA) Calculation

### ISSUE THREAD

**Issue by Sundragon1993** [GoogleCloudPlatform/vertex-ai-samples#3302]
Dear team, thank you for the comprehensive benchmark of Stable diffusion fine-tune approaches. 

Could you give the procedure or snippet of code to calculate the Subject Fidelity(DINO) and Prompt Fidelity (COCA) which were shown in this file: https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/community-content/vertex_model_garden/benchmarking_reports/stable_diffusion_v1-5_benchmarking_report.md ?  
I've been searching for these keywords but have not had success yet.

**Comment by weigary** [comment]
Hi,

Thanks for reading the benchmark! 

Unfortunately the DINO and COCA calculation algorithms are from an internal implementation which has not yet open sourced. But I believe we can do something similar by following the two papers. There might also be some open-sourced similar algorithms available.

[1] (DINO)](https://arxiv.org/abs/2104.14294)
[2] [prompt fidelity scores (CoCa)](https://arxiv.org/abs/2205.01917),
