### ISSUE TITLE
How to add header to AnthropicVertex Python request

### ISSUE THREAD

**Issue by SomebodySysop** [GoogleCloudPlatform/vertex-ai-samples#3330]
## Expected Behavior

Allow max output tokens of 8192 when making calls to claude-sonnet-3.5 using AnthropicVertex SDK (Python)

## Actual Behavior

Only 4196 output tokens allows.

## Steps to Reproduce the Problem

From: https://docs.anthropic.com/en/docs/about-claude/models

> Max output | 8192 tokens1
> 8192 output tokens is in beta and requires the header anthropic-beta: max-tokens-3-5-sonnet-2024-07-15. If the header is not specified, the limit is 4096 tokens.
> 

Question:  How do I add _anthropic-beta: max-tokens-3-5-sonnet-2024-07-15_ to header when using AnthropicVertex SDK?

## Specifications

- Version:  Python 3.11.9.  AnthropicVertex was installed about a month ago.
- Platform: Linux system with Vertex AI Platform and Anthropic Vertex SDKs installed for Python

**Comment by SomebodySysop** [comment]
After extensive online searches, I did find two ways advertised to modify the headers to increase the maximum output tokens:

https://github.com/anthropics/anthropic-sdk-python?tab=readme-ov-file#default-headers
```
    client = AnthropicVertex(
        region=LOCATION,
        project_id=project_id,
		# https://github.com/anthropics/anthropic-sdk-python?tab=readme-ov-file#default-headers
		default_headers={"anthropic-beta": "max-tokens-3-5-sonnet-2024-07-15"} # Custom headers here
    )
```
And also:

 https://x.com/alexalbert__/status/1812921642143900036

```
    message = client.messages.create(
        max_tokens=max_tokens,
        messages=[
            {
                "role": "user",
                "content": content,
            }
        ],
        model="claude-3-5-sonnet@20240620",
        # https://x.com/alexalbert__/status/1812921642143900036
		extra_headers={"anthropic-beta": "max-tokens-3-5-sonnet-2024-07-15"}  # Custom headers here
    )
```
But neither way appears to work in the AnthropicVertex SDK:

> Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'max_tokens: 8192 > 4096, which is the maximum allowed number of output tokens for claude-3-5-sonnet-20240620'}}

**Comment by gericdong** [comment]
Thanks for reporting this issue. I'd suggest to contact AnthropicVertex SDK support for assistance.
