### ISSUE TITLE
HexLLM deployment - OSError: /tmp/gcs/gemma-funccall-keras-lora-train_20240801_060033 does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by ranasaurus9** [GoogleCloudPlatform/vertex-ai-samples#3375]
## Expected Behavior
Model deployed successfully

## Actual Behavior
ERROR:	Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
async with self.lifespan_context(app) as maybe_state:
File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
return await anext(self.gen)
File "/workspace/hex-llm/hex_llm/server/api_server.py", line 28, in lifespan
engine = AsyncLLMEngine.from_engine_args(engine_args)
File "/workspace/hex-llm/hex_llm/engine/llm_engine.py", line 179, in from_engine_args
engine_configs = engine_args.create_engine_configs()
File "/workspace/hex-llm/hex_llm/args.py", line 237, in create_engine_configs
model_config = ModelConfig(
File "/workspace/hex-llm/hex_llm/config.py", line 53, in __init__
self.hf_config = get_config(self.model, self.trust_remote_code)
File "/workspace/hex-llm/hex_llm/transformers_utils/config.py", line 6, in get_config
config = AutoConfig.from_pretrained(model, trust_remote_code=trust_remote_code)
File "/usr/local/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 928, in from_pretrained
config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
File "/usr/local/lib/python3.10/site-packages/transformers/configuration_utils.py", line 631, in get_config_dict
config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
File "/usr/local/lib/python3.10/site-packages/transformers/configuration_utils.py", line 686, in _get_config_dict
resolved_config_file = cached_file(
File "/usr/local/lib/python3.10/site-packages/transformers/utils/hub.py", line 369, in cached_file
raise EnvironmentError(
OSError: /tmp/gcs/gemma-funccall-keras-lora-train_20240801_060033 does not appear to have a file named config.json. Checkout 'https://huggingface.co//tmp/gcs/gemma-funccall-keras-lora-train_20240801_060033/tree/None' for available files.

## Steps to Reproduce the Problem

Running the below code
```
KERAS_TRAIN_DOCKER_URI = "us-docker.pkg.dev/vertex-ai/vertex-vision-model-garden-dockers/jax-keras-train-tpu:20240422_0939_RC00"
KERAS_MODEL_CONVERSION_DOCKER_URI = "us-docker.pkg.dev/vertex-ai/vertex-vision-model-garden-dockers/jax-keras-model-conversion:20240422_0949_RC00"
HEXLLM_DOCKER_URI = "us-docker.pkg.dev/vertex-ai-restricted/vertex-vision-model-garden-dockers/hex-llm-serve:deploy"
```

```
def deploy_model_hexllm(
    model_name: str,
    model_id: str,
    service_account: str,
    base_model_id: str = None,
    tensor_parallel_size: int = 1,
    machine_type: str = "ct5lp-hightpu-1t",
    hbm_utilization_factor: float = 0.6,
    max_running_seqs: int = 256,
    endpoint_id: str = "",
    min_replica_count: int = 1,
    max_replica_count: int = 1,
) -> Tuple[aiplatform.Model, aiplatform.Endpoint]:
    """Deploys models with Hex-LLM on TPU in Vertex AI."""
    if endpoint_id:
        aip_endpoint_name = (
            f"projects/{PROJECT_ID}/locations/{REGION}/endpoints/{endpoint_id}"
        )
        endpoint = aiplatform.Endpoint(aip_endpoint_name)
    else:
        endpoint = aiplatform.Endpoint.create(
            display_name=f"{model_name}-endpoint",
            location=TPU_DEPLOYMENT_REGION,
        )

    if not base_model_id:
        base_model_id = model_id

    if not tensor_parallel_size:
        tensor_parallel_size = int(machine_type[-2])

    hexllm_args = [
        "--host=0.0.0.0",
        "--port=7080",
        "--log_level=INFO",
        f"--model={model_id}",
        f"--tensor_parallel_size={tensor_parallel_size}",
        "--enable_jit",
        "--load_format=auto",
        f"--hbm_utilization_factor={hbm_utilization_factor}",
        f"--max_running_seqs={max_running_seqs}",
    ]

    env_vars = {
        "MODEL_ID": base_model_id,
        "PJRT_DEVICE": "TPU",
        "RAY_DEDUP_LOGS": "0",
        "RAY_USAGE_STATS_ENABLED": "0",
        "DEPLOY_SOURCE": "notebook",
    }

    try:
        if HF_TOKEN:
            env_vars.update({"HF_TOKEN": HF_TOKEN})
    except:
        pass

    model = aiplatform.Model.upload(
        display_name=model_name,
        serving_container_image_uri=HEXLLM_DOCKER_URI,
        serving_container_command=["python", "-m", "hex_llm.server.api_server"],
        serving_container_args=hexllm_args,
        serving_container_ports=[7080],
        serving_container_predict_route="/generate",
        serving_container_health_route="/ping",
        serving_container_environment_variables=env_vars,
        serving_container_shared_memory_size_mb=(16 * 1024),  # 16 GB
        serving_container_deployment_timeout=7200,
        location=TPU_DEPLOYMENT_REGION,
    )

    model.deploy(
        endpoint=endpoint,
        machine_type=machine_type,
        deploy_request_timeout=1800,
        service_account=service_account,
        min_replica_count=min_replica_count,
        max_replica_count=max_replica_count,
    )
    return model, endpoint
```

```
TPU_DEPLOYMENT_REGION = "us-west1"
machine_type = "ct5lp-hightpu-4t"
accelerator_type = "TPU_V5e"
accelerator_count = 4

print("Using model from: ", output_folder)
model, endpoint = deploy_model_hexllm(
    model_name=get_job_name_with_datetime(prefix="gemma-serve-hexllm"),
    base_model_id=f"google/{KAGGLE_MODEL_ID}",
    model_id=output_folder,
    service_account=SERVICE_ACCOUNT,
    machine_type=machine_type,
  )
print("endpoint_name:", endpoint.name)
```

## Specifications

- Version: google-cloud-aiplatform==1.59.0
- Platform: Colab enterprise

**Comment by kathyyu-google** [comment]
Thanks @ranasaurus9 for reaching out. The error logs seem to suggest that only the LoRA adapter was provided as the model artifacts for the deployment, not the base model artifacts. Please verify whether that is the case. If that is the case and the intention is to serve a fine-tuned model, please merge the LoRA adapter with the base model and re-deploy with the artifacts of the merged model.

**Comment by kathyyu-google** [comment]
Closing this issue because the potential cause has been proposed and there hasn't been a continued discussion. Please reopen if needed, thanks!
