### ISSUE TITLE
Regression test failures: Explainability notebooks have GAPIC API retries that are too short

### ISSUE THREAD

**Issue by ivanmkc** [GoogleCloudPlatform/vertex-ai-samples#339]
Build log: https://pantheon2.corp.google.com/cloud-build/builds;region=global/3d191399-2605-44d7-9422-c6f5768e10e2?project=python-docs-samples-tests

- gapic-custom_image_classification_batch_explain.ipynb
- gapic-custom_image_classification_online_explain.ipynb
- gapic-custom_tabular_regression_batch_explain.ipynb
- gapic-custom_tabular_regression_online_explain.ipynb

Likely all are failing at the model upload step.

**Comment by andrewferlitsch** [comment]
closing.  notebooks deprecated with SDK equivalents.
