### ISSUE TITLE
Regression test failures: Various KFP failures

### ISSUE THREAD

**Issue by ivanmkc** [GoogleCloudPlatform/vertex-ai-samples#341]
https://pantheon2.corp.google.com/cloud-build/builds;region=global/3d191399-2605-44d7-9422-c6f5768e10e2?project=python-docs-samples-tests

-  automl_tabular_classification_beans.ipynb: https://console.cloud.google.com/cloud-build/builds/75d65a4d-bdde-4d86-a922-6fcc626c1a10?project=1012616486416
- custom_model_training_and_batch_prediction.ipynb: https://console.cloud.google.com/cloud-build/builds/a2597317-9cb4-4d24-84d1-906c5896c209?project=1012616486416
- google_cloud_pipeline_components_automl_tabular.ipynb: https://console.cloud.google.com/cloud-build/builds/907259e8-8b21-4aef-8740-4127558fbef1?project=1012616486416
- google_cloud_pipeline_components_automl_text.ipynb: https://console.cloud.google.com/cloud-build/builds/a8b53d3b-9ab4-420b-a398-c573f2f79307?project=1012616486416
- pipelines_intro_kfp.ipynb: https://console.cloud.google.com/cloud-build/builds/43b4e35d-d11e-446e-8ef0-205a8638226d?project=1012616486416

On initiail inspection, could be a 500 error or a retry timeout.

**Comment by andrewferlitsch** [comment]
**custom_model_training_and_batch_prediction.ipynb:**
**pipelines_intro_kfp.ipynb:**
...
 ---> 29 from googleapiclient import discovery
 ...
Step #3: ContextualVersionConflict: (google-api-core 2.3.2 (/builder/home/.local/lib/python3.9/site-packages), Requirement.parse('google-api-core<2dev,>=1.21.0'), {'google-api-python-client'})
Step #3: 
Finished Step #3
ERROR
ERROR: build step 3 "gcr.io/cloud-devrel-public-resources/python-samples-testing-docker:latest" failed: step exited with non-zero status: 1


Appears to be a version conflict. For intro_kfp notebook, the root import is AIPlatformClient. For custom_model, it is tf.

**Comment by andrewferlitsch** [comment]
latent errors in notebook ingestion testing. We now have new versions of the notebooks/PRs. Closing as obsolete.
