### ISSUE TITLE
com.google.cloud.ai.platform.common.errors.AiPlatformException: code=RESOURCE_EXHAUSTED, message=The following quota metrics exceed quota limits: aiplatform.googleapis.com/custom_model_training_cpus, cause=null; Failed to create custom job for the task. 

### ISSUE THREAD

**Issue by dkml-123** [GoogleCloudPlatform/vertex-ai-samples#3479]
## Expected Behavior

Vertex AI Scheduler gives error when performed on workbench notebooks.

**Comment by gericdong** [comment]
@dkml-123: was there a specific notebook failing on this error?

**Comment by dkml-123** [comment]
Yes. https://codelabs.developers.google.com/vertex-p2p-training#0

**Comment by gericdong** [comment]
Thanks for reporting the issue but we won't be able to provide support for this Codelab tutorial.
Please try to open an issue here: https://cloud.google.com/support/docs/issue-trackers if you still need assistance.
