### ISSUE TITLE
 Prophet on Vertex Prediction Pipeline Error: deadline_exceeded

### ISSUE THREAD

**Issue by aljab017** [GoogleCloudPlatform/vertex-ai-samples#3487]
## Expected Behavior
I'm following this documentation for the [Prophet on Vertex Pipelines notebook](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/tabular_workflows/prophet_on_vertex_pipelines.ipynb). I expected the prediction pipeline to complete successfully after running the batch prediction job.

## Actual Behavior
The prediction pipeline fails at the model batch prediction step with a deadline_exceeded error. The job consistently fails after running for around 40 minutes, regardless of the dataset size used. Additionally, I am unable to identify the exact source of the issue because the batch prediction logs do not provide any detailed information.
<img width="622" alt="image" src="https://github.com/user-attachments/assets/d927db40-dbab-4e16-978b-72a3e798fb5e">
<img width="636" alt="image" src="https://github.com/user-attachments/assets/9ca9a75e-95fe-4a97-b9cb-73dcb14bdd12">

## Steps to Reproduce the Problem
1. Follow the steps in the [Prophet on Vertex Pipelines notebook](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/tabular_workflows/prophet_on_vertex_pipelines.ipynb) to set up and run the training pipeline.
2. Proceed to the prediction pipeline step, using any dataset.
3. Observe the pipeline fail at the model-batch-predict stage after running for approximately 40 minutes with a deadline_exceeded error.

## Specifications
- Version: google-cloud-aiplatform version '1.59.0', Python version '3.12.2'
- Platform: Google Cloud Vertex AI, OS: Microsoft Windows 11 version '10.0.22631'

**Comment by gericdong** [comment]
Thanks for reporting this issue. This may be a memory issue. Please try to reduct the input size or use a higher memory VM for the prediction job.
