### ISSUE TITLE
Broken icons in `model_garden_gemma_deployment_on_vertex.ipynb`

### ISSUE THREAD

**Issue by palladius** [GoogleCloudPlatform/vertex-ai-samples#3496]
## Expected Behavior

icons on top of https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_gemma_deployment_on_vertex.ipynb should load

## Actual Behavior

Broken icon

## Steps to Reproduce the Problem

1. open https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_gemma_deployment_on_vertex.ipynb
1. see broken images: https://screenshot.googleplex.com/8Yihaupo9ishWLv

**Comment by gericdong** [comment]
@palladius thanks for reporting the issue. The issue has been fixed by Github team.
