### ISSUE TITLE
Llama3.1 Model Garden Vertex AI Open AI :  model does not support the stopSequences parameter

### ISSUE THREAD

**Issue by grappa-ytannous** [GoogleCloudPlatform/vertex-ai-samples#3515]
## Expected Behavior
Successful response from VertexAi chat completion endpoint using openai library

## Actual Behavior
Response 400 
 ("Error code: 400 - [{'error': {'code': 400, 'message': 'Unable to submit request because the model does not support the stopSequences parameter. Remove it and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/overview', 'status': 'INVALID_ARGUMENT'}}]",)

## Steps to Reproduce the Problem

1.Make an http request to VertexAI openai spec endpoint
2.Make sure to pass a "stop" parameter to the request
3.Wait for unsuccessful 400 response

```py
    client = openai.OpenAI(
            base_url=f"https://{env.LOCATION}-aiplatform.googleapis.com/v1beta1/projects/{env.PROJECT_ID}/locations/{env.LOCATION}/endpoints/openapi/chat/completions?",
            api_key=credentials.token,
        )
    try:
        response = client.chat.completions.create(
            model="meta/llama3-405b-instruct-maas",
            messages=[
                {
                    "role": "system",
                    "content": "You are an English to SQL translation tool. Only return the SQL query",
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.2,
            max_tokens=250,
            top_p=1.0,
            stream=False,
            stop="Observation",
        )
        return response
    except Exception as e:
        print("ERROR", e)
```
## Reference : 
https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_openai_api_llama3_1.ipynb

## Inquiry
How to get a list of supported parameters of the model on Vertex AI?

**Comment by kathyyu-google** [comment]
Thank you for this question. The current list of supported parameters is:
- max_tokens
- temperature
- top_k
- top_p
- stream

**Comment by kathyyu-google** [comment]
More parameters are supported now, and documentation is available here: https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/call-vertex-using-openai-library#supported_parameters.
This is in sync with other models, such as Gemini.
