### ISSUE TITLE
Installing Python packages for Gemma2 fine tunning fails in first run

### ISSUE THREAD

**Issue by rsamborski** [GoogleCloudPlatform/vertex-ai-samples#3665]
## Expected Behavior

No errors displayed after running the cell called "Install Python Packages for Finetuning".

## Actual Behavior

Multiple dependency errors after first run of the cell:
![6uczRyA3Ac7enhA](https://github.com/user-attachments/assets/ec662fd1-4d88-4a06-8227-2b237f57b32e)
![C7tHgkZQKHq5BQ9](https://github.com/user-attachments/assets/2cf5eef8-e75a-42ce-a553-c06325360385)

Running the same cell for the second time works fine.

## Steps to Reproduce the Problem

1. Open [model_garden_gemma2_finetuning_on_vertex.ipynb](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_gemma2_finetuning_on_vertex.ipynb) in Colab Enterprise or Colab Standard
1. Run the code in cell called "Install Python Packages for Finetuning"

## Specifications

- Platform: Colab Enterprise and Colab Standard

**Comment by gericdong** [comment]
@lavraicse: can you please help with this issue? Thanks.

**Comment by rayandasoriya** [comment]
https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/3683 should fix this issue.
