### ISSUE TITLE
while tuning the text embedding models in pipeline upload node failed after running Tune Text-Embeddings cells

### ISSUE THREAD

**Issue by shiv-cg** [GoogleCloudPlatform/vertex-ai-samples#3676]
## Expected Behavior
No errors displayed after running the cell called "Tune Text-Embeddings cells".

## Actual Behavior

![image](https://github.com/user-attachments/assets/19c19169-5006-4369-a74d-9b0c6c11ef77)

## Steps to Reproduce the Problem

1.Open [tuned_text-embeddings.ipynb](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/generative_ai/tuned_text-embeddings.ipynb) in google workbench(jypyterlab)
2.Run the code in cell called  "Tune Text-Embeddings cells".

## Specifications

- Platform:google workbench(jypyterlab)

**Comment by gericdong** [comment]
@lee1premium: can you please help us take a look at this? Thanks.

**Comment by jstama** [comment]
Hello! We are also facing the same issue. Any updates?

**Comment by shiv-cg** [comment]
> Hello! We are also facing the same issue. Any updates?

I tried with the Google documentation, but I'm still experiencing the same issue.

**Comment by gericdong** [comment]
@shiv-cg: would you please open a support ticket for the model uploading issue in https://issuetracker.google.com/issues? It seems that this is an known issue and it has been worked on. It'll be easier for you track the progress in the support ticket.
I will close this issue here.

**Comment by shiv-cg** [comment]
> @shiv-cg: would you please open a support ticket for the model uploading issue in https://issuetracker.google.com/issues? It seems that this is an known issue and it has been worked on. It'll be easier for you track the progress in the support ticket. I will close this issue here.

Okay, thank you
