### ISSUE TITLE
Error when uploading custom model to Vertex AI Model registry

### ISSUE THREAD

**Issue by TheFabRepos** [GoogleCloudPlatform/vertex-ai-samples#3710]
## Expected Behavior
Custom Model being uploaded in Vertex AI registry when executing the following cell:

            import google.cloud.aiplatform as aiplatform
            
            MODEL_PATH = "gs://mco-mm/churn"
            MODEL_NAME = "churn"
            IMAGE = "us-docker.pkg.dev/cloud-aiplatform/prediction/tf2-cpu.2-5:latest"
            
            model = aiplatform.Model.upload(
                display_name=MODEL_NAME,
                artifact_uri=MODEL_PATH,
                serving_container_image_uri=IMAGE,
                sync=True,
            )
            MODEL_ID = model.resource_name.split("/")[-1]

in file "notebooks/official/model_monitoring_v2/model_monitoring_for_custom_model_batch_prediction_job.ipynb"

## Actual Behavior

I receive the following error message:

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.FAILED_PRECONDITION
	details = "Service account `[service-789051324393@gcp-sa-aiplatform.iam.gserviceaccount.com](mailto:service-789051324393@gcp-sa-aiplatform.iam.gserviceaccount.com)` does not have `[storage.objects.get]` IAM permission(s) to the directory "gs://mco-mm/churn". Please either copy the files to the Google Cloud Storage bucket owned by your project, or grant the required IAM permission(s) to the service account."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:74.125.126.95:443 {grpc_message:"Service account `[service-789051324393@gcp-sa-aiplatform.iam.gserviceaccount.com](mailto:service-789051324393@gcp-sa-aiplatform.iam.gserviceaccount.com)` does not have `[storage.objects.get]` IAM permission(s) to the directory \"gs://mco-mm/churn\". Please either copy the files to the Google Cloud Storage bucket owned by your project, or grant the required IAM permission(s) to the service account.", grpc_status:9, created_time:"2024-11-14T05:59:29.185932594+00:00"}"
>

I don't have any form of privilege to add permission on the gs://mco-mm/churn directory in the mco-mm bucket.

## Steps to Reproduce the Problem

1. Execute the cells in "notebooks/official/model_monitoring_v2/model_monitoring_for_custom_model_batch_prediction_job.ipynb" and when you reach the cell containing the code reported above then you have the exception. 

## Specifications

- Version: 
- Platform: Colb Enterprise ig Google Cloud Platform

**Comment by gericdong** [comment]
@TheFabRepos: this issue is being looked at. Thanks.

**Comment by gericdong** [comment]
@TheFabRepos: the notebook has been updated. The custom model is currently available at gs://cloud-samples-data/vertex-ai/model-deployment/models/churn.
