### ISSUE TITLE
How to reuse an existing Endpoint in pipeline?

### ISSUE THREAD

**Issue by MMichael-S** [GoogleCloudPlatform/vertex-ai-samples#400]
Hi Experts

## Expected Behavior
Hope to reuse an existing endpoint in pipeline.

Also see that google_cloud_pipeline_components.v1.endpoint has only EndpointCreateOp method.
https://google-cloud-pipeline-components.readthedocs.io/en/google-cloud-pipeline-components-1.0.0/google_cloud_pipeline_components.v1.endpoint.html

Is there a way to reuse an existing Endpoint? And how to reuse it? This will saves costs.

## Actual Behavior
Have to create a new Endpoint in the pipeline.
See that the EndpointCreateOp step is included in all the sample code.

     endpoint_op = EndpointCreateOp(
         project=project,
         location=region,
         display_name="train-automl-flowers",
     )

     ModelDeployOp(
         model=training_run_task.outputs["model"],
         endpoint=endpoint_op.outputs["endpoint"],
         automatic_resources_min_replica_count=1,
         automatic_resources_max_replica_count=1,
     )

## Steps to Reproduce the Problem

N/A

## Specifications

- Version: 
google-cloud-pipeline-components-1.0.0
- 
- Platform:
Google Cloud Vertex AI

**Comment by andrewferlitsch** [comment]
This does appear to be a limitation  the prebuilt components. You could then write your own python component, something like:

@component()
def get_endpoint(resource_name: str,
                               endpoint: Output[Artifact]
                               )
        endpoint = aiplatform.Endpoint(endpoint_name=resource_name)

**Comment by MMichael-S** [comment]
@andrewferlitsch 
Thank you very much. 
We have done in the same way by using customized components to import the existed endpoint.

Code as following,  for someone who need the reference:

    from google_cloud_pipeline_components.types import artifact_types
    from kfp.v2.components import importer_node

    
    endpoint = importer_node.importer(
        artifact_uri="https://us-central1-aiplatform.googleapis.com/v1/projects/xxxxxxxx/locations/us-central1/endpoints/xxxxxx",
        artifact_class=artifact_types.VertexEndpoint,
        metadata={
            "resourceName": "projects/xxxx/locations/us-central1/endpoints/xxxxx"
        }
    )

...

ModelDeployOp(
        model=training_run_task.outputs["model"],
        endpoint=endpoint.outputs['artifact'],
        automatic_resources_min_replica_count=1,
        automatic_resources_max_replica_count=1,
    )
