### ISSUE TITLE
demo vertex kfp pipeline fails with "Invalid Cloud Storage URI for gcs_output_directory"

### ISSUE THREAD

**Issue by ra312** [GoogleCloudPlatform/vertex-ai-samples#424]
## Expected Behavior
the pipeline job has to start

## Actual Behavior
the pipeline job run fails

## Steps to Reproduce the Problem

1. python3 -m pip install google-cloud-aiplatform==1.7.1
google-cloud-pipeline-components==0.2.0
kfp==1.8.9

2. python3 pipellines_intro_kfp.py (obtained by converting https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/pipelines/pipelines_intro_kfp.ipynb)

## Specifications

- Version:
- Platform:

**Comment by andrewferlitsch** [comment]
@ra312 
Hello. Can you be more specific? What do you mean by: obtained by converting https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/pipelines/pipelines_intro_kfp.ipynb)

**Comment by ra312** [comment]
Hi @andrewferlitsch 
Thanks for getting back so quickly! To be more specific, I used Jupiter nbconvert --to script pipelines_intro_kfp.ipynb and edited the script a bit to adjust for the ML workflow I am attempting to productionize

'''
from kfp.v2.dsl import component
from kfp.v2 import compiler
from kfp import dsl
from typing import NamedTuple
import google.cloud.aiplatform as aip
from datetime import datetime
import os
import google

PROJECT_ID = "ds-ml-development"
os.system(f"gcloud config set project ${PROJECT_ID}")
REGION = "europe-west1"  # Change
TIMESTAMP = datetime.now().strftime("%Y%m%d%H%M%S")
BUCKET_NAME = "ml-bucket-dev"
BUCKET_URI = f"gs://{BUCKET_NAME}"
SERVICE_ACCOUNT = (
    f"my-service-account"
    f"@{PROJECT_ID}.iam.gserviceaccount.com"
)
API_ENDPOINT = f"{REGION}-aiplatform.googleapis.com"  # API service endpoint
PIPELINE_ROOT = "{BUCKET_URI}/pipeline_root/intro/url.csv"

aip.init(
    project=PROJECT_ID,
    staging_bucket=BUCKET_URI
)


@component(output_component_file="hw.yaml", base_image="python:3.9")
def hello_world(text: str) -> str:
    print(text)
    return text


@component(packages_to_install=["google-cloud-storage"])
def two_outputs(
    text: str,
) -> NamedTuple(
    "Outputs",
    [
        ("output_one", str),  # Return parameters
        ("output_two", str),
    ],
):
    # the import is not actually used for this simple example, but the import
    # is successful, as it was included in the `packages_to_install` list.
    from google.cloud import storage  # noqa: F401

    o1 = f"output one from text: {text}"
    o2 = f"output two from text: {text}"
    print("output one: {}; output_two: {}".format(o1, o2))
    return (o1, o2)


@component
def consumer(text1: str, text2: str, text3: str):
    print(f"text1: {text1}; text2: {text2}; text3: {text3}")


@dsl.pipeline(
    name="hello-world-v2",
    description="A simple intro pipeline",
    pipeline_root=PIPELINE_ROOT,
)
def pipeline(text: str = "hi there"):
    hw_task = hello_world(text)
    two_outputs_task = two_outputs(text)
    consumer_task = consumer(  # noqa: F841
        hw_task.output,
        two_outputs_task.outputs["output_one"],
        two_outputs_task.outputs["output_two"],
    )


compiler.Compiler().compile(pipeline_func=pipeline,
                            package_path="intro_pipeline.json")


DISPLAY_NAME = "intro_" + TIMESTAMP

job = aip.PipelineJob(
    display_name=DISPLAY_NAME,
    template_path="intro_pipeline.json",
    pipeline_root=PIPELINE_ROOT,
)



runtime_config = google.cloud.aiplatform_v1.types.PipelineJob.RuntimeConfig(gcs_output_directory=BUCKET_URI)
job.runtime_config = runtime_config
job.run(
    service_account=SERVICE_ACCOUNT
)

job.delete()
'''
I debug this script to observe pipeline in vertex AI UI, but get this exception instead
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/12486277/160983201-7ba16456-c6f6-4549-8400-978041df465c.png">

**Comment by ra312** [comment]
I added runtime_config and specified service_account to resolve the Exception

**Comment by andrewferlitsch** [comment]
@ra312 Does the bucket exist? Otherwise you need to create it first.

BUCKET_NAME = "ml-bucket-dev"
BUCKET_URI = f"gs://{BUCKET_NAME}"

**Comment by ra312** [comment]
Hi @andrewferlitsch,
Yes, I made sure the bucket exists

**Comment by ivanmkc** [comment]
Any updates on this?

**Comment by ra312** [comment]
Hi,
I would be happy to look further into the issue (maybe a PR), but we are moving fast to MVP with Vertex, so currently I am using the same PipelineJob with different versions. So if it helps anyone else, here are the versions I am using right now
google-api-core==1.31.5
google-api-python-client==1.12.11
google-auth==1.35.0
google-cloud-aiplatform==1.11.0
google-cloud-storage==1.44.0
google-cloud-bigquery==2.9.0
oauth2client==4.1.3
kfp==1.8.12
requests==2.27.1
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
typing==3.7.4.3
typing-extensions==3.7.4.3
So it seems we could close the issue for now. 
Thanks for getting back to me.

**Comment by andrewferlitsch** [comment]
@ra312 I see what might be a typo. PIPELINE_ROOT should be a folder not a file.

PIPELINE_ROOT = "{BUCKET_URI}/pipeline_root/intro/url.csv"

**Comment by ra312** [comment]
Thanks, @andrewferlitsch for your help! . It did actually work!
