### ISSUE TITLE
Getting an error on  custom-tabular-bq-managed-dataset.ipynb

### ISSUE THREAD

**Issue by dmparish42** [GoogleCloudPlatform/vertex-ai-samples#451]
## Expected Behavior
go through config and then train a model.

## Actual Behavior
During model training, get this error:
INFO:google.cloud.aiplatform.utils.source_utils:Training script copied to:
gs://dmp_vertex_test/aiplatform-2022-04-07-01:12:19.726-aiplatform_custom_trainer_script-0.1.tar.gz.
INFO:google.cloud.aiplatform.training_jobs:Training Output directory:
gs://dmp_vertex_test/aiplatform-custom-training-2022-04-07-01:12:20.066 
INFO:google.cloud.aiplatform.training_jobs:No dataset split provided. The service will use a default split.
INFO:google.cloud.aiplatform.training_jobs:View Training:
https://console.cloud.google.com/ai/platform/locations/us-central1/training/4479230601408282624?project=471881642629
INFO:google.cloud.aiplatform.training_jobs:CustomTrainingJob projects/471881642629/locations/us-central1/trainingPipelines/4479230601408282624 current state:
PipelineState.PIPELINE_STATE_RUNNING
INFO:google.cloud.aiplatform.training_jobs:CustomTrainingJob projects/471881642629/locations/us-central1/trainingPipelines/4479230601408282624 current state:
PipelineState.PIPELINE_STATE_RUNNING
INFO:google.cloud.aiplatform.training_jobs:CustomTrainingJob projects/471881642629/locations/us-central1/trainingPipelines/4479230601408282624 current state:
PipelineState.PIPELINE_STATE_RUNNING
INFO:google.cloud.aiplatform.training_jobs:CustomTrainingJob projects/471881642629/locations/us-central1/trainingPipelines/4479230601408282624 current state:
PipelineState.PIPELINE_STATE_RUNNING
INFO:google.cloud.aiplatform.training_jobs:CustomTrainingJob projects/471881642629/locations/us-central1/trainingPipelines/4479230601408282624 current state:
PipelineState.PIPELINE_STATE_RUNNING
INFO:google.cloud.aiplatform.training_jobs:View backing custom job:
https://console.cloud.google.com/ai/platform/locations/us-central1/training/3781102290421678080?project=471881642629
INFO:google.cloud.aiplatform.training_jobs:CustomTrainingJob projects/471881642629/locations/us-central1/trainingPipelines/4479230601408282624 current state:
PipelineState.PIPELINE_STATE_RUNNING
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-22-ddeb0598cb2f>](https://localhost:8080/#) in <module>
     19         machine_type=TRAIN_COMPUTE,
     20         accelerator_type=TRAIN_GPU.name,
---> 21         accelerator_count=TRAIN_NGPU,
     22     )
     23 else:

6 frames
[/usr/local/lib/python3.7/dist-packages/google/cloud/aiplatform/training_jobs.py](https://localhost:8080/#) in _raise_failure(self)
    898 
    899         if self._gca_resource.error.code != code_pb2.OK:
--> 900             raise RuntimeError("Training failed with:\n%s" % self._gca_resource.error)
    901 
    902     @property

RuntimeError: Training failed with:
code: 3
message: "The replica workerpool0-0 exited with a non-zero status of 1. \nTraceback (most recent call last):\n  File \"/root/.local/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py\", line 36, in <module>\n    import db_dtypes  # type: ignore\nModuleNotFoundError: No module named \'db_dtypes\'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/opt/conda/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/opt/conda/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/root/.local/lib/python3.7/site-packages/aiplatform_custom_trainer_script/task.py\", line 144, in <module>\n    df_train = download_table(training_data_uri)\n  File \"/root/.local/lib/python3.7/site-packages/aiplatform_custom_trainer_script/task.py\", line 141, in download_table\n    return rows.to_dataframe(create_bqstorage_client=False)\n  File \"/root/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py\", line 1925, in to_dataframe\n    _pandas_helpers.verify_pandas_imports()\n  File \"/root/.local/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py\", line 991, in verify_pandas_imports\n    raise ValueError(_NO_DB_TYPES_ERROR) from db_dtypes_import_exception\nValueError: Please install the \'db-dtypes\' package to use this function.\n\nTo find out more about why your job exited please check the logs: [https://](https://github.com/GoogleCloudPlatform/vertex-ai-samples/issues/new)...

## Steps to Reproduce the Problem

1.Am running on colab (and am running as a googler user)

1.Run the colab as is.. no changes..
I am using my google based project and a bucket under that project .

NOTE: feel free to ping me for any more details etc.
dmparish@google.com

## Specifications

- Version:
- Platform:

**Comment by dmparish42** [comment]
Note: looking on moma: I found this bug report .. not sure if it is relevant or not but seems related:[
(https://cloud.google.com/python/docs/reference/bigquery/latest/changelog)Bug Fixes

deps: raise exception when pandas is installed but db-dtypes is not ([#1191](https://github.com/googleapis/python-bigquery/issues/1191)) ([4333910](https://github.com/googleapis/python-bigquery/commit/433391097bae57dd12a93db18fc2bab573d8f128))

**Comment by andrewferlitsch** [comment]
I ran the notebook in Workbench and got the same error:

RuntimeError: Training failed with:
code: 3
message: "The replica workerpool0-0 exited with a non-zero status of 1. \nTraceback (most recent call last):\n  File \"/root/.local/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py\", line 36, in <module>\n    import db_dtypes  # type: ignore\nModuleNotFoundError: No module named \'db_dtypes\'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/opt/conda/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/opt/conda/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/root/.local/lib/python3.7/site-packages/aiplatform_custom_trainer_script/task.py\", line 143, in <module>\n    df_train = download_table(training_data_uri)\n  File \"/root/.local/lib/python3.7/site-packages/aiplatform_custom_trainer_script/task.py\", line 140, in download_table\n    return rows.to_dataframe(create_bqstorage_client=False)\n  File \"/root/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py\", line 1925, in to_dataframe\n    _pandas_helpers.verify_pandas_imports()\n  File \"/root/.local/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py\", line 991, in verify_pandas_imports\n    raise ValueError(_NO_DB_TYPES_ERROR) from db_dtypes_import_exception\nValueError: Please install the \'db-dtypes\' package to use this function.\n\nTo find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=759209241365&resource=ml_job%2Fjob_id%2F6588410562831450112&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%226588410562831450112%22"

**Comment by andrewferlitsch** [comment]
It appears that when the bigquery package is installed, the pandas_helper component is missing a package called db_dtypes. I am manually adding the package to the requirements and see what happens.

**Comment by andrewferlitsch** [comment]
fix by https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/458
