### ISSUE TITLE
error

### ISSUE THREAD

**Issue by skr3178** [GoogleCloudPlatform/vertex-ai-samples#476]
## Actual Behavior
PermissionDenied: 403 Vertex AI API has not been used in project 720070608347 before or it is disabled.

## Steps to Reproduce the Problem

1. run cells: 42 on notebook 03-cloud-training

## Specifications

- Version: [Time Series Forecasting with Vertex AI and BigQuery ML](https://codelabs.developers.google.com/codelabs/time-series-forecasting-with-cloud-ai-platform?hl=en)
- Platform: Vertex AI
PermissionDenied: 403 Vertex AI API has not been used in project 720070608347 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/aiplatform.googleapis.com/overview?project=720070608347 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [links {
  description: "Google developers console API activation"
  url: "https://console.developers.google.com/apis/api/aiplatform.googleapis.com/overview?project=720070608347"
}
, reason: "SERVICE_DISABLED"
domain: "googleapis.com"
metadata {
  key: "consumer"
  value: "projects/720070608347"
}
metadata {
  key: "service"
  value: "aiplatform.googleapis.com"
}
]

**Comment by kweinmeister** [comment]
Hello, does this issue relate to a notebook contained in this repo?

**Comment by ivanmkc** [comment]
No, the link provided is to a Codelab.

Doing an internal code search shows that the owner is @kweinmeister and the authors are @kweinmeister and @sararob. We can close this issue (due to out-of-scope) and log the bug for wherever Codelab issues are logged.
