### ISSUE TITLE
Featurestore Batch data export to CSv using method "batch_read_feature_values" is giving empty result

### ISSUE THREAD

**Issue by rajantiwari-mlg06** [GoogleCloudPlatform/vertex-ai-samples#584]
## Expected Behavior
It should provide the latest values of features from the featurestore

## Actual Behavior

The column values for features are empty only timestamp and entity_is columns have values.
## Steps to Reproduce the Problem

1.
batch_serving_request = featurestore_service_pb2.BatchReadFeatureValuesRequest(
    # featurestore info
    featurestore=admin_client.featurestore_path(PROJECT_ID, REGION, FEATURESTORE_ID),
    # URL for the label data, i.e., Table 1.
    destination=featurestore_service_pb2.FeatureValueDestination(
        csv_destination=io_pb2.CsvDestination(
            gcs_destination=io_pb2.GcsDestination(output_uri_prefix=GCS_DESTINATION_OUTPUT_URI)
        #gcs_source=io_pb2.GcsDestination(GCS_DESTINATION_OUTPUT_URI)
     )
    ),
    bigquery_read_instances=io_pb2.BigQuerySource(input_uri=READ_INSTANCES_URI),
    entity_type_specs=[
        featurestore_service_pb2.BatchReadFeatureValuesRequest.EntityTypeSpec(
            entity_type_id=ENTITY_ID,
            feature_selector=FeatureSelector(
                id_matcher=IdMatcher(
                    ids=feature_ids
                )
            ),
        ),
    ],
)

1.
1.

## Specifications

- Version:
- Platform:GCP

**Comment by andrewferlitsch** [comment]
appears obsolete. FS for Batch Prediction is working with Vertex AI SDK
