### ISSUE TITLE
Error: no "view" mailcap rules found for type "image/png"

### ISSUE THREAD

**Issue by skr3178** [GoogleCloudPlatform/vertex-ai-samples#614]
## Expected Behavior
https://www.youtube.com/watch?v=-2uI3OTYcCE&t=212s

## Actual Behavior
![image](https://user-images.githubusercontent.com/79299617/172028490-083cb29e-7321-4f92-8167-d49384d5930f.png)

## Steps to Reproduce the Problem
where can I find the correct codes?
1.
1.
1.

## Specifications

- Version:Vertex AI
- 
- Platform:

**Comment by andrewferlitsch** [comment]
The cell `visualize` which has no output appears to have been ran after the kernel was restarted. Note, the [1] in front of the cell in the image, instead of [4]
