### ISSUE TITLE
There is no procedure with the name `gds.graph.create.cypher` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

### ISSUE THREAD

**Issue by startr3k** [GoogleCloudPlatform/vertex-ai-samples#619]
## Actual Behavior
Error message : There is no procedure with the name `gds.graph.create.cypher` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

## Steps to Reproduce the Problem
The part of the code 

"with driver.session(database=DB_NAME) as session:
    result = session.read_transaction(
        lambda tx: tx.run(
            """
    CALL gds.graph.create.cypher('client_graph', 
      'MATCH (c:Client) RETURN id(c) as id, c.num_transactions as num_transactions, c.total_transaction_amnt as total_transaction_amnt, c.is_fraudster as is_fraudster',
      'MATCH (c:Client)-[:PERFORMED]->(t:Transaction)-[:TO]->(c2:Client) return id(c) as source, id(c2) as target, sum(t.amount) as amount, "TRANSACTED_WITH" as type ')
    """
        ).data()
    )
"

Instead of **gds.graph.create.cypher**, it should be **gds.graph.project.cypher**

**Comment by andrewferlitsch** [comment]
@startr3k which notebook does this issue refer to?

**Comment by yuhuayang-google** [comment]
This is regarding https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/neo4j/graph_paysim.ipynb

Already fixed by https://github.com/GoogleCloudPlatform/vertex-ai-samples/commit/24904a5999d4050863fab9324a624956e7cffad6

You should be able to close this out.
