### ISSUE TITLE
Create a notebook index in the README

### ISSUE THREAD

**Issue by ivanmkc** [GoogleCloudPlatform/vertex-ai-samples#643]
Feedback has been received that it's hard to find a notebook without clicking into it and viewing the contents.

Although there is a curated list at https://cloud.google.com/vertex-ai/docs/tutorials/jupyter-notebooks?hl=en, it does not include all official notebooks and people might not know about that link.

An effort to add an index to this repo should be explored.

**Comment by ivanmkc** [comment]
One proposal is to auto-generate an index based on a particular marked cell in each ipynb file.

**Comment by ivanmkc** [comment]
@andrewferlitsch AFAIK you are doing some work that will mitigate this. Let me know if I should reassign.

**Comment by andrewferlitsch** [comment]
Work in progress and being evaluated by TW. Next will be a draft updated content strategy proposal that will supercede this issue.

**Comment by andrewferlitsch** [comment]
work in progress

**Comment by andrewferlitsch** [comment]
This task was completed
