### ISSUE TITLE
In notebook_template.ipynb, add a blurb for Googlers to inform viewers that the notebook is created by Googlers.

### ISSUE THREAD

**Issue by ivanmkc** [GoogleCloudPlatform/vertex-ai-samples#644]
Problem: Some feedback has been given that users may think the "community" notebooks are not authored by Google. In fact, "community" notebooks can be authored by anyone (Googlers and non-Googlers alike), but are just not maintained.

Although this is described in the repo's README, users might not read that. To mitigate this, we propose the creation of a short blurb in the notebook_template.ipynb that tells users that the notebook is Google-authored.

**Comment by andrewferlitsch** [comment]
We would have to update (and CI/CD) test over a 100 notebooks for consistency. Does not seem feasible.

**Comment by ivanmkc** [comment]
Closing for now.
