### ISSUE TITLE
Import error while running query on match engine service

### ISSUE THREAD

**Issue by ssistla1998** [GoogleCloudPlatform/vertex-ai-samples#646]
## Expected Behavior
The line 'import match_service_pb2' in the notebook should run without any errors

## Actual Behavior
Throws the error 
---> 18 DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b......)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "match_service.proto":
  google.cloud.aiplatform.container.v1beta1.MatchRequest.deployed_index_id: "google.cloud.aiplatform.container.v1beta1.MatchRequest.deployed_index_id" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchRequest.float_val: "google.cloud.aiplatform.container.v1beta1.MatchRequest.float_val" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchRequest.num_neighbors: "google.cloud.aiplatform.container.v1beta1.MatchRequest.num_neighbors" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchRequest.restricts: "google.cloud.aiplatform.container.v1beta1.MatchRequest.restricts" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchRequest.per_crowding_attribute_num_neighbors: "google.cloud.aiplatform.container.v1beta1.MatchRequest.per_crowding_attribute_num_neighbors" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchRequest.approx_num_neighbors: "google.cloud.aiplatform.container.v1beta1.MatchRequest.approx_num_neighbors" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchRequest.leaf_nodes_to_search_percent_override: "google.cloud.aiplatform.container.v1beta1.MatchRequest.leaf_nodes_to_search_percent_override" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchRequest: "google.cloud.aiplatform.container.v1beta1.MatchRequest" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchResponse.neighbor: "google.cloud.aiplatform.container.v1beta1.MatchResponse.neighbor" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchResponse.Neighbor.id: "google.cloud.aiplatform.container.v1beta1.MatchResponse.Neighbor.id" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchResponse.Neighbor.distance: "google.cloud.aiplatform.container.v1beta1.MatchResponse.Neighbor.distance" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchResponse.Neighbor: "google.cloud.aiplatform.container.v1beta1.MatchResponse.Neighbor" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchResponse: "google.cloud.aiplatform.container.v1beta1.MatchResponse" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.BatchMatchRequest.requests: "google.cloud.aiplatform.container.v1beta1.BatchMatchRequest.requests" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.BatchMatchRequest.BatchMatchRequestPerIndex.deployed_index_id: "google.cloud.aiplatform.container.v1beta1.BatchMatchRequest.BatchMatchRequestPerIndex.deployed_index_id" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.BatchMatchRequest.BatchMatchRequestPerIndex.requests: "google.cloud.aiplatform.container.v1beta1.BatchMatchRequest.BatchMatchRequestPerIndex.requests" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.BatchMatchRequest.BatchMatchRequestPerIndex.low_level_batch_size: "google.cloud.aiplatform.container.v1beta1.BatchMatchRequest.BatchMatchRequestPerIndex.low_level_batch_size" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.BatchMatchRequest.BatchMatchRequestPerIndex: "google.cloud.aiplatform.container.v1beta1.BatchMatchRequest.BatchMatchRequestPerIndex" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.BatchMatchRequest: "google.cloud.aiplatform.container.v1beta1.BatchMatchRequest" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.BatchMatchResponse.responses: "google.cloud.aiplatform.container.v1beta1.BatchMatchResponse.responses" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.BatchMatchResponse.BatchMatchResponsePerIndex.deployed_index_id: "google.cloud.aiplatform.container.v1beta1.BatchMatchResponse.BatchMatchResponsePerIndex.deployed_index_id" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.BatchMatchResponse.BatchMatchResponsePerIndex.responses: "google.cloud.aiplatform.container.v1beta1.BatchMatchResponse.BatchMatchResponsePerIndex.responses" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.BatchMatchResponse.BatchMatchResponsePerIndex.status: "google.cloud.aiplatform.container.v1beta1.BatchMatchResponse.BatchMatchResponsePerIndex.status" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.BatchMatchResponse.BatchMatchResponsePerIndex: "google.cloud.aiplatform.container.v1beta1.BatchMatchResponse.BatchMatchResponsePerIndex" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.BatchMatchResponse: "google.cloud.aiplatform.container.v1beta1.BatchMatchResponse" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.Namespace.name: "google.cloud.aiplatform.container.v1beta1.Namespace.name" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.Namespace.allow_tokens: "google.cloud.aiplatform.container.v1beta1.Namespace.allow_tokens" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.Namespace.deny_tokens: "google.cloud.aiplatform.container.v1beta1.Namespace.deny_tokens" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.Namespace: "google.cloud.aiplatform.container.v1beta1.Namespace" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchService.Match: "google.cloud.aiplatform.container.v1beta1.MatchService.Match" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchService.BatchMatch: "google.cloud.aiplatform.container.v1beta1.MatchService.BatchMatch" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchService: "google.cloud.aiplatform.container.v1beta1.MatchService" is already defined in file "google/cloud/aiplatform/matching_engine/_protos/match_service.proto".
  google.cloud.aiplatform.container.v1beta1.MatchRequest.restricts: "google.cloud.aiplatform.container.v1beta1.Namespace" seems to be defined in "google/cloud/aiplatform/matching_engine/_protos/match_service.proto", which is not imported by "match_service.proto".  To use it here, please add the necessary import.
  google.cloud.aiplatform.container.v1beta1.MatchResponse.neighbor: "google.cloud.aiplatform.container.v1beta1.MatchResponse.Neighbor" seems to be defined in "google/cloud/aiplatform/matching_engine/_protos/match_service.proto", which is not imported by "match_service.proto".  To use it here, please add the necessary import.
  google.cloud.aiplatform.container.v1beta1.BatchMatchRequest.BatchMatchRequestPerIndex.requests: "google.cloud.aiplatform.container.v1beta1.MatchRequest" seems to be defined in "google/cloud/aiplatform/matching_engine/_protos/match_service.proto", which is not imported by "match_service.proto".  To use it here, please add the necessary import.
  google.cloud.aiplatform.container.v1beta1.BatchMatchRequest.requests: "google.cloud.aiplatform.container.v1beta1.BatchMatchRequest.BatchMatchRequestPerIndex" seems to be defined in "google/cloud/aiplatform/matching_engine/_protos/match_service.proto", which is not imported by "match_service.proto".  To use it here, please add the necessary import.
  google.cloud.aiplatform.container.v1beta1.BatchMatchResponse.BatchMatchResponsePerIndex.responses: "google.cloud.aiplatform.container.v1beta1.MatchResponse" seems to be defined in "google/cloud/aiplatform/matching_engine/_protos/match_service.proto", which is not imported by "match_service.proto".  To use it here, please add the necessary import.
  google.cloud.aiplatform.container.v1beta1.BatchMatchResponse.responses: "google.cloud.aiplatform.container.v1beta1.BatchMatchResponse.BatchMatchResponsePerIndex" seems to be defined in "google/cloud/aiplatform/matching_engine/_protos/match_service.proto", which is not imported by "match_service.proto".  To use it here, please add the necessary import.
  google.cloud.aiplatform.container.v1beta1.MatchService.Match: "google.cloud.aiplatform.container.v1beta1.MatchRequest" seems to be defined in "google/cloud/aiplatform/matching_engine/_protos/match_service.proto", which is not imported by "match_service.proto".  To use it here, please add the necessary import.
  google.cloud.aiplatform.container.v1beta1.MatchService.Match: "google.cloud.aiplatform.container.v1beta1.MatchResponse" seems to be defined in "google/cloud/aiplatform/matching_engine/_protos/match_service.proto", which is not imported by "match_service.proto".  To use it here, please add the necessary import.
  google.cloud.aiplatform.container.v1beta1.MatchService.BatchMatch: "google.cloud.aiplatform.container.v1beta1.BatchMatchRequest" seems to be defined in "google/cloud/aiplatform/matching_engine/_protos/match_service.proto", which is not imported by "match_service.proto".  To use it here, please add the necessary import.
  google.cloud.aiplatform.container.v1beta1.MatchService.BatchMatch: "google.cloud.aiplatform.container.v1beta1.BatchMatchResponse" seems to be defined in "google/cloud/aiplatform/matching_engine/_protos/match_service.proto", which is not imported by "match_service.proto".  To use it here, please add the necessary import.

## Steps to Reproduce the Problem

1. Running the notebook with a small set of sentences.
[https://colab.research.google.com/drive/1fgFMR-9dpx13CKZm_uYRwbji79PT83Pu?usp=sharing&authuser=3#scrollTo=bM5Mfc4aucgw]

## Specifications

- Version: Running on google colab
![Screen Shot 2022-06-20 at 5 08 16 PM](https://user-images.githubusercontent.com/107895666/174691379-67a3b103-7ef5-4482-aeda-41bd01d511a8.png)
![Screen Shot 2022-06-20 at 5 08 36 PM](https://user-images.githubusercontent.com/107895666/174691385-e015df5c-15f3-4a27-a7fc-b8ae661dcb38.png)

- Platform:

**Comment by ivanmkc** [comment]
Can you provide to the link to the file in question?

**Comment by ssistla1998** [comment]
https://colab.research.google.com/drive/13UfI6CJKXCtDeDdQKig5ZJk23-eQAX8-#scrollTo=1urwW_CcZ-vc

**Comment by ssistla1998** [comment]
Hi, any update?

**Comment by ssistla1998** [comment]
Hi any update?

**Comment by ivanmkc** [comment]
Hi, sorry was out of office. I can't access your link.
This is the link to the proper usage of matching engine: https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/matching_engine/sdk_matching_engine_for_indexing.ipynb

Does that help?

**Comment by ivanmkc** [comment]
Closing due to no response.
