### ISSUE TITLE
Model monitoring notebook failing on weekly regression test.

### ISSUE THREAD

**Issue by ivanmkc** [GoogleCloudPlatform/vertex-ai-samples#647]
Build log (you might not have access): https://pantheon.corp.google.com/cloud-build/builds;region=us-central1/ea184a8b-a6a7-40c3-b3a2-c2076f81c4fc?project=python-docs-samples-tests

See attached notebook:
[model_monitoring.ipynb.zip](https://github.com/GoogleCloudPlatform/vertex-ai-samples/files/8951154/model_monitoring.ipynb.zip)

**Comment by andrewferlitsch** [comment]
I observed the same while trying to update the notebook to current notebook standard. Something about monitoring_config is empty.

**Comment by mco-gh** [comment]
Hi folks,

Sorry for the delay, I've been busy with a bunch of customer engagements.
I'll take a look at this on Monday (tomorrow).

Marc

**Comment by mco-gh** [comment]
Actually better make that next Monday (July 4). I have to give three talks
tomorrow and then I'll be ooo wed-fri of this week.

**Comment by andrewferlitsch** [comment]
regression failure previously fixed
