### ISSUE TITLE
Broken link in the notebook 

### ISSUE THREAD

**Issue by hyunuk** [GoogleCloudPlatform/vertex-ai-samples#672]
The notebook in [vertex-ai-samples/notebooks/official/migration/UJ15 Vertex SDK AutoML Object Tracking.ipynb](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/migration/UJ15%20Vertex%20SDK%20AutoML%20Object%20Tracking.ipynb) has several broken links that are just redirected to `todo`.

I tried to run it in Colab but [the link](https://colab.research.google.com/github/GoogleCloudPlatform/ai-platform-samples/blob/master/vertex-ai-samples/tree/master/notebooks/official/migration/UJ15%20Vertex%20SDK%20AutoML%20Object%20Tracking.ipynb) is also invalid.

**Comment by leahecole** [comment]
cc @andrewferlitsch - last person who committed to this notebook
