### ISSUE TITLE
Question: How to get explanations while using Batch Predictions

### ISSUE THREAD

**Issue by SophieBoule99** [GoogleCloudPlatform/vertex-ai-samples#688]
## Expected Behavior
I am trying to get explanations while using batch_predict() on a custom xgboost model. This notebook is the only example I have found of a non-tensorflow implementation of explainable AI. I have managed to get explanations using an endpoint. When running batch_predict() (from bigquery to bigquery) through a vertex pipeline I am expecting the output bigquery table to be appended with an extra explanations column.

## Actual Behavior
When using the ExplanationMetadata format advised in this notebook and used for the endpoint my batch predictions do not run successfully and I get the following error: `Nameless input are allowed only if there is a single input in the explanation metadata.`
After researching the issue I have discovered that since my input to batch predict is a single list with feature values it is treated as a single input and I should set the ExplanationMetadata with a single feature input with a chosen name, as follows: 
```
EXPLANATION_METADATA = aiplatform.explain.ExplanationMetadata(
    inputs=
        {"features": {}}
    ,
    outputs={"probability": {}},
    )
```

This metadata setup allows for the batch_predictions to run through but no explanations column is appended to my bigquery output.

Could you advise me on the format of the metadata inputs using the vertex batch predictions?

**Comment by ivanmkc** [comment]
Which notebook are you referring to?

**Comment by SophieBoule99** [comment]
I am refering to this notebook: https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/explainable_ai/SDK_Custom_Container_XAI.ipynb 
It gives an example of enabling explanations on a non-tensorflow model but only deploys it to an endpoint. It does not use it for batch predictions.

**Comment by gericdong** [comment]
@SophieBoule99 : I am following up to see if you still need any assistance with this issue?

**Comment by gericdong** [comment]
I am closing this issue.
@SophieBoule99: please feel free to reopen this issue or open a new question if you still need any assistance. Thanks.
