### ISSUE TITLE
Missing XLA configuration on jupyterLab vertex

### ISSUE THREAD

**Issue by ma-batita** [GoogleCloudPlatform/vertex-ai-samples#697]
## Expected Behavior
the 'TrainingArguments' should not give me the XLA error because I am not using TPU. I am working on GPU only

## Actual Behavior
with the trainingarg 
`
args = TrainingArguments(
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    num_train_epochs=1,
    weight_decay=0.01,
    output_dir="/tmp/cls"
)
`

I get `RuntimeError: tensorflow/compiler/xla/xla_client/computation_client.cc:273 : Missing XLA configuration`

## Steps to Reproduce the Problem
1. running the tuto in the main branch and I just got the error

## Specifications
- Platform: jupyterlab vertex

**Comment by nicain** [comment]
Triaging to @andrewferlitsch. Might be more appropriate for @RajeshThallam.

**Comment by andrewferlitsch** [comment]
@ma-batita Can you let us know which tutorial you had the error.

btw> XLA works for GPUs and TPUs. Perhaps you using a CPU training image with a GPU?

**Comment by andrewferlitsch** [comment]
@ma-batita fyi> from notebook author
Hi Andrew, not completely sure but looking at the TrainingArguments it appears to be the community content notebook I own. I believe the issue they are reporting could be because they are running training code locally on a CPU based notebook instance

**Comment by RajeshThallam** [comment]
@ma-batita 

- Are you running [this tutorial](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/community-content/pytorch_text_classification_using_vertex_sdk_and_gcloud/pytorch-text-classification-vertex-ai-train-tune-deploy.ipynb) on Vertex AI Workbench notebook? 
- If you running on Vertex AI Workbench notebooks, can you let us know if you have GPU attached to instance? and what Notebook kernel are you asing?

**Comment by ma-batita** [comment]
@RajeshThallam @andrewferlitsch thanks you for your responses.
I think the problem is coming from vertex itself. I manage to surpass the error by just uninstalling torch xla `!pip uninstall torch-xla`.  

thanks!
