### ISSUE TITLE
RuntimeError: Training failed with: code: 8 message: "The following quota metrics exceed quota limits: aiplatform.googleapis.com/custom_model_training_nvidia_k80_gpus"

### ISSUE THREAD

**Issue by Dudledood** [GoogleCloudPlatform/vertex-ai-samples#700]
## Expected Behavior
train model successed

## Actual Behavior
RuntimeError: Training failed with: code: 8 message: "The following quota metrics exceed quota limits: aiplatform.googleapis.com/custom_model_training_nvidia_k80_gpus"

## Steps to Reproduce the Problem

1.here my colab: https://colab.research.google.com/drive/1W_friSAYA2WowY0tOB8XiL2rhm5xGGSq?usp=sharing
(have few modify from https://colab.research.google.com/github/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/custom/sdk-custom-image-classification-online.ipynb#scrollTo=title)
error occur when run step: Tutorial > train the model

## Specifications

- Version: 2022/6/10
Update drivefs from 57.0.5 to 58.0.3 and tensorflow from 2.8.0 to 2.8.2
Support more than 100 repos in the GitHub repo selector shown in the open dialog and the clone to GitHub dialog
Show full notebook names on hover in the open dialog
Improve the color contrast for links, buttons, and the ipywidgets.Accordion widget in dark mode
- Platform: google colab

#Note
I check my quota in gcp(IAM and Admin) >AI Platform Training & Prediction API(region : us-central1) > Edit quota, it's currently on highest limit: 1572864000, so I don't know why it's not enough
I'm new in this place please kind to me

**Comment by gericdong** [comment]
Hi @Dudledood, I wanted to follow up to see if you still have this error?

**Comment by Davidnet** [comment]
Hi @gericdong I do have this error and I cannot seem to edit the provided quota:

![image](https://user-images.githubusercontent.com/3343006/216987727-f89391d5-9dab-40cd-a074-1f9cf74e0326.png)

**Comment by Davidnet** [comment]
Nevermind, I found it using the following filters:

![image](https://user-images.githubusercontent.com/3343006/217008461-b4c095d3-ba66-4089-a243-2e93fa58d3bb.png)


bit difficult to search

**Comment by gericdong** [comment]
If there is no more assistance needed, I am closing the issue. Thanks for the feedback!

**Comment by KISHAN8888** [comment]
I am getting the same error. Please help me to fix it.
