### ISSUE TITLE
Authentication process needed for automl-text-classification.ipynb

### ISSUE THREAD

**Issue by myoshimu** [GoogleCloudPlatform/vertex-ai-samples#71]
## Expected Behavior
I tried to run [the sample notebook](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/master/notebooks/official/automl/automl-text-classification.ipynb) of Vertex AI AutoML text classification model. 

## Actual Behavior
This notebooks has no authentication process so the user can not access the GCP resources.

## Steps to Reproduce the Problem
1. [Open the notebook](https://console.cloud.google.com/vertex-ai/notebooks/deploy-notebook?download_url=https%3A%2F%2Fraw.githubusercontent.com%2FGoogleCloudPlatform%2Fvertex-ai-samples%2Fmaster%2Fnotebooks%2Fofficial%2Fautoml%2Fautoml-text-classification.ipynb&_ga=2.13444159.926770121.1632210293-765888617.1631078205) in colab
1. Run all the cell

## Workaround
Running following cell resolve the issue

```
from google.colab import auth
auth.authenticate_user()
```

**Comment by nicain** [comment]
I just opened the notebook, and it worked without any problems.  So far I cannot reproduce.

**Comment by nicain** [comment]
fix: https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/88
