### ISSUE TITLE
is it possible to pass script_path="task.py" to CustomTrainingJobOp?

### ISSUE THREAD

**Issue by hilliao** [GoogleCloudPlatform/vertex-ai-samples#724]
I observe the [google_cloud_pipeline_components.v1.custom_job.CustomTrainingJobOp](https://google-cloud-pipeline-components.readthedocs.io/en/google-cloud-pipeline-components-0.2.1/google_cloud_pipeline_components.experimental.custom_job.html) may not have a parameter to accept a script path like the following [code section](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/custom/sdk-custom-image-classification-online.ipynb):

```
job = aiplatform.CustomTrainingJob(
    display_name=JOB_NAME,
    script_path="task.py",
    container_uri=TRAIN_IMAGE,
    requirements=["tensorflow_datasets==1.3.0"],
    model_serving_container_image_uri=DEPLOY_IMAGE,
)

MODEL_DISPLAY_NAME = "cifar10-" + TIMESTAMP

# Start the training
if TRAIN_GPU:
    model = job.run(
        model_display_name=MODEL_DISPLAY_NAME,
        args=CMDARGS,
        replica_count=1,
        machine_type=TRAIN_COMPUTE,
        accelerator_type=TRAIN_GPU.name,
        accelerator_count=TRAIN_NGPU,
    )
else:
    model = job.run(
        model_display_name=MODEL_DISPLAY_NAME,
        args=CMDARGS,
        replica_count=1,
        machine_type=TRAIN_COMPUTE,
        accelerator_count=0,
    )
```

Is it possible to achieve the training above in with [Vertex Pipeline code sample](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb) below?

```
custom_job_task = CustomTrainingJobOp(
        project=project,
        display_name="model-training",
        worker_pool_specs=[
            {
                "containerSpec": {
                    "args": TRAINER_ARGS,
                    "env": [{"name": "AIP_MODEL_DIR", "value": WORKING_DIR}],
                    "imageUri": "gcr.io/google-samples/bw-cc-train:latest",
                },
                "replicaCount": "1",
                "machineSpec": {
                    "machineType": "n1-standard-16",
                    "accelerator_type": aip.gapic.AcceleratorType.NVIDIA_TESLA_K80,
                    "accelerator_count": 2,
                },
            }
        ],
    )
```

I am guessing gcr.io/google-samples/bw-cc-train:latest is probably @andrewferlitsch custom build container image for the model training which may contain task.py already. I want to understand if CustomTrainingJobOp can accept script_path="task.py"; if not, I am guessing developers would need to create a kfp.v2.dsl.component to include the 1st code section of `aiplatform.CustomTrainingJob`?

**Comment by andrewferlitsch** [comment]
@hilliao Sorry for the late response.
CustomPythonPackageTrainingJob takes an entire python package.

CustomTrainingJob does accept script_path=task.py.

It is CustomContainerJob where the script is burned into the container,
