### ISSUE TITLE
Problem with TF runtime optimized deployment 

### ISSUE THREAD

**Issue by sayakpaul** [GoogleCloudPlatform/vertex-ai-samples#743]
## Expected Behavior

Referring to this notebook: https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/vertex_endpoints/optimized_tensorflow_runtime/bert_optimized_online_prediction.ipynb.

## Actual Behavior

Deployment with the TF runtime should pass. 

## Steps to Reproduce the Problem

1. Run https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/vertex_endpoints/optimized_tensorflow_runtime/bert_optimized_online_prediction.ipynb.
1. It will fail for `tf_opt_gpu_deployed_model`. Logs attached. 
[downloaded-logs-20220726-171156.json.zip](https://github.com/GoogleCloudPlatform/vertex-ai-samples/files/9189457/downloaded-logs-20220726-171156.json.zip)

## Specifications

Colab

**Comment by sayakpaul** [comment]
@vlasenkoalexey

**Comment by sayakpaul** [comment]
Same happens with `tf_opt_lossy_gpu_deployed_model` too:

[downloaded-logs-20220726-172037.json.zip](https://github.com/GoogleCloudPlatform/vertex-ai-samples/files/9189481/downloaded-logs-20220726-172037.json.zip)

**Comment by vlasenkoalexey** [comment]
Looks like you modified Colab and trying to deploy your models on NVIDIA K80: 
```
I0726 11:47:56.340117      26 gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10882 MB memory:  -> device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7
```
Optimized TensorFlow Runtime is not supporting old GPUs, see documentation: https://cloud.google.com/vertex-ai/docs/predictions/optimized-tensorflow-runtime

**Comment by sayakpaul** [comment]
Sorry for flagging this without reading the documentation. Maybe including a note about it in the Colab would be helpful?
