### ISSUE TITLE
Extending the TRT text classification example to images

### ISSUE THREAD

**Issue by sayakpaul** [GoogleCloudPlatform/vertex-ai-samples#748]
@vlasenkoalexey 

I am trying to extend your TRT example to images. I am trying a Vision Transformer architecture based on Transformers (like BERT). So, I think it should be fairly well supported. I am not sure how should I export the model in that case. 

I tried with an approach, but that failed with the request payload. Here is my notebook (apologies for the rough edges in the code): https://gist.github.com/sayakpaul/d8b9876fad1421b7cb8301d0dcaf4946.

I guess that we need to export the model such that it operates on strings of images (decoding would happen internally within the model), but that fails with the request payload complaining about the decoding process. 

Could you suggest anything here?

**Comment by vlasenkoalexey** [comment]
It is common to take some time to figure out how prediction requests should look like.
First, make it working locally using OSS TensorFlow Serving container running in docker. Sample has instructions how to do that.
Check model signatures using saved_model_cli, as far as I understand it expects dictionary where image bytes are expected (it is likely going to be loaded.signatures["serving_default"].structured_input_signature[0].keys()[0])

Here is a sample I have for EfficientNet that is slightly different:
```python
def generate_requests(base_dir, files, dimensions=[600,600]):
    requests = []
    for filename in files:
        tensors = []
        img_raw = tf.io.read_file(filename)
        img = tf.io.decode_image(img_raw)
        img = tf.image.convert_image_dtype(img, tf.float32)
        img = tf.image.resize(img, dimensions)
        tensors.append(img)
        requests.append(tf.stack(tensors, axis=0).numpy())

    with open(f'{base_dir}/requests_{len(files)}_1.jsonl', "w") as f:
        for request in requests:
            d = dict()
            d["image_input"] = request.tolist()
            f.write(json.dumps(d))
            f.write("\n")
```
It might be easier to make it working for REST protocol first.
After you have it working locally, upload to Vertex Prediction using optimized TensorFlow runtime.
Also note that that format for Vertex Prediction public endpoint REST requests is different from TF Serving REST requests.

Hope it helps.

**Comment by sayakpaul** [comment]
Thanks. 

I have a notebook where I have verified if the model works locally with TF Serving (both for REST and gRPC): https://github.com/sayakpaul/deploy-hf-tf-vision-models/blob/main/hf_vision_model_tfserving.ipynb.

Note that the model export varies in that notebook in that I am making the model take strings as input, decode that on the fly, and then perform predictions.

**Comment by andrewferlitsch** [comment]
appears that the question has been answered

**Comment by sayakpaul** [comment]
@vlasenkoalexey so, after studying your suggestion, it looks like I need the model to accept image URIs (GCS URIs)? Because sending over multiple image bytes (i.e., bytes of multiple images) seems to be still broken ([reference](https://github.com/GoogleCloudPlatform/practical-ml-vision-book/blob/master/09_deploying/09d_bytes.ipynb))?
