### ISSUE TITLE
Question: Notebook to use Feature Store values in Model training / Batch Predictions

### ISSUE THREAD

**Issue by jakepaw** [GoogleCloudPlatform/vertex-ai-samples#815]
Hello, 

I have a general question to gather if there are any examples or plan to be examples of how to use the features we store in feature store. I have walked through the notebooks using Feature Store, which show how to gather values online /offline but there is no notebook describing how to ingest those features for other aspects of Vertex AI (Into a pipeline for predictions or used to train models).

Thank you,
Jake

**Comment by gericdong** [comment]
@jakepaw I am following up this case. It's been awhile and I wanted to confirm if you still need assistance with this question? Thanks.

**Comment by gericdong** [comment]
I am closing this issue for now as I assume that assistance is not longer needed. 
Thanks.
