### ISSUE TITLE
Beam pipeline error in  notebooks > community > ml_ops > stage1 > mlops_data_management.ipynb

### ISSUE THREAD

**Issue by tottenjordan** [GoogleCloudPlatform/vertex-ai-samples#816]
## Expected Behavior
In [mlops_data_management.ipynb](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/ml_ops/stage1/mlops_data_management.ipynb), expecting the dataflow pipeline to run successfully

## Actual Behavior
get error: 
```
KeyError: "tip_bin [while running 'Write TF Test Data/Write/WriteImpl/WriteBundles-ptransform-559']"
```

## Steps to Reproduce the Problem

Run [mlops_data_management.ipynb](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/ml_ops/stage1/mlops_data_management.ipynb)

## Error derives from this code snippet in the beam pipeline:
```
            # Convert raw test data to JSON (for batch prediction)
            json_test_data = (raw_test_data) | "Convert Batch Test Data" >> beam.Map(
                convert_to_jsonl, label=label
            )
```
* `label` is not an arg of `beam.Map()`
* changing to `convert_to_jsonl(data=raw_test_data,  label=label)` yields an error ~PCollections can't delete
* Pipeline runs successfully when changing to the snippet below, but not sure if this will break downstream dependencies on this dataset

```
            # Convert raw test data to JSON (for batch prediction)
            json_test_data = (raw_test_data) | "Convert Batch Test Data" >> beam.Map(
                convert_to_jsonl
            )
```

## Specifications

- Version:
- Platform:

**Comment by andrewferlitsch** [comment]
I seen that error occur when there is a mismatch between TF and TFDV versions

**Comment by andrewferlitsch** [comment]
Fixed by PR
https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/997
