### ISSUE TITLE
Extending to batched inputs

### ISSUE THREAD

**Issue by sayakpaul** [GoogleCloudPlatform/vertex-ai-samples#832]
Referring to https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/ml_ops/stage6/get_started_with_tf_serving_function.ipynb. 

How can I include multiple encoded image strings in a single request? 

In particular, 

```py
instances = [{serving_input: {"b64": b64str}}]

prediction = endpoint.predict(instances=instances)

print(prediction)
```

Here `b64str` is just one single image. 

Cc: @andrewferlitsch

**Comment by sayakpaul** [comment]
Furthermore, how would I need to construct the request payloads when using the TF runtime as shown in [this notebook](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/vertex_endpoints/optimized_tensorflow_runtime/bert_optimized_online_prediction.ipynb)?

**Comment by andrewferlitsch** [comment]
@sayakpaul As a list:

instances = [{serving_input: {"b64": b64str_1}},
                      {serving_input: {"b64": b64str_2}},
]

**Comment by sayakpaul** [comment]
@andrewferlitsch thank you, but how should they be structured if I were to create a warmup request payload for TF runtime ([reference](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/vertex_endpoints/optimized_tensorflow_runtime/bert_optimized_online_prediction.ipynb))?

**Comment by sayakpaul** [comment]
@andrewferlitsch any inputs?
