### ISSUE TITLE
Missing end_run() in Experiments sample notebook

### ISSUE THREAD

**Issue by jaycee-li** [GoogleCloudPlatform/vertex-ai-samples#850]
A customer is following the [Track parameters and metrics for custom training jobs](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/ml_metadata/sdk-metric-parameter-tracking-for-custom-jobs.ipynb) tutorial. However, the state is in constant running when viewing in UI.
<img width="1746" alt="image" src="https://user-images.githubusercontent.com/102714969/183988250-64108cf7-b572-4bcc-81f9-ebff410789d3.png">

I think the problem is we didn't call `aiplatform.end_run()` after we are done with the experimentRun. Could you please add this line (before **View data in the Cloud Console** section) to the notebook? Thanks!

**Comment by andrewferlitsch** [comment]
Submitted fix in PR https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/863
