### ISSUE TITLE
Matching engine deny list not working

### ISSUE THREAD

**Issue by niladridutt** [GoogleCloudPlatform/vertex-ai-samples#922]
Reposting from stackoverflow- https://stackoverflow.com/questions/73565771/how-does-google-vertex-ai-matching-engine-deny-list-work

**Comment by niladridutt** [comment]
Can you please help me with this?- @proppy @olegshaldybin @dazuma @fhirschmann

**Comment by mattcarrolldev** [comment]
@niladridutt this repos issues are for issues with Vertex AI samples. If you are having a issue with one of the samples please open a new issues and include in the issue itself:

1. a detailed description of the issues
2. A full list of steps to reproduce the issue
3. The expected result
4. The actual result

Please also include any other information/materials that would help with reproducing your issue like details about your environment (OS, language, runtime, versions, etc.), screenshots, or any other data you think might help.
