### ISSUE TITLE
Changing region in the model monitoring notebook make it fail as the dataset is only in us-central1

### ISSUE THREAD

**Issue by leclem** [GoogleCloudPlatform/vertex-ai-samples#925]
## Expected Behavior
Being able to run the notebook without an error even if region is changed, or to not allow/suggest user to change region
https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/model_monitoring/model_monitoring.ipynb

## Actual Behavior
An error is sent if region of endpoint/model monitogine is changed from us-central1 

## Steps to Reproduce the Problem

1. Execute https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/model_monitoring/model_monitoring.ipynb changing region with another than us-central1
2. Receive an email "Vertex AI deployed model monitoring job creation failed." with error message "Input dataset location is not consistent with server location, more details: Cannot read and write in different locations: source: us-central1, destination: europe-west4'"

## Specifications

- Platform: Google Cloud Managed Notebooks

**Comment by andrewferlitsch** [comment]
@leclem Vertex AI doesn't support cross-region resource access. You would need to create a dataset in the new region
