### ISSUE TITLE
How come NVIDIA driver installation isn't needed in pytorch_image_classification_single_gpu_with_vertex_sdk_and_torchserve?

### ISSUE THREAD

**Issue by skeller88** [GoogleCloudPlatform/vertex-ai-samples#931]
## Expected Behavior
In the [pytorch_image_classification_single_gpu_with_vertex_sdk_and_torchserve](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/community-content/pytorch_image_classification_single_gpu_with_vertex_sdk_and_torchserve) example, I would expect there to be a driver installation step for the pipeline to use the GPU. 

## Actual Behavior
Does the [pytorch image](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/community-content/pytorch_image_classification_single_gpu_with_vertex_sdk_and_torchserve/trainer/Dockerfile) already contain the nvidia drivers, or does it install the nvidia driver onto the host somehow? I asked a similar question [here](https://stackoverflow.com/questions/73642322/running-custom-docker-container-with-gpu-using-vertex-ai-pipelines-how-to-inst).

**Comment by ivanmkc** [comment]
According to our guidelines, the community-content folder has no support provided. The original author is no longer available to support this sample.

@andrewferlitsch do you have an answer to this question about Vertex AI pipelines? https://stackoverflow.com/questions/73642322/running-custom-docker-container-with-gpu-using-vertex-ai-pipelines-how-to-inst
