### ISSUE TITLE
Unexpected costs by executing a sample notebook

### ISSUE THREAD

**Issue by verhoek** [GoogleCloudPlatform/vertex-ai-samples#941]
## Expected Behavior

By reading the sample notebook https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/experiments/comparing_local_trained_models.ipynb, I expected to not be charged $300 by running the underlying compute engine for just a few minutes.

Expected would have been a disclaimer near the text:

_"[Select or create a Google Cloud project](https://console.cloud.google.com/cloud-resource-manager). When you first create an account, you get a $300 free credit towards your compute/storage costs."_

with the text:

_"Be careful, if you did not activate tensorboard in vertex ai yet, execution of the following steps results in being charged an amount of $300."_

## Actual Behavior

Although the compute engine costs were negligible, the enabling of tensorboard charges the user an amount of $300.
Tensorboard was previously free of charge. No disclaimer of additional charges are mentioned.

## Steps to Reproduce the Problem

1. Execute the sample notebook

## Specifications

- Version:
- Platform:

**Comment by ivanmkc** [comment]
@inardini can you address the comments regarding your notebook?

**Comment by inardini** [comment]
Thanks for the feedback. @ivanmkc I will open a PR to update the notebook accordingly.

**Comment by andrewferlitsch** [comment]
was fixed by Ivan Nardini
